### ISSUE TITLE
Adding a summarizer results in a NotFoundError

### ISSUE THREAD

**Issue by jeromepl** [tensorforce/tensorforce#477]
I haven't been able to add a summarizer to my PPO Agent object. The settings I used are (although I did try other configurations without success):
```python
summarizer=dict(
    directory='./logs-tensorboard',
    steps=50,
    labels=['losses']            
)
```

And running this results in the following error:
```
tensorflow.python.framework.errors_impl.NotFoundError: Resource localhost/logdir:./logs-tensorboard/class tensorflow::SummaryWriterInterface does not exist.
```

Maybe this is related to https://github.com/reinforceio/tensorforce/issues/415, although I did not test my code with a tensorforce version prior to the fix for that issue. This might also just be something I missed from the documentation!

**Comment by AlexKuhnle** [comment]
Interesting, I wouldn't have expected `'graph'` to be a necessary label, but might be I just never tried without. If so, I will change graph recording to default (it's probably something one wants to do anyway).

**Comment by jeromepl** [comment]
Thanks for that @kevinanschau that works well as a temporary solution.

However, after running more tests, I have found a few are more issues related to the summarizer:
- labels `'inputs'`, `'states'`, `'actions'`, `'rewards'` do not seem to output any data (no plot for these shows up in tensorboard)
- using the `'configuration'` label with a `meta_dict` results in a `module 'tensorflow.summary' has no attribute 'generic'` error on line 259 of `meta_parameter_recorder.py`

**Comment by AlexKuhnle** [comment]
I fixed the `"graph"` issue (not required anymore) and replaced the wrong `tf.summary.generic` with `tf.contrib.summary.generic` in `meta_parameter_recorder.py`, but wasn't able to fully fix the histogram issue yet (it only shows some histograms now).

**Comment by joelthelion** [comment]
Do you have an example summary_spec that works with your recent changes? I can't get anything to display in tensorboard, and it seems the event files are not getting filled with anything, no matter what labels I try...

**Comment by AlexKuhnle** [comment]
Does the following work (folder: `[current_directory]/temp/...`)?
```
"summarizer": {
    "directory": "temp",
    "labels": ["graph", "total-loss"]
}
```

**Comment by joelthelion** [comment]
Nope: it outputs not error, but it produces a mostly empty event file. Attaching my code and the output in case I'm missing something obvious.
[debug.zip](https://github.com/reinforceio/tensorforce/files/2347531/debug.zip)

Using the git version of tensorforce from yesterday, on python3.7 distributed with Arch Linux.

**Comment by AlexKuhnle** [comment]
Ah, see the problem now: PPO uses an episode-based update mechanism, but you're episode never terminates, hence an update never happens and the `total-loss` summary is never called. You could either switch to DQN (timestep-based) or change the update mode to `timesteps`. Be aware, though, that the latter is theoretically problematic (but may practically still work well).

**Comment by joelthelion** [comment]
Thanks a lot for looking into my code! I added a Runner as shown in the quickstart example, and sure enough, it now works.

Quick note: one of the reasons I got it wrong was the example in the main readme. It shows the use of the PPOAgent without episodes. I understand this is supposed to be a simplified example to illustrate the library, but you might want to add some sort of disclaimer or warning.

**Comment by AlexKuhnle** [comment]
Cool, closing then.

**Comment by AlexKuhnle** [comment]
Ah, sorry, I missed that this was actually a "sub-issue" and the main point is not yet fully resolved.

**Comment by ljf19920902** [comment]
I have the same issue with BOTH ppo and vpg agent. I tried to add `'graph'` in `'labels'`, it runs but the other label options (e.g., `'inputs'`, `'gradients'`) did not show up as expected.

**Comment by kkuette** [comment]
I'm using PPO, and it only output ```"total-loss"```.

**Comment by Deathn0t** [comment]
Hi all, in order to add a gradient histogram to the summary I tried to replace that : 

```
applied = self.tf_optimizer.minimize(loss=loss, var_list=variables)  # colocate_gradients_with_ops=True
```
with the following code :
```
grads = tf.gradients(loss, tf.trainable_variables())
            grads = list(zip(grads, tf.trainable_variables()))
            # Op to update all variables according to their gradient
            applied = self.tf_optimizer.apply_gradients(grads_and_vars=grads)
            if 'gradients' in self.summary_labels:
                for grad, var in grads:i
                    tf.contrib.summary.histogram("%s-grad" % var.name, grad)
```
File is : `tensorforce/core/optimizers/tf_optimizer.py`
Here is the error I am having when I run the code :
```
Traceback (most recent call last):
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 217, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 202, in constant
    name=name).outputs[0]
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1746, in __init__
    self._control_flow_post_processing()
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1757, in _control_flow_post_processing
    self._control_flow_context.AddOp(self)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2438, in AddOp
    self._AddOpInternal(op)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2475, in _AddOpInternal
    for x in external_inputs if x.outputs]
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2475, in <listcomp>
    for x in external_inputs if x.outputs]
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 80, in identity
    return gen_array_ops.identity(input, name=name)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3264, in identity
    "Identity", input=input, name=name)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1746, in __init__
    self._control_flow_post_processing()
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1755, in _control_flow_post_processing
    control_flow_util.CheckInputFromValidContext(self, input_tensor.op)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_util.py", line 314, in CheckInputFromValidContext
    raise ValueError(error_msg + " See info log for more details.")
ValueError: Cannot use 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/gradients/Add/Identity' as input to 'ppo/observe-timestep/cond/optimization/multi-step/step/while/Identity_3' because they are in different while loops. See info log for more details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 524, in _apply_op_helper
    values, as_ref=input_arg.is_ref).dtype.name
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 217, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 202, in constant
    name=name).outputs[0]
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1746, in __init__
    self._control_flow_post_processing()
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1757, in _control_flow_post_processing
    self._control_flow_context.AddOp(self)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2438, in AddOp
    self._AddOpInternal(op)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2475, in _AddOpInternal
    for x in external_inputs if x.outputs]
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2475, in <listcomp>
    for x in external_inputs if x.outputs]
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 80, in identity
    return gen_array_ops.identity(input, name=name)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3264, in identity
    "Identity", input=input, name=name)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1746, in __init__
    self._control_flow_post_processing()
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1755, in _control_flow_post_processing
    control_flow_util.CheckInputFromValidContext(self, input_tensor.op)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_util.py", line 314, in CheckInputFromValidContext
    raise ValueError(error_msg + " See info log for more details.")
ValueError: Cannot use 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/gradients/Add/Identity_1' as input to 'ppo/observe-timestep/cond/optimization/multi-step/step/while/Identity_3' because they are in different while loops. See info log for more details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/experiments/ppo_mathfun_2D.py", line 176, in <module>
    episode_rewards, runner = go_learning(fw)
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/experiments/ppo_mathfun_2D.py", line 130, in go_learning
    agent, environment = get_agent_environment(func_wrapper)
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/experiments/ppo_mathfun_2D.py", line 117, in get_agent_environment
    labels=['gradients_scalar', 'gradients_histogram', 'losses']
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/agents/ppo_agent.py", line 155, in __init__
    entropy_regularization=entropy_regularization
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/agents/learning_agent.py", line 141, in __init__
    batching_capacity=batching_capacity
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/agents/agent.py", line 76, in __init__
    self.model = self.initialize_model()
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/agents/ppo_agent.py", line 183, in initialize_model
    likelihood_ratio_clipping=self.likelihood_ratio_clipping
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/models/pg_prob_ratio_model.py", line 88, in __init__
    gae_lambda=gae_lambda
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/models/pg_model.py", line 98, in __init__
    requires_deterministic=False
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/models/distribution_model.py", line 90, in __init__
    discount=discount
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/models/memory_model.py", line 114, in __init__
    reward_preprocessing=reward_preprocessing
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/models/model.py", line 235, in __init__
    self.setup()
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/models/model.py", line 310, in setup
    independent=independent
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/models/memory_model.py", line 605, in create_operations
    independent=independent
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/models/model.py", line 1254, in create_operations
    self.create_observe_operations(reward=reward, terminal=terminal)
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/models/model.py", line 1187, in create_observe_operations
    reward=reward
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 367, in __call__
    return self._call_func(args, kwargs)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 310, in _call_func
    result = self._func(*args, **kwargs)
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/models/memory_model.py", line 566, in tf_observe_timestep
    return tf.cond(pred=optimize, true_fn=true_fn, false_fn=tf.no_op)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2048, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1895, in BuildCondBranch
    original_result = fn()
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/models/memory_model.py", line 562, in true_fn
    optimize = self.fn_optimization(**batch)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 367, in __call__
    return self._call_func(args, kwargs)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 310, in _call_func
    result = self._func(*args, **kwargs)
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/models/pg_model.py", line 305, in tf_optimization
    next_internals=next_internals
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/models/memory_model.py", line 491, in tf_optimization
    return self.optimizer.minimize(**arguments)
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/core/optimizers/optimizer.py", line 143, in minimize
    deltas = self.step(time=time, variables=variables, **kwargs)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 367, in __call__
    return self._call_func(args, kwargs)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 310, in _call_func
    result = self._func(*args, **kwargs)
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/core/optimizers/multi_step.py", line 89, in tf_step
    _, deltas = tf.while_loop(cond=cond, body=body, loop_vars=(0, deltas))
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3232, in while_loop
    return_same_structure)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2952, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2887, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/core/optimizers/multi_step.py", line 82, in body
    step_deltas = self.optimizer.step(time=time, variables=variables, arguments=arguments, **kwargs)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 359, in __call__
    return self._call_func(args, kwargs)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 305, in _call_func
    result = self._func(*args, **kwargs)
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/core/optimizers/subsampling_step.py", line 103, in tf_step
    **kwargs
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 359, in __call__
    return self._call_func(args, kwargs)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 305, in _call_func
    result = self._func(*args, **kwargs)
  File "/Users/Deathn0t/Documents/Argonne/dl-nas/tensorforce/core/optimizers/tf_optimizer.py", line 70, in tf_step
    grads = tf.gradients(loss, tf.trainable_variables())
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 596, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 663, in _GradientsHelper
    to_ops, from_ops, colocate_gradients_with_ops, func_graphs, xs)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 190, in _PendingCount
    between_op_list, between_ops, colocate_gradients_with_ops)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1432, in MaybeCreateControlFlowState
    loop_state.AddWhileContext(op, between_op_list, between_ops)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1244, in AddWhileContext
    grad_state = GradLoopState(forward_ctxt, outer_grad_state)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 822, in __init__
    cnt, forward_index = forward_ctxt.AddForwardLoopCounter(outer_grad_state)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2546, in AddForwardLoopCounter
    index = math_ops.add(switch_n[1], 1)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 297, in add
    "Add", x=x, y=y, name=name)
  File "/Users/Deathn0t/anaconda2/envs/balsam/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'y' to a tensor and failed. Error: Cannot use 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/gradients/Add/Identity_1' as input to 'ppo/observe-timestep/cond/optimization/multi-step/step/while/Identity_3' because they are in different while loops. See info log for more details.
```
Does anyone have an idea to solve that ?

**Comment by AlexKuhnle** [comment]
These kind of error messages came up a few times already, in different contexts. It really seems as if while-loop control flow is troublesome in TensorFlow. Maybe have to work on fundamental design at some point again...

Anyway, what potentially helps in this case is to unroll the while loop in multi-step [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/optimizers/multi_step.py#L32). If I remember correctly, that option was somewhat less performant, but don't think it's a major issue.

**Comment by AlexKuhnle** [comment]
Summaries work with the new branch (`major-revision`), which will be merged with master soon, hence already closing summary-related issues. Currently supported labels:
```python
"bernoulli", "beta", "categorical", "distributions", "dropout", "entropy", "gaussian", "graph",
"loss", "losses", "objective-loss", "regularization-loss", "relu", "updates", "variables"
```
Others will be added, and please feel free to post specific requests here.
