### ISSUE TITLE
PPO agent throws Retval[0] does not have value

### ISSUE THREAD

**Issue by 80dB** [tensorforce/tensorforce#540]
I'm getting the above exception when training the PPO agent. Strangely enough it doesn't always happen at the same episode/etc. 

I saw someone else report a similar issue but it got closed. 

This was with Tensorflow 1.12 and the github version of Tensorforce (thought I'd give it a try instead of the 0.43 version from PIP).

'''
  File "C:\Program Files\Microsoft\ML Server\PYTHON_SERVER\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Program Files\Microsoft\ML Server\PYTHON_SERVER\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Program Files\Microsoft\ML Server\PYTHON_SERVER\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "....py", line 396, in <module>

  File "d:\tensorflow\tensorforce-master\tensorforce\agents\agent.py", line 188, in observe
    index=index
  File "d:\tensorflow\tensorforce-master\tensorforce\models\model.py", line 1496, in observe
    episode = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "C:\Program Files\Microsoft\ML Server\PYTHON_SERVER\lib\site-packages\tensorflow\python\training\monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "C:\Program Files\Microsoft\ML Server\PYTHON_SERVER\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "C:\Program Files\Microsoft\ML Server\PYTHON_SERVER\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files\Microsoft\ML Server\PYTHON_SERVER\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Program Files\Microsoft\ML Server\PYTHON_SERVER\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "C:\Program Files\Microsoft\ML Server\PYTHON_SERVER\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Program Files\Microsoft\ML Server\PYTHON_SERVER\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Program Files\Microsoft\ML Server\PYTHON_SERVER\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Program Files\Microsoft\ML Server\PYTHON_SERVER\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Program Files\Microsoft\ML Server\PYTHON_SERVER\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value
'''

**Comment by AlexKuhnle** [comment]
Hey, which issue reported a similar problem? I remember seeing it before, but can't recall in what context. Definitely looks like something fundamental, there are quite a few weird issues related to TensorFlow. I'm currently working at a revised version of Tensorforce which hopefully gets rid of these (see branch), I hope that will also help here.

**Comment by 80dB** [comment]
The other issue was on another agent:
https://github.com/tensorforce/tensorforce/issues/398

**Comment by AlexKuhnle** [comment]
Hmm, in that issue there was also no clear solution, it seems. Sorry, I have no idea what could cause this problem. One thing you could try is run the branch version of PPO and see whether it still happens.

**Comment by 80dB** [comment]
I tried to run the major-revision branch with my test script but ran straight into an issue that I just rewrote my script to use Agent.from_spec and that one doesn't work anymore.

**Comment by AlexKuhnle** [comment]
I added a basic `Agent.from_spec(spec)` option again, since it generally makes sense. However, note that the branch will be a completely new version, so you probably need to adapt parameter/argument names here and there. If you post your specification dict here, I can tell you what to change.

**Comment by 80dB** [comment]
It took me a small bit of time to modify code so it worked with the major-rev branch. But running into some issues. 

Setting actions_exploration results in an error, internal_lstm results in an error, lstm also (but then again that one never worked), I did get a very basic dense network working with ppo agent, but didnt test it long enough to know if the above error occurs, mostly because it's not representative.

Also on a side node, the Runner was modified to allow evaluation runs, but at the same time I think it made it very difficult to run an evaluation run on another environment. I have two datasets/environments, the train-env and test-env. I don't want to know how well RL works on the train-set as it'll probably do very well on it (eventually).

**Comment by AlexKuhnle** [comment]
Yeah, sorry, a few features are not working yet. Exploration is under way, LSTM soon as well, and before merging with master I want to finally get the internal_lstm to work as well. So with LSTM it would be representative? Then let's check again when it's done.

Regarding the runner, good point. What do you think about the following interface: `runner.run(environment=..., evaluation_environment=..., etc)`, so make both the training environment and optionally a testing environment an argument of run?

**Comment by 80dB** [comment]
LSTM is a yes for me. Not impossible without it but it performs overall better on my data then just dense or conv1d.

As for runner, yes I think having a parameter for test-environment would be perfect. Name wise it was also a bit unclear which callback was called after each episode (this used to be episode_finished). Would have to be able to see if it was a eval run or train run.

**Comment by AlexKuhnle** [comment]
Yes, `episode_finished` was renamed to just `callback`, since I want to move away from insisting on episodes in the future and alternatively offer a timestep-based callback. `callback` is called during training, `evaluation_callback` after the periodic evaluation episodes.

**Comment by AlexKuhnle** [comment]
The `lstm` and `internal_lstm` layers work now, although the `internal_lstm` layer is still not trained as supposed. Nonetheless worth trying, as people reported improved results even without the intended optimization implementation. The whole issue should be addressed soon.

**Comment by 80dB** [comment]
Running this DQN agent (very limited in configuration):
{
    "type": "dqn",
    "discount": 0.999,
    "double_q_model": true,
    "update_mode": {
        "unit": "timesteps",
        "batch_size": 64,
        "frequency": 4
    }
}

With this network:
[
    {
        "type": "lstm",
        "size": 256
    },
    {
        "type": "internal_lstm",
        "size": 256
    }
]

Resulted in a Retval[0] does not have a value.  It ran fine with a pooling-concat + double internal_lstm's. And it only crashes on training, not on evaluation.

**Comment by AlexKuhnle** [comment]
Does the following roughly correspond to what you tried (as for me this seems to be working fine):

```python
environment = UnittestEnvironment(
    states=dict(type='int', shape=(4,), num_values=3),
    actions=dict(type='int', shape=(), num_values=3),
    timestep_range=(200, 1000)
)

agent = DQNAgent(
    states=environment.states(), actions=environment.actions(),
    discount=0.999, double_q_model=True,
    update_mode=dict(unit='timesteps', batch_size=64, frequency=4),
    network=[
        dict(type='embedding', size=32),
        dict(type='lstm', size=32),
        dict(type='internal_lstm', size=32)
    ]
)

runner = Runner(agent=agent, environment=environment)

runner.run(num_episodes=10000)
```

**Comment by 80dB** [comment]
This one returns the error rather quickly:
```python
import numpy as np

class TestEnv():
    def reset(self):
        return self.get_state()

    def get_state(self):
        return np.zeros((112,5))

    def execute(self, actions):
        return self.get_state(), False, 0

def main():
    network_spec = [
        dict(type='lstm', size=256),
        dict(type='internal_lstm', size=256)
    ]

    agent_spec = dict(
        type="dqn",
        discount=0.999,
        double_q_model=True,
        update_mode=dict(
            unit="timesteps",
            batch_size=64,
            frequency=4
        )
    )

    from tensorforce.agents import Agent
    agent = Agent.from_spec(
        spec=agent_spec,
        states=dict(type='float', shape=[112,5]),
        actions=dict(type='int', shape=(), num_values=2),
        network=network_spec
    )

    from tensorforce.execution import Runner
    runner = Runner(agent, TestEnv())
    runner.run(num_episodes=1000)

if __name__ == "__main__":
    main()
```

**Comment by AlexKuhnle** [comment]
The LSTM problem should be fixed now (seems to require the `parallel_iterations` argument [here](https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn) to be > sequence length, for whatever reason).
