### ISSUE TITLE
NAF example does not work -->  tensorforce/tensorforce/tests/test_naf_agent.py

### ISSUE THREAD

**Issue by aGiant** [tensorforce/tensorforce#544]
Hi,
NAFAgent does not work and the configurations were not accepted by naf_agent.py. Please give us some guidance here, many thanks!

**Comment by AlexKuhnle** [comment]
Could you post the error message you're getting, and what exactly you run, config, environment?

**Comment by aGiant** [comment]
Direct from  tensorforce/tensorforce/tests/test_naf_agent.py:

config = dict(
        actions_exploration=dict(
            type='ornstein_uhlenbeck'
        ),
        update_mode=dict(
            unit='timesteps',
            batch_size=8,
            frequency=4
        ),
        memory=dict(
            type='replay',
            include_next_states=True,
            capacity=100
        ),
        optimizer=dict(
            type='adam',
            learning_rate=1e-2
        ),
        target_sync_frequency=10
        # memory=dict(
        #     type='replay',
        #     capacity=1000
        # ),
        # optimizer=dict(
        #     type='adam',
        #     learning_rate=0.001
        # ),
        # batch_size=8,
        # first_update=8,
        # repeat_update=4
)

Errors:
Traceback (most recent call last):
  File "/home/llu/c7_triangle/train_tensorforce.py", line 74, in <module>
    target_sync_frequency=10
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/agents/naf_agent.py", line 131, in __init__
    entropy_regularization=entropy_regularization
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/agents/learning_agent.py", line 141, in __init__
    batching_capacity=batching_capacity
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 80, in __init__
    self.model = self.initialize_model()
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/agents/naf_agent.py", line 158, in initialize_model
    huber_loss=self.huber_loss
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/q_naf_model.py", line 88, in __init__
    huber_loss=huber_loss
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/q_model.py", line 98, in __init__
    requires_deterministic=True
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/distribution_model.py", line 90, in __init__
    discount=discount
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/memory_model.py", line 114, in __init__
    reward_preprocessing=reward_preprocessing
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 217, in __init__
    self.setup()
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 290, in setup
    independent=independent
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/memory_model.py", line 605, in create_operations
    independent=independent
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 1201, in create_operations
    terminal=terminal
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 1178, in create_atomic_observe_operations
    reward=reward
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 360, in __call__
    return self._call_func(args, kwargs)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 306, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/memory_model.py", line 566, in tf_observe_timestep
    return tf.cond(pred=optimize, true_fn=true_fn, false_fn=tf.no_op)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2086, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1930, in BuildCondBranch
    original_result = fn()
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/memory_model.py", line 562, in true_fn
    optimize = self.fn_optimization(**batch)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 360, in __call__
    return self._call_func(args, kwargs)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 306, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/q_model.py", line 252, in tf_optimization
    next_internals=next_internals
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/memory_model.py", line 491, in tf_optimization
    return self.optimizer.minimize(**arguments)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/core/optimizers/optimizer.py", line 139, in minimize
    deltas = self.step(time=time, variables=variables, **kwargs)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 360, in __call__
    return self._call_func(args, kwargs)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 306, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/core/optimizers/tf_optimizer.py", line 70, in tf_step
    applied = self.tf_optimizer.minimize(loss=loss, var_list=variables)  # colocate_gradients_with_ops=True
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 410, in minimize
    name=name)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 593, in apply_gradients
    self._create_slots(var_list)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/training/adam.py", line 135, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 1139, in _zeros_slot
    new_slot_variable = slot_creator.create_zeros_slot(var, op_name)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py", line 183, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py", line 157, in create_slot_with_initializer
    dtype)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py", line 65, in _create_slot_var
    validate_shape=validate_shape)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1487, in get_variable
    aggregation=aggregation)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1237, in get_variable
    aggregation=aggregation)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 523, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1925, in wrapped_custom_getter
    *args, **kwargs)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 524, in custom_getter
    variable = getter(name=name, **kwargs)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 524, in custom_getter
    variable = getter(name=name, **kwargs)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 879, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
ValueError: Variable naf/observe-timestep/optimization/adam/step/naf/observe-timestep/optimization/adam/step/loss/loss-per-instance/state-value/apply/W/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

originally defined at:
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 245, in setup
    self.setup_components_and_tf_funcs()
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/q_naf_model.py", line 92, in setup_components_and_tf_funcs
    super(QNAFModel, self).setup_components_and_tf_funcs(custom_getter)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/q_model.py", line 109, in setup_components_and_tf_funcs
    super(QModel, self).setup_components_and_tf_funcs(custom_getter)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/distribution_model.py", line 120, in setup_components_and_tf_funcs
    custom_getter = super(DistributionModel, self).setup_components_and_tf_funcs(custom_getter)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/memory_model.py", line 148, in setup_components_and_tf_funcs
    kwargs=dict(summary_labels=self.summary_labels)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/core/optimizers/optimizer.py", line 160, in from_spec
    kwargs=kwargs
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/util.py", line 192, in get_object
    return obj(*args, **kwargs)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/core/optimizers/tf_optimizer.py", line 51, in __init__
    super(TFOptimizer, self).__init__(scope=(scope or optimizer), summary_labels=summary_labels)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/core/optimizers/optimizer.py", line 52, in __init__
    custom_getter=custom_getter
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 154, in make_template
    **kwargs)


originally defined at:
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 245, in setup
    self.setup_components_and_tf_funcs()
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/q_naf_model.py", line 92, in setup_components_and_tf_funcs
    super(QNAFModel, self).setup_components_and_tf_funcs(custom_getter)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/q_model.py", line 109, in setup_components_and_tf_funcs
    super(QModel, self).setup_components_and_tf_funcs(custom_getter)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/distribution_model.py", line 120, in setup_components_and_tf_funcs
    custom_getter = super(DistributionModel, self).setup_components_and_tf_funcs(custom_getter)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/memory_model.py", line 180, in setup_components_and_tf_funcs
    custom_getter_=custom_getter
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 154, in make_template
    **kwargs)


originally defined at:
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 245, in setup
    self.setup_components_and_tf_funcs()
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/q_naf_model.py", line 92, in setup_components_and_tf_funcs
    super(QNAFModel, self).setup_components_and_tf_funcs(custom_getter)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/q_model.py", line 109, in setup_components_and_tf_funcs
    super(QModel, self).setup_components_and_tf_funcs(custom_getter)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/distribution_model.py", line 120, in setup_components_and_tf_funcs
    custom_getter = super(DistributionModel, self).setup_components_and_tf_funcs(custom_getter)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/memory_model.py", line 132, in setup_components_and_tf_funcs
    custom_getter = super(MemoryModel, self).setup_components_and_tf_funcs(custom_getter)
  File "/home/llu/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 551, in setup_components_and_tf_funcs
    custom_getter_=custom_getter
  File "/home/llu/.local/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 154, in make_template
    **kwargs)

**Comment by AlexKuhnle** [comment]
Thanks for confirming. Unfortunately this seems related to TensorFlow- and TensorForce-internal variable handling, which apparently doesn't work well together anymore. I can't think of a quick fix, but in the new version that I'm currently preparing (see branch `major-revision`), variable handling (and other aspects) are approached differently, so it should work there. Feel free to check it out already, however, note that it's still under development.

**Comment by giorgionicola** [comment]
Ok thanks, do you know which previous version of tensorflow might be compatible with the latest github version of tensorforce?

**Comment by AlexKuhnle** [comment]
Unfortunately not, but I would guess maybe 1.10 or 1.9 could work (haven't really kept track of these changes in the last months). One thing I noticed when starting to properly redesign the Tensorforce architecture: the current master version uses an apparently older optimizer variable interface ([here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/core/optimizers/tf_optimizer.py#L79)), while TensorFlow at some point seems to have changed things on that front (compare [here](https://github.com/tensorforce/tensorforce/blob/major-revision/tensorforce/core/optimizers/tf_optimizer.py#L89)). For most simpler use cases such changes in TensorFlow don't matter, but unfortunately the variable handling for Tensorforce is a bit more involved. Generally, it's probably best to migrate to the new branch version in the next weeks.

**Comment by aGiant** [comment]
yes, I installed this version yesterday.

**Comment by aGiant** [comment]
Still no update and errors remain the same till today.

**Comment by AlexKuhnle** [comment]
Sorry, but does the exception really still appear with the most recent branch version? The most recent one unfortunately relies on features from version 1.13, so you need to manually upgrade to `tensorflow==1.13.0rc0`)

**Comment by AlexKuhnle** [comment]
Unfortunately the new version is coming along slower than expected.

**Comment by AlexKuhnle** [comment]
Improved
