### ISSUE TITLE
Game 2048 isn't runnable on major-revision branch

### ISSUE THREAD

**Issue by brokenloop** [tensorforce/tensorforce#561]
It looks as if  the [2048 Game](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/contrib/game_2048.py) is outdated, and isn't runnable on the `major-revision` branch. I've managed to fix some simple issues (replacing ` def execute(self, action):` with `def execute(self, actions=None):` for example), but I still can't get it to run with with a ppo agent and basic mlp network. 

Here is the config I'm using: 

```
from tensorforce.agents import PPOAgent
from tensorforce.execution import Runner
from tensorforce.contrib.game_2048 import Game2048

environment = Game2048()

agent = PPOAgent(
    states=environment.states(), actions=environment.actions(),
    # MLP network
    network=[dict(type='dense', size=32, activation='relu'), dict(type='dense', size=32, activation='relu')],
    # Update every 5 episodes, with a batch of 10 episodes
    update_mode=dict(unit='episodes', batch_size=10, frequency=5),
    # Memory sampling most recent experiences, with a capacity of 2500 timesteps
    # (2500 > [10 episodes] * [200 max timesteps per episode])
    memory=dict(type='latest', include_next_states=False, capacity=2500),
    discount=0.99, entropy_regularization=0.01,
    # MLP baseline
    baseline_mode='states', baseline=dict(type='mlp', sizes=[32, 32]),
    # Baseline optimizer
    baseline_optimizer=dict(
        type='multi_step', optimizer=dict(type='adam', learning_rate=1e-3), num_steps=5
    ),
    gae_lambda=0.97, likelihood_ratio_clipping=0.2,
    # PPO optimizer
    step_optimizer=dict(type='adam', learning_rate=3e-4),
    # PPO multi-step optimization: 25 updates, each calculated for 20% of the batch
    subsampling_fraction=0.2, optimization_steps=25
)

runner = Runner(agent=agent, environment=environment) 

runner.run(num_episodes=1000000, max_episode_timesteps=200)

runner.close()
```

And here is the exception it's throwing for me:  

```
Traceback (most recent call last):
  File "C:/Users/[MY-PATH]/tensorforce/slither_pit_test.py", line 45, in <module>
    subsampling_fraction=0.2, optimization_steps=25
  File "C:\Users\[MY-PATH]\tensorforce\tensorforce\agents\ppo_agent.py", line 135, in __init__
    likelihood_ratio_clipping=likelihood_ratio_clipping
  File "C:\Users\[MY-PATH]\tensorforce\tensorforce\core\models\pg_prob_ratio_model.py", line 56, in __init__
    gae_lambda=gae_lambda
  File "C:\Users\[MY-PATH]\tensorforce\tensorforce\core\models\pg_model.py", line 55, in __init__
    entropy_regularization=entropy_regularization, requires_deterministic=False
  File "C:\Users\[MY-PATH]\tensorforce\tensorforce\core\models\distribution_model.py", line 71, in __init__
    "Invalid output rank for network: {}.".format(len(output_spec['shape']))
tensorforce.exception.TensorforceError: Invalid output rank for network: 2.
```

Does anyone have any idea what might be causing this exception, and how I would go about fixing it?

**Comment by AlexKuhnle** [comment]
That seems due to the state shape being 2-rank, but the dense layers and the output of the network requiring a 1-rank tensor. The flatten layer needs to be added again, but can be simulated by `dict(type='pooling', reduction='concat')`, which should help if you add it as the first layer.

**Comment by AlexKuhnle** [comment]
Added the flatten layer again, for convenience.

**Comment by brokenloop** [comment]
That makes sense, thanks for the feedback. I'm assuming it's also necessary to add a flattening layer to the baseline? I can train a model using the environment if I add a flattening layer and remove the baseline altogether, but the model doesn't seem to improve at all after training.

**Comment by AlexKuhnle** [comment]
This can be closed?
