### ISSUE TITLE
Receiving NotImplementedError when restoring agent.

### ISSUE THREAD

**Issue by ZeroMaxinumXZ** [tensorforce/tensorforce#570]
So, I'm receiving a not implemented error when I try to restore the agent....
Code:
agent = Agent(...)
agent.restore_model(savedfileofmodel'sdirectory)

Is this due to it not being implemented, because I've seen another issue that had nearly the exact same code that supposedly worked?  Or is it due to the filepath...?

**Comment by AlexKuhnle** [comment]
Is this on the master branch? Could you post the stacktrace? Helps identifying where exactly the NotImplementedError is thrown...

**Comment by ZeroMaxinumXZ** [comment]
Yes, it's on the pypi (pip) version.
Full traceback:

Traceback (most recent call last):
  File "/home/user/Documents/algernon-master/algernon/start.py", line 52, in <module>
    agent = agent_build()
  File "/home/user/Documents/algernon-master/algernon/agent.py", line 17, in agent_build
    batching_capacity = 32
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 80, in __init__
    self.model = self.initialize_model()
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 94, in initialize_model
    raise NotImplementedError
NotImplementedError

**Comment by ZeroMaxinumXZ** [comment]
Agent loading code:

try:
        agent = Agent(
            states=dict(type='float', shape=(screen_size()[1], screen_size()[0])),
            actions=dict(type='int', num_actions=ceil(act_screen_size()[1]*.001)*1000),
            batching_capacity = 32
        )
        agent.restore_model(join(getcwd(), "models"))
        print("Agent loaded successfully...")

**Comment by ZeroMaxinumXZ** [comment]
Ok, I've figured out how to restore a model (Changed Agent to DQN as per the note in initialize_model...), however this error shows up...

Full stacktrace:
Using TensorFlow backend.
WARNING:tensorflow:From /home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-03-10 23:55:35.333741: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-10 23:55:35.354888: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3000000000 Hz
2019-03-10 23:55:35.355150: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x3d846c0 executing computations on platform Host. Devices:
2019-03-10 23:55:35.355186: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /home/user/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Curiousity engine model loaded successfully.
WARNING:tensorflow:From /home/user/.local/lib/python3.6/site-packages/tensorforce/models/model.py:1081: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-03-10 23:55:38.879134: W tensorflow/core/framework/allocator.cc:124] Allocation of 2654208000 exceeds 10% of system memory.
WARNING:tensorflow:From /home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,128,128] rhs shape= [3,256,256]
     [[{{node save/Assign_6}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1276, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,128,128] rhs shape= [3,256,256]
     [[node save/Assign_6 (defined at /home/user/.local/lib/python3.6/site-packages/tensorforce/models/model.py:591) ]]

Caused by op 'save/Assign_6', defined at:
  File "start.py", line 52, in <module>
    agent = agent_build()
  File "/home/user/Documents/algernon-master/algernon/agent.py", line 27, in agent_build
    network = network
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/agents/dqn_agent.py", line 131, in __init__
    entropy_regularization=entropy_regularization
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/agents/learning_agent.py", line 141, in __init__
    batching_capacity=batching_capacity
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 80, in __init__
    self.model = self.initialize_model()
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/agents/dqn_agent.py", line 158, in initialize_model
    huber_loss=self.huber_loss
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/models/q_model.py", line 98, in __init__
    requires_deterministic=True
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/models/distribution_model.py", line 90, in __init__
    discount=discount
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/models/memory_model.py", line 114, in __init__
    reward_preprocessing=reward_preprocessing
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 217, in __init__
    self.setup()
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 325, in setup
    self.setup_saver()
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 591, in setup_saver
    save_relative_paths=True
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 354, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [3,128,128] rhs shape= [3,256,256]
     [[node save/Assign_6 (defined at /home/user/.local/lib/python3.6/site-packages/tensorforce/models/model.py:591) ]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 52, in <module>
    agent = agent_build()
  File "/home/user/Documents/algernon-master/algernon/agent.py", line 29, in agent_build
    agent.restore_model(join(getcwd(), "models"))
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 273, in restore_model
    self.model.restore(directory=directory, file=file)
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 1493, in restore
    self.saver.restore(sess=self.session, save_path=file)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1312, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [3,128,128] rhs shape= [3,256,256]
     [[node save/Assign_6 (defined at /home/user/.local/lib/python3.6/site-packages/tensorforce/models/model.py:591) ]]

Caused by op 'save/Assign_6', defined at:
  File "start.py", line 52, in <module>
    agent = agent_build()
  File "/home/user/Documents/algernon-master/algernon/agent.py", line 27, in agent_build
    network = network
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/agents/dqn_agent.py", line 131, in __init__
    entropy_regularization=entropy_regularization
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/agents/learning_agent.py", line 141, in __init__
    batching_capacity=batching_capacity
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 80, in __init__
    self.model = self.initialize_model()
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/agents/dqn_agent.py", line 158, in initialize_model
    huber_loss=self.huber_loss
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/models/q_model.py", line 98, in __init__
    requires_deterministic=True
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/models/distribution_model.py", line 90, in __init__
    discount=discount
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/models/memory_model.py", line 114, in __init__
    reward_preprocessing=reward_preprocessing
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 217, in __init__
    self.setup()
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 325, in setup
    self.setup_saver()
  File "/home/user/.local/lib/python3.6/site-packages/tensorforce/models/model.py", line 591, in setup_saver
    save_relative_paths=True
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 354, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [3,128,128] rhs shape= [3,256,256]
     [[node save/Assign_6 (defined at /home/user/.local/lib/python3.6/site-packages/tensorforce/models/model.py:591) ]]

**Comment by AlexKuhnle** [comment]
Yes, you need to use the agent type of the model to be loaded. Regarding the second error, is it by chance using a different network config? `lhs shape= [3,128,128] rhs shape= [3,256,256]` seems to indicate that? Otherwise I'm not sure what is wrong there, maybe worth checking whether it happens when you train a new agent just for a minute, then save and load again...

**Comment by ZeroMaxinumXZ** [comment]
Ok, it works, closing this issue... :+1:
