### ISSUE TITLE
How to test validation set while training?

### ISSUE THREAD

**Issue by bbliao** [tensorforce/tensorforce#579]
Hi, thanks for the great work!

I am a newbie in this framework. What I am doing is using the PPO agent to generate a path in a network. So I revised the Game_2048 example and its environment. For each episode, I randomly choose a node in the network as the start, and let the agent select the "proper" neighbor next node to generate a path. Everything goes fine, the loss is decreasing, the entropy is decreasing, and the reward is increasing. I test the trained model after training with `agent.restore_model`.

The state, action, and network are described in #577

However, I want to test the validation set while training like so many supervised learning. I didn't find any examples, so I add some codes in the `episode_finished` function for each 1000 episodes as:
```
    def episode_finished(r):
        if r.episode % 10 == 0:
            add_to_summary_reward(tag='reward', value=sum(r.episode_rewards[-10:]) / 10, step=r.timestep)
        if r.episode % 1000 == 0 and r.episode > 0:
            test_start_time = time.time()
            sps = r.timestep / (time.time() - r.start_time)
            logger.info("Finished episode {ep} after {ts} timesteps. "
                        "Steps Per Second {sps}".format(ep=r.episode, ts=r.timestep, sps=sps))
            """
                test on top 500 hot station
            """
            start_id_list_hot = get_top_k_station_id_list()
            valid_len = len(start_id_list_hot)
            cnt = 0
            reward_list_hot = np.zeros(valid_len, dtype=np.float)
            for start_id in start_id_list_hot:
                if cnt > 0 and cnt % 100 == 0:
                    logger.info("testing: {} / {}".format(cnt, valid_len))
                reward_list_hot[cnt] = top_k_save_time_single(start_id)
                cnt += 1
            sorted_reward_hot = np.sort(reward_list_hot)
            top_k_result_list_hot = get_top_500_result(sorted_reward_hot)
            add_to_summary("hot", top_k_result_list_hot, r.timestep)
            print_list_result("Hot station result:", top_k_result_list_hot)
            logger.info("Test cost time: {cost_time}".format(cost_time=time.time() - test_start_time))
        return True
```

After first 1000 episodes, the agent starts to test on the validation set, and it outputs the result of the validation set. However, it crashes when retraining for the second 1000 episodes:

```
10%|▉         | 999/10000 [02:55<52:39,  2.85it/s]2019-03-27 17:19:23,765 [MainThread  ] [INFO ]  Finished episode 1000 after 20017 timesteps. Steps Per Second 113.775630107
 10%|█         | 1000/10000 [03:11<52:39,  2.85it/s]2019-03-27 17:22:48,898 [MainThread  ] [INFO ]  testing: 100 / 500
2019-03-27 17:25:16,357 [MainThread  ] [INFO ]  testing: 200 / 500
2019-03-27 17:27:31,099 [MainThread  ] [INFO ]  testing: 300 / 500
2019-03-27 17:29:23,988 [MainThread  ] [INFO ]  testing: 400 / 500
2019-03-27 17:31:02,164 [MainThread  ] [INFO ]  Hot station result:
2019-03-27 17:31:02,165 [MainThread  ] [INFO ]  top 100: 53278.41
2019-03-27 17:31:02,165 [MainThread  ] [INFO ]  top 200: 28542.675
2019-03-27 17:31:02,165 [MainThread  ] [INFO ]  top 300: 19096.0566667
2019-03-27 17:31:02,165 [MainThread  ] [INFO ]  top 400: 14322.0425
2019-03-27 17:31:02,165 [MainThread  ] [INFO ]  top 500: 11457.634
2019-03-27 17:31:02,165 [MainThread  ] [INFO ]  Test cost time: 698.400026083
 10%|█         | 1000/10000 [14:34<2:11:09,  1.14it/s]
Traceback (most recent call last):
  File "base_avg_model_train_val.py", line 158, in <module>
    main()
  File "base_avg_model_train_val.py", line 150, in main
    episode_finished=episode_finished
  File "/home/liaobinbing/bus/tensorforce/tensorforce/execution/runner.py", line 115, in run
    self.agent.observe(terminal=terminal, reward=reward)
  File "/home/liaobinbing/bus/tensorforce/tensorforce/agents/agent.py", line 188, in observe
    index=index
  File "/home/liaobinbing/bus/tensorforce/tensorforce/models/model.py", line 1496, in observe
    episode = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1239, in run
    raise six.reraise(*original_exc_info)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1224, in run
    return self._sess.run(*args, **kwargs)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1296, in run
    run_metadata=run_metadata)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Must have updates.shape = indices.shape + params.shape[1:] or updates.shape = [], got updates.shape [1000,27,256], indices.shape [21], params.shape [50000,27,256]
         [[{{node ppo/observe-timestep/store/ScatterUpdate_1}} = ScatterUpdate[T=DT_FLOAT, Tindices=DT_INT32, _class=["loc:@ppo/o...2_1/Switch"], use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ppo/initialize/latest/initialize/state-neighbour_embedding, ppo/observe-timestep/store/mod, ppo/strided_slice_2, ^ppo/observe-timestep/store/AssignSub)]]

Caused by op u'ppo/observe-timestep/store/ScatterUpdate_1', defined at:
  File "base_avg_model_train_val.py", line 158, in <module>
    main()
  File "base_avg_model_train_val.py", line 49, in main
    network=CustomNetwork
  File "/home/liaobinbing/bus/tensorforce/tensorforce/agents/agent.py", line 286, in from_spec
    kwargs=kwargs
  File "/home/liaobinbing/bus/tensorforce/tensorforce/util.py", line 198, in get_object
    return obj(*args, **kwargs)
  File "/home/liaobinbing/bus/tensorforce/tensorforce/agents/ppo_agent.py", line 155, in __init__
    entropy_regularization=entropy_regularization
  File "/home/liaobinbing/bus/tensorforce/tensorforce/agents/learning_agent.py", line 141, in __init__
    batching_capacity=batching_capacity
  File "/home/liaobinbing/bus/tensorforce/tensorforce/agents/agent.py", line 76, in __init__
    self.model = self.initialize_model()
  File "/home/liaobinbing/bus/tensorforce/tensorforce/agents/ppo_agent.py", line 183, in initialize_model
    likelihood_ratio_clipping=self.likelihood_ratio_clipping
  File "/home/liaobinbing/bus/tensorforce/tensorforce/models/pg_prob_ratio_model.py", line 88, in __init__
    gae_lambda=gae_lambda
  File "/home/liaobinbing/bus/tensorforce/tensorforce/models/pg_model.py", line 98, in __init__
    requires_deterministic=False
  File "/home/liaobinbing/bus/tensorforce/tensorforce/models/distribution_model.py", line 90, in __init__
    discount=discount
  File "/home/liaobinbing/bus/tensorforce/tensorforce/models/memory_model.py", line 114, in __init__
    reward_preprocessing=reward_preprocessing
  File "/home/liaobinbing/bus/tensorforce/tensorforce/models/model.py", line 235, in __init__
    self.setup()
  File "/home/liaobinbing/bus/tensorforce/tensorforce/models/model.py", line 312, in setup
    index=episode_index
  File "/home/liaobinbing/bus/tensorforce/tensorforce/models/memory_model.py", line 613, in create_operations
    index=index
  File "/home/liaobinbing/bus/tensorforce/tensorforce/models/model.py", line 1260, in create_operations
    index=index
  File "/home/liaobinbing/bus/tensorforce/tensorforce/models/model.py", line 1188, in create_observe_operations
    reward=reward
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 368, in __call__
    return self._call_func(args, kwargs)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 311, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/liaobinbing/bus/tensorforce/tensorforce/models/memory_model.py", line 504, in tf_observe_timestep
    reward=reward
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 360, in __call__
    return self._call_func(args, kwargs)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 306, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/liaobinbing/bus/tensorforce/tensorforce/core/memories/queue.py", line 176, in tf_store
    updates=states[name]
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 296, in scatter_update
    use_locking=use_locking, name=name)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 1210, in scatter_update
    use_locking=use_locking, name=name)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/home/liaobinbing/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Must have updates.shape = indices.shape + params.shape[1:] or updates.shape = [], got updates.shape [1000,27,256], indices.shape [21], params.shape [50000,27,256]
         [[{{node ppo/observe-timestep/store/ScatterUpdate_1}} = ScatterUpdate[T=DT_FLOAT, Tindices=DT_INT32, _class=["loc:@ppo/o...2_1/Switch"], use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ppo/initialize/latest/initialize/state-neighbour_embedding, ppo/observe-timestep/store/mod, ppo/strided_slice_2, ^ppo/observe-timestep/store/AssignSub)]]
```

I dont know what's wrong with it? The json file for agent_config is
[ppo-avg-add-dense-train-val-base.txt](https://github.com/tensorforce/tensorforce/files/3016421/ppo-avg-add-dense-train-val-base.txt)

 Or maybe there is better way to test the validation set while training. Thanks a lot!

**Comment by AlexKuhnle** [comment]
Hi,
I'm not quite sure I follow: You don't actually call the agent in `episode_finished` to evaluate it under validation conditions, or is this somewhere hidden in the functions you call in there, and if so, could you post the code for them as well? One thing that may cause this error is if you don't adapt the environment-agent interaction for validation: training consists of sequences of `act()` - `observe()`, but evaluation should not call `observe()` and use `act(..., independent=True)` to tell the agent it shouldn't add the experience to memory etc.

**Comment by bbliao** [comment]
@AlexKuhnle Thanks for your quick reply.
The `episode_finished` function is a parameter in the `runner.run`:
```
runner = Runner(
        agent=agent,
        environment=environment,
        repeat_actions=1
    )
runner.run(
        timesteps=500000,
        episodes=10000,
        max_episode_timesteps=20,
        deterministic=False,
        episode_finished=episode_finished
    )
```
[which](https://github.com/tensorforce/tensorforce/blob/520a8d992230e382f08e315ede5fc477f5e26bfb/tensorforce/execution/runner.py#L137) will be called after every episodes.

**Comment by bbliao** [comment]
@AlexKuhnle Cool, 

>  training consists of sequences of act() - observe(), but evaluation should not call observe() and use act(..., independent=True) to tell the agent it shouldn't add the experience to memory etc

I use `act(..., independent=True) `, and it works. 
```
10%|▉         | 999/10000 [03:01<26:06,  5.75it/s]2019-04-01 14:19:01,358 [MainThread  ] [INFO ]  Finished episode 1000 after 20113 timesteps. Steps Per Second 110.981604587
 10%|█         | 1000/10000 [03:12<26:05,  5.75it/s]2019-04-01 14:22:14,029 [MainThread  ] [INFO ]  testing: 100 / 500
2019-04-01 14:24:47,657 [MainThread  ] [INFO ]  testing: 200 / 500
2019-04-01 14:27:00,825 [MainThread  ] [INFO ]  testing: 300 / 500
2019-04-01 14:29:10,283 [MainThread  ] [INFO ]  testing: 400 / 500
2019-04-01 14:31:15,513 [MainThread  ] [INFO ]  Hot station result:
2019-04-01 14:31:15,513 [MainThread  ] [INFO ]  top 100: 52360.67
2019-04-01 14:31:15,513 [MainThread  ] [INFO ]  top 200: 27990.835
2019-04-01 14:31:15,513 [MainThread  ] [INFO ]  top 300: 18695.15
2019-04-01 14:31:15,513 [MainThread  ] [INFO ]  top 400: 14021.3625
2019-04-01 14:31:15,514 [MainThread  ] [INFO ]  top 500: 11217.09
2019-04-01 14:31:15,514 [MainThread  ] [INFO ]  Test cost time: 734.156128883
 18%|█▊        | 1848/10000 [18:33<36:47,  3.69it/s]  
```
Thank you very much!

**Comment by AlexKuhnle** [comment]
> @AlexKuhnle Thanks for your quick reply.
> The `episode_finished` function is a parameter in the `runner.run`:
> 
> ```
> runner = Runner(
>         agent=agent,
>         environment=environment,
>         repeat_actions=1
>     )
> runner.run(
>         timesteps=500000,
>         episodes=10000,
>         max_episode_timesteps=20,
>         deterministic=False,
>         episode_finished=episode_finished
>     )
> ```
> [which](https://github.com/tensorforce/tensorforce/blob/520a8d992230e382f08e315ede5fc477f5e26bfb/tensorforce/execution/runner.py#L137) will be called after every episodes.

Yes, I only was confused where in the function you posted up there the actual evaluation agent-environment interaction happens.

Good to hear it works! And good point that should be improved/documented better. :-)

Closing this then.
