### ISSUE TITLE
PGProbRatioModel has no attribute 'act'

### ISSUE THREAD

**Issue by ZeroMaxinumXZ** [tensorforce/tensorforce#584]
Hi, so, I got this error, when  I tried to act on a PPO Agent, in the major revision.

Full error message:
```
Entering agent loop.
Traceback (most recent call last):
  File "start.py", line 102, in <module>
    main()
  File "start.py", line 77, in main
    main_loop(agent, curiousity_engine)
  File "start.py", line 35, in main_loop
    action1 = agent.act(states=prev_state)
  File "/home/ai/tensorforce-major-revision/tensorforce/agents/agent.py", line 198, in act
    actions, self.timestep = self.model.act(
AttributeError: 'PGProbRatioModel' object has no attribute 'act'
```

EDIT: DQN too...

**Comment by AlexKuhnle** [comment]
Ah, that sounds like you haven't initialized the agent, which is now necessary: `agent.initialize()`.

**Comment by ZeroMaxinumXZ** [comment]
Ah, thanks, closing this...
