### ISSUE TITLE
Argument of type 'method' is not iterable.

### ISSUE THREAD

**Issue by ZeroMaxinumXZ** [tensorforce/tensorforce#587]
Error Message I Received:
```
Traceback (most recent call last):
  File "mario.py", line 64, in <module>
    memory=memory
  File "/home/ai/tensorforce/tensorforce/agents/ppo_agent.py", line 85, in __init__
    buffer_observe=buffer_observe, seed=seed
  File "/home/ai/tensorforce/tensorforce/agents/agent.py", line 90, in __init__
    values_spec=states, value_type='state', return_normalized=True
  File "/home/ai/tensorforce/tensorforce/util.py", line 267, in valid_values_spec
    if is_atomic_values_spec(values_spec=values_spec):
  File "/home/ai/tensorforce/tensorforce/util.py", line 260, in is_atomic_values_spec
    return 'type' in values_spec or 'shape' in values_spec
TypeError: argument of type 'method' is not iterable
```

Code:
```
import os
import tensorforce
import logging


import gym_super_mario_bros
from gym_super_mario_bros.actions import SIMPLE_MOVEMENT as controls
from tensorforce.environments.openai_gym import OpenAIGym
from tensorforce.agents import PPOAgent as DQN
from tensorforce.execution import Runner

logger = logging.getLogger()
logger.setLevel(logging.INFO)

env = OpenAIGym("SuperMarioBros-v0", visualize=True, for_nes=True, nes_controls=controls) #Modified code to work with gym-super-mario-bros
network_spec = [
    dict(type='conv2d',
         size=32,
         window=8,
         stride=4
         ),
    dict(type = 'conv2d',
         size = 64,
         window=4,
         stride=2,
         ),
    dict(type = 'conv2d',
         size = 64,
         window=4,
         stride=2,
         ),
    dict(type = 'conv2d',
         size = 64,
         window=4,
         stride=2,
         ),
    dict(type='flatten'),
    dict(type='dense', size=512)
    ]

action_exp = dict(
    type='decaying',
    name="Mario",
    unit='timesteps',
    decay='natural_exponential',
    initial_value=1.0,
    decay_steps=1

    )

memory = dict(type='prioritized_replay',
              include_next_state=False,
              capacity=129

              )

     
agent = DQN(
    states=env.states,
    actions=env.actions,
    network=network_spec,
    parallel_interactions=10,
    exploration = action_exp,
    memory=memory
    )

agent.initialize()
save_location = os.getcwd()

runner = Runner(agent=agent,
                environment=env,
                repeat_actions=1
                )

def episode_finished(r):
    print("Finished episode {ep} after {ts} timesteps (reward: {reward})".format(ep=r.episode, ts=r.episode_timestep,
                                                                                 reward=r.episode_rewards[-1]))
    r.agent.save_model(save_location, False)
    return True


runner.run(num_episodes=1000,
           #num_timesteps=6000000,
           max_episode_timesteps = 6000,
           deterministic = False,
           episode_finished=episode_finished
           )
```

**Comment by AlexKuhnle** [comment]
I assume this is due to `env.states` and `env.actions` being functions now, so it should be `env.states()` and `env.actions()` for the agent constructor.

**Comment by ZeroMaxinumXZ** [comment]
Ahh, thank you.

**Comment by AlexKuhnle** [comment]
No problem.
