### ISSUE TITLE
InvalidArgumentError: indices[0] = [0, 1] does not index into shape [1,1]

### ISSUE THREAD

**Issue by ZeroMaxinumXZ** [tensorforce/tensorforce#590]
Error + Traceback:

```
Traceback (most recent call last):
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = [0, 1] does not index into shape [1,1]
	 [[{{node dqn.act/cond_4/ResourceScatterNdUpdate_1}} = ResourceScatterNdUpdate[T=DT_INT32, Tindices=DT_INT64, use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](dqn.act/cond_4/ResourceScatterNdUpdate_1/Switch, dqn.act/cond_4/ResourceScatterNdUpdate/indices/_285, dqn.act/cond_4/ResourceScatterNdUpdate_1/Switch_1/_287)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 84, in <module>
    main()
  File "start.py", line 80, in main
    main_loop(agent, curiousity_engine) 
  File "start.py", line 36, in main_loop
    action2 = agent.act(states=prev_state)
  File "/home/ai/tensorforce/tensorforce/agents/agent.py", line 200, in act
    independent=independent, **kwargs
  File "/home/ai/tensorforce/tensorforce/core/module.py", line 406, in fn
    fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = [0, 1] does not index into shape [1,1]
	 [[node dqn.act/cond_4/ResourceScatterNdUpdate_1 (defined at /home/ai/tensorforce/tensorforce/core/models/model.py:1021)  = ResourceScatterNdUpdate[T=DT_INT32, Tindices=DT_INT64, use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](dqn.act/cond_4/ResourceScatterNdUpdate_1/Switch, dqn.act/cond_4/ResourceScatterNdUpdate/indices/_285, dqn.act/cond_4/ResourceScatterNdUpdate_1/Switch_1/_287)]]

Caused by op 'dqn.act/cond_4/ResourceScatterNdUpdate_1', defined at:
  File "start.py", line 84, in <module>
    main()
  File "start.py", line 80, in main
    main_loop(agent, curiousity_engine)
  File "start.py", line 18, in main_loop
    agent.initialize()
  File "/home/ai/tensorforce/tensorforce/agents/agent.py", line 151, in initialize
    self.model.setup()  # should be self.model.initialize()
  File "/home/ai/tensorforce/tensorforce/core/models/model.py", line 349, in setup
    self.initialize()
  File "/home/ai/tensorforce/tensorforce/core/module.py", line 325, in initialize
    name='{}.{}'.format(self.name, function_name), api_function=api_function
  File "/home/ai/tensorforce/tensorforce/core/module.py", line 362, in create_api_function
    results = api_function()
  File "/home/ai/tensorforce/tensorforce/core/models/model.py", line 1036, in api_act
    pred=independent, true_fn=util.no_operation, false_fn=update_buffers
  File "/home/ai/tensorforce/tensorforce/core/module.py", line 417, in cond
    x = tf.cond(pred=pred, true_fn=true_fn, false_fn=false_fn, strict=True)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2097, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1930, in BuildCondBranch
    original_result = fn()
  File "/home/ai/tensorforce/tensorforce/core/models/model.py", line 1021, in update_buffers
    indices=[(parallel, buffer_index)], updates=actions[name]
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1181, in scatter_nd_update
    name=name))
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 499, in resource_scatter_nd_update
    use_locking=use_locking, name=name)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): indices[0] = [0, 1] does not index into shape [1,1]
	 [[node dqn.act/cond_4/ResourceScatterNdUpdate_1 (defined at /home/ai/tensorforce/tensorforce/core/models/model.py:1021)  = ResourceScatterNdUpdate[T=DT_INT32, Tindices=DT_INT64, use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](dqn.act/cond_4/ResourceScatterNdUpdate_1/Switch, dqn.act/cond_4/ResourceScatterNdUpdate/indices/_285, dqn.act/cond_4/ResourceScatterNdUpdate_1/Switch_1/_287)]]
```
Code used to get this:
```agent.act(states=get_screen())```

Get_screen function:
```
def get_screen(for_agent=False, output_layer=None):
    img = screen.grab()
    img = img.resize((screen_size()[0], screen_size()[1]))
    img = np.array(img)
    #Img = np.reshape(img, screen_size())

    #img = img.convert('L')
    #img = np.array(img)
    img = img / 255
    if for_agent:
        img = np.reshape(img, (screen_size()[0], screen_size()[1], 3))
    else:
        img = np.reshape(img, (1, screen_size()[0], screen_size()[1], 3))
    return img
```

screen_size() function:
```
def screen_size(): 
    return size()[0] // 4, size()[1] // 4, 3 #Size gets screen size from pyautogui
```

**Comment by AlexKuhnle** [comment]
Hi,
Can you post the states and actions specification, and what value you chose for buffer_observe? Seems to be related to that...
Alex
