### ISSUE TITLE
MultiDiscrete Action Space TF Exception

### ISSUE THREAD

**Issue by JNC96** [tensorforce/tensorforce#607]
Hi all,

I'm an undergraduate electrical engineer currently working on my final year project that revolves around Interactive Learning, and I've been using Tensorforce for the last few months (and I love it!). As part of my project, I've created a custom environment that involves a multi-discrete action space. When I try to create a PPO agent, however, an exception is raised. Here's the traceback:

```
Traceback (most recent call last):
  File "C:\<redacted>\runner_v2.py", line 135, in <module>
    summarizer=None, recorder=None
  File "c:\windows\system32\tensorforce\tensorforce\agents\agent.py", line 100, in create
    agent = tensorforce.agents.agents[agent](**kwargs)
  File "c:\windows\system32\tensorforce\tensorforce\agents\ppo.py", line 90, in __init__
    entropy_regularization=entropy_regularization
  File "c:\windows\system32\tensorforce\tensorforce\agents\policy_agent.py", line 269, in __init__
    recorder=recorder
  File "c:\windows\system32\tensorforce\tensorforce\agents\agent.py", line 125, in __init__
    values_spec=actions, value_type='action', return_normalized=True
  File "c:\windows\system32\tensorforce\tensorforce\util.py", line 325, in valid_values_spec
    return_normalized=return_normalized
  File "c:\windows\system32\tensorforce\tensorforce\util.py", line 312, in valid_values_spec
    value_spec=values_spec, value_type=value_type, return_normalized=return_normalized
  File "c:\windows\system32\tensorforce\tensorforce\util.py", line 435, in valid_value_spec
    name=(value_type + ' spec'), argument='num_values', value=num_values
tensorforce.exception.TensorforceError: Invalid type for action spec argument num_values: <class 'numpy.int64'>
```

I spent a while going through the source code, and from what I can understand there is a check condition in util that checks the data type of the value of 'num_values' and whether or not it is an integer. However, num_values is defined as np.int64. A function within openai_gym.py generates the action_spec dictionary:

```
specs = dict()
                for n in range(num_discrete_space):
                    specs['gymmdc{}'.format(n)] = dict(
                        type='int', shape=(), num_values=space.nvec[n]
                    )
```

Just to make sure, I tested it with a simple test case:

```
import numpy as np
import os

import tensorforce
import gym
import gym_drone
import argparse
import importlib
import json
import logging
import os
import time
import sys

from tensorforce.agents import Agent
from tensorforce.execution import Runner
from tensorforce.environments import Environment
from tensorforce import util

from gym.envs.registration import registry, register, make, spec
from gym import envs, wrappers, logger, spaces


# MD space with 3 actions: 1st action has 1 option, 2nd action has 2 ...
space = spaces.MultiDiscrete([1,2,3]) 

num_discrete_space = len(space.nvec)

specs = dict()
for n in range(num_discrete_space):
    specs['gymmdc{}'.format(n)] = dict(
        type='int', shape=(), num_values=space.nvec[n]
    )

print(specs)

first_action = specs['gymmdc0']

print(isinstance(first_action['num_values'], int))
```
This outputs:
```
{'gymmdc0': {'type': 'int', 'shape': (), 'num_values': 1}, 'gymmdc1': {'type': 'int', 'shape': (), 'num_values': 2}, 'gymmdc2': {'type': 'int', 'shape': (), 'num_values': 3}}

False
```

It fails the check because of this. How should I go about fixing this?

Thank you in advance!

**Comment by AlexKuhnle** [comment]
Hi! Glad you like the framework. :-)

Regarding the problem: This needs to be fixed, the best way is probably to replace [this problematic line](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/util.py#L431) with:

```python
if isinstance(num_values, (np.int32, np.int64)):
```

If it helps, feel free to open a PR with the fix. Thanks! :-)

**Comment by JNC96** [comment]
@AlexKuhnle will do, thank you !
