### ISSUE TITLE
TensorFlow Error: "Object was never used (type <class tensorflow.python.framework.ops.Operation>)"

### ISSUE THREAD

**Issue by Luca96** [tensorforce/tensorforce#642]
Hi @AlexKuhnle,
I'm new to Tensorforce and when I've tried some code I got the weird error above.

Code: 
```python
import gym
import tensorflow as tf
import tensorforce as tsf

from tensorforce.agents import Agent
from tensorforce.execution import Runner
from tensorforce.environments import Environment


if __name__ == '__main__':
    environment = Environment.create(environment='gym', level='CartPole-v1')
    agent = Agent.create(agent='ppo', environment=environment, max_episode_timesteps=500)
```

Full error message:
```
Traceback (most recent call last):                                                                                                         
  File "cartpole_agent.py", line 12, in <module>                                                                                           
    agent = Agent.create(agent='ppo', environment=environment, max_episode_timesteps=500)                                                  
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\agents\agent.py", line 124, in create           
    return Agent.create(agent=agent, environment=environment)                                                                              
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\agents\agent.py", line 60, in create            
    agent.initialize()                                                                                                                     
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\agents\agent.py", line 305, in initialize       
    self.model.initialize()                                                                                                                
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\models\model.py", line 248, in initialize  
    super().initialize()                                                                                                                   
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\module.py", line 469, in initialize        
    name='{}.{}'.format(self.name, function_name), api_function=api_function                                                               
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\module.py", line 519, in create_api_functio
n                                                                                                                                          
    results = api_function()                                                                                                               
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\models\model.py", line 770, in api_act     
    timestep=self.global_timestep, episode=self.global_episode, update=self.global_update                                                  
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\module.py", line 119, in update_tensors    
    Module.update_tensor(name=name, tensor=tensor)                                                                                         
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\module.py", line 104, in update_tensor     
    if not util.is_consistent_with_value_spec(value_spec=spec, x=tensor):                                                                  
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\util.py", line 718, in is_consistent_with_value_
spec                                                                                                                                       
    elif dtype(x=x) == value_spec['type']:                                                                                                 
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\util.py", line 204, in dtype                    
    raise TensorforceError.value(name='dtype', value=x.dtype)                                                                              
tensorforce.exception.TensorforceError: Invalid dtype value: <dtype: 'int64_ref'>.                                                         
ERROR:tensorflow:==================================                                                                                        
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):                                                          
<tf.Operation 'agent.act/assert_less/Assert/AssertGuard/Merge' type=Merge>                                                                 
If you want to mark it as used call its "mark_used()" method.                                                                              
It was originally created here:                                                                                                            
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\module.py", line 519, in create_api_functio
n                                                                                                                                          
    results = api_function()  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\models\model.py
", line 770, in api_act                                                                                                                    
    timestep=self.global_timestep, episode=self.global_episode, update=self.global_update  File "C:\Users\Luca\AppData\Local\Programs\Pytho
n\Python37\lib\site-packages\tensorflow_core\python\ops\check_ops.py", line 879, in assert_less                                            
    summarize, message, name)  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\chec
k_ops.py", line 371, in _binary_assert                                                                                                     
    return control_flow_ops.Assert(condition, data, summarize=summarize)  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\si
te-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped                                                            
    return _add_should_use_warning(fn(*args, **kwargs))                                                                                    
==================================                                                                                                         
ERROR:tensorflow:==================================                                                                                        
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):                                                          
<tf.Operation 'agent.act/assert_non_negative/assert_less_equal/Assert/AssertGuard/Merge' type=Merge>                                       
If you want to mark it as used call its "mark_used()" method.                                                                              
It was originally created here:                                                                                                            
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\models\model.py", line 770, in api_act     
    timestep=self.global_timestep, episode=self.global_episode, update=self.global_update  File "C:\Users\Luca\AppData\Local\Programs\Pytho
n\Python37\lib\site-packages\tensorflow_core\python\ops\check_ops.py", line 559, in assert_non_negative                                    
    return assert_less_equal(zero, x, data=data, summarize=summarize)  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-
packages\tensorflow_core\python\ops\check_ops.py", line 923, in assert_less_equal                                                          
    np.less_equal, x, y, data, summarize, message, name)  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tens
orflow_core\python\ops\check_ops.py", line 371, in _binary_assert                                                                          
    return control_flow_ops.Assert(condition, data, summarize=summarize)  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\si
te-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped                                                            
    return _add_should_use_warning(fn(*args, **kwargs))                                                                                    
==================================                                                                                                         
ERROR:tensorflow:==================================                                                                                        
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):                                                          
<tf.Operation 'agent.act/assert_equal_5/Assert/AssertGuard/Merge' type=Merge>                                                              
If you want to mark it as used call its "mark_used()" method.                                                                              
It was originally created here:                                                                                                            
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\module.py", line 519, in create_api_functio
n                                                                                                                                          
    results = api_function()  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\models\model.py
", line 770, in api_act                                                                                                                    
    timestep=self.global_timestep, episode=self.global_episode, update=self.global_update  File "C:\Users\Luca\AppData\Local\Programs\Pytho
n\Python37\lib\site-packages\tensorflow_core\python\ops\check_ops.py", line 658, in assert_equal                                           
    data, summarize, message, name)  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\op
s\check_ops.py", line 371, in _binary_assert                                                                                               
    return control_flow_ops.Assert(condition, data, summarize=summarize)  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\si
te-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped                                                            
    return _add_should_use_warning(fn(*args, **kwargs))                                                                                    
==================================                                                                                                         
ERROR:tensorflow:==================================                                                                                        
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):                                                          
<tf.Operation 'agent.act/assert_equal_3/Assert/Assert' type=Assert>                                                                        
If you want to mark it as used call its "mark_used()" method.                                                                              
It was originally created here:                                                                                                            
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\module.py", line 519, in create_api_functio
n                                                                                                                                          
    results = api_function()  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\models\model.py
", line 770, in api_act                                                                                                                    
    timestep=self.global_timestep, episode=self.global_episode, update=self.global_update  File "C:\Users\Luca\AppData\Local\Programs\Pytho
n\Python37\lib\site-packages\tensorflow_core\python\ops\check_ops.py", line 658, in assert_equal                                           
    data, summarize, message, name)  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\op
s\check_ops.py", line 371, in _binary_assert                                                                                               
    return control_flow_ops.Assert(condition, data, summarize=summarize)  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\si
te-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped                                                            
    return _add_should_use_warning(fn(*args, **kwargs))                                                                                    
==================================                                                                                                         
ERROR:tensorflow:==================================                                                                                        
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):                                                          
<tf.Operation 'agent.act/assert_equal_1/Assert/Assert' type=Assert>                                                                        
If you want to mark it as used call its "mark_used()" method.                                                                              
It was originally created here:                                                                                                            
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\module.py", line 519, in create_api_functio
n                                                                                                                                          
    results = api_function()  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorforce\core\models\model.py
", line 770, in api_act                                                                                                                    
    timestep=self.global_timestep, episode=self.global_episode, update=self.global_update  File "C:\Users\Luca\AppData\Local\Programs\Pytho
n\Python37\lib\site-packages\tensorflow_core\python\ops\check_ops.py", line 658, in assert_equal                                           
    data, summarize, message, name)  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\op
s\check_ops.py", line 371, in _binary_assert                                                                                               
    return control_flow_ops.Assert(condition, data, summarize=summarize)  File "C:\Users\Luca\AppData\Local\Programs\Python\Python37\lib\si
te-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped                                                            
    return _add_should_use_warning(fn(*args, **kwargs))                                                                                    
==================================                                                                                                         
```

I'm on a Windows 10 platform, running TensorFlow-cpu 1.15.0, OpenAI Gym 0.15.4 and Tensorforce 0.5.3 on Python 3.7.4.

As you may notice, the error triggers as `Agent.create(...)` get's called. Moreover, the tf error repeats for the following `tf.Operation`:
```
<tf.Operation 'agent.act/assert_less/Assert/AssertGuard/Merge' type=Merge>
<tf.Operation 'agent.act/assert_non_negative/assert_less_equal/Assert/AssertGuard/Merge' type=Merge>
<tf.Operation 'agent.act/assert_equal_5/Assert/AssertGuard/Merge' type=Merge>
<tf.Operation 'agent.act/assert_equal_3/Assert/Assert' type=Assert>
<tf.Operation 'agent.act/assert_equal_1/Assert/Assert' type=Assert>
```

The error still persists by changing the agent (e.g. `agent='tensorforce') and environment. I ran the same code on **Google Collaboratory**, which works fine.

Hope you can help me. Thank you in advance.

**Comment by AlexKuhnle** [comment]
The likely cause for this is that you use TF 1.15, whereas Google Collab presumably uses 2.0. These two versions are not compatible, and Tensorforce uses TF 2.0 by now, so I hope upgrading TF will resolve the issue.

**Comment by Luca96** [comment]
I've upgraded TF to 2.0, now it works fine.

Thanks for your help @AlexKuhnle and for making such a great library.
