### ISSUE TITLE
Quickstart.py errors with Invalid value for util.dtype argument x: <dtype: 'int64_ref'>.

### ISSUE THREAD

**Issue by sccrthlt** [tensorforce/tensorforce#645]
I am looking to run the `examples/quickstart.py` unfortunately I am receiving the following error:
```
tensorforce.exception.TensorforceError: Invalid value for util.dtype argument x: <dtype: 'int64_ref'>.
```
# OS
```
Ubuntu 18.04.3 LTS
NVIDIA-SMI 418.87.01    
Driver Version: 418.87.01    
CUDA Version: 10.1  
```
# Environment
```
name: test
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1d=h7b6447c_3
  - pip=20.0.2=py37_0
  - python=3.7.6=h0371630_2
  - readline=7.0=h7b6447c_5
  - setuptools=45.1.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.9.0
    - argcomplete==1.11.1
    - astor==0.8.1
    - attrs==19.1.0
    - cloudpickle==1.2.2
    - cmake==3.15.3
    - colorlog==4.1.0
    - contextlib2==0.6.0.post1
    - cvxopt==1.2.3
    - cycler==0.10.0
    - decorator==4.4.1
    - dm-sonnet==1.32
    - future==0.18.2
    - gast==0.2.2
    - google-pasta==0.1.8
    - grpcio==1.26.0
    - gym==0.15.4
    - h5py==2.10.0
    - importlib-metadata==1.4.0
    - ipython==5.8.0
    - ipython-genutils==0.2.0
    - jax==0.1.58
    - jaxlib==0.1.37
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - matplotlib==3.1.1
    - mock==3.0.5
    - more-itertools==8.1.0
    - msgpack==0.6.2
    - msgpack-numpy==0.4.4.3
    - nashpy==0.0.19
    - networkx==2.2
    - nox==2019.11.9
    - numpy==1.18.1
    - opencv-python==4.1.2.30
    - opt-einsum==3.1.0
    - packaging==20.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pluggy==0.13.1
    - prompt-toolkit==1.0.18
    - protobuf==3.11.2
    - ptyprocess==0.6.0
    - py==1.8.1
    - pyglet==1.3.2
    - pygments==2.5.2
    - pyparsing==2.4.6
    - pyspiel==0.0.1rc2
    - pytest==5.3.4
    - python-dateutil==2.8.1
    - scipy==1.4.1
    - semantic-version==2.8.4
    - simplegeneric==0.8.1
    - six==1.14.0
    - tensorboard==1.15.0
    - tensorflow==1.15.2
    - tensorflow-estimator==1.15.1
    - tensorflow-probability==0.7.0
    - tensorforce==0.5.3
    - termcolor==1.1.0
    - tqdm==4.42.0
    - traitlets==4.3.3
    - virtualenv==16.7.9
    - wcwidth==0.1.8
    - werkzeug==0.16.1
    - wrapt==1.11.2
    - zipp==2.1.0
```

# Traceback
```
Traceback (most recent call last):
  File "quickstart.py", line 54, in <module>
    main()
  File "quickstart.py", line 42, in main
    summarizer=None, recorder=None
  File "/home/username/code/tensorforce/tensorforce/agents/agent.py", line 112, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/home/username/code/tensorforce/tensorforce/agents/agent.py", line 86, in create
    return Agent.create(agent=agent, environment=environment)
  File "/home/username/code/tensorforce/tensorforce/agents/agent.py", line 63, in create
    agent.initialize()
  File "/home/username/code/tensorforce/tensorforce/agents/agent.py", line 315, in initialize
    self.model.initialize()
  File "/home/username/code/tensorforce/tensorforce/core/models/model.py", line 281, in initialize
    super().initialize()
  File "/home/username/code/tensorforce/tensorforce/core/module.py", line 489, in initialize
    name='{}.{}'.format(self.name, function_name), api_function=api_function
  File "/home/username/code/tensorforce/tensorforce/core/module.py", line 539, in create_api_function
    results = api_function()
  File "/home/username/code/tensorforce/tensorforce/core/models/model.py", line 889, in api_act
    timestep=self.global_timestep, episode=self.global_episode, update=self.global_update
  File "/home/username/code/tensorforce/tensorforce/core/module.py", line 127, in update_tensors
    Module.update_tensor(name=name, tensor=tensor)
  File "/home/username/code/tensorforce/tensorforce/core/module.py", line 110, in update_tensor
    if not util.is_consistent_with_value_spec(value_spec=spec, x=tensor):
  File "/home/username/code/tensorforce/tensorforce/util.py", line 723, in is_consistent_with_value_spec
    elif dtype(x=x) == value_spec['type']:
  File "/home/username/code/tensorforce/tensorforce/util.py", line 220, in dtype
    raise TensorforceError.value(name='util.dtype', argument='x', value=x.dtype)
tensorforce.exception.TensorforceError: Invalid value for util.dtype argument x: <dtype: 'int64_ref'>.
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'agent.act/assert_less/Assert/AssertGuard/Merge' type=Merge>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/username/code/tensorforce/tensorforce/core/module.py", line 539, in create_api_function
    results = api_function()  File "/home/username/code/tensorforce/tensorforce/core/models/model.py", line 889, in api_act
    timestep=self.global_timestep, episode=self.global_episode, update=self.global_update  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/ops/check_ops.py", line 879, in assert_less
    summarize, message, name)  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/ops/check_ops.py", line 371, in _binary_assert
    return control_flow_ops.Assert(condition, data, summarize=summarize)  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/util/tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'agent.act/assert_non_negative/assert_less_equal/Assert/AssertGuard/Merge' type=Merge>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/username/code/tensorforce/tensorforce/core/models/model.py", line 889, in api_act
    timestep=self.global_timestep, episode=self.global_episode, update=self.global_update  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/ops/check_ops.py", line 559, in assert_non_negative
    return assert_less_equal(zero, x, data=data, summarize=summarize)  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/ops/check_ops.py", line 923, in assert_less_equal
    np.less_equal, x, y, data, summarize, message, name)  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/ops/check_ops.py", line 371, in _binary_assert
    return control_flow_ops.Assert(condition, data, summarize=summarize)  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/util/tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'agent.act/assert_equal_5/Assert/AssertGuard/Merge' type=Merge>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/username/code/tensorforce/tensorforce/core/module.py", line 539, in create_api_function
    results = api_function()  File "/home/username/code/tensorforce/tensorforce/core/models/model.py", line 889, in api_act
    timestep=self.global_timestep, episode=self.global_episode, update=self.global_update  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/ops/check_ops.py", line 658, in assert_equal
    data, summarize, message, name)  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/ops/check_ops.py", line 371, in _binary_assert
    return control_flow_ops.Assert(condition, data, summarize=summarize)  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/util/tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'agent.act/assert_equal_3/Assert/AssertGuard/Merge' type=Merge>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/username/code/tensorforce/tensorforce/core/module.py", line 539, in create_api_function
    results = api_function()  File "/home/username/code/tensorforce/tensorforce/core/models/model.py", line 889, in api_act
    timestep=self.global_timestep, episode=self.global_episode, update=self.global_update  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/ops/check_ops.py", line 658, in assert_equal
    data, summarize, message, name)  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/ops/check_ops.py", line 371, in _binary_assert
    return control_flow_ops.Assert(condition, data, summarize=summarize)  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/util/tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'agent.act/assert_equal_1/Assert/AssertGuard/Merge' type=Merge>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/username/code/tensorforce/tensorforce/core/module.py", line 539, in create_api_function
    results = api_function()  File "/home/username/code/tensorforce/tensorforce/core/models/model.py", line 889, in api_act
    timestep=self.global_timestep, episode=self.global_episode, update=self.global_update  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/ops/check_ops.py", line 658, in assert_equal
    data, summarize, message, name)  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/ops/check_ops.py", line 371, in _binary_assert
    return control_flow_ops.Assert(condition, data, summarize=summarize)  File "/opt/conda/envs/open_spiel/lib/python3.7/site-packages/tensorflow_core/python/util/tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================

```

**Comment by AlexKuhnle** [comment]
It looks like you're on the wrong TensorFlow version, Tensorforce needs version TF 2, or more precisely, 2.0.1. To upgrade: `pip install --upgrade tensorflow==2.0.1`.

**Comment by AlexKuhnle** [comment]
Re-open if this doesn't help.
