### ISSUE TITLE
quickstart.py fails with gym 0.15.6

### ISSUE THREAD

**Issue by oandrieu** [tensorforce/tensorforce#649]
```
$ python3 quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 68, in <module>
    main()
  File "quickstart.py", line 33, in main
    environment = Environment.create(environment='gym', level='CartPole-v1')
  File "/home/oandrieu/env/tensorforce/lib64/python3.7/site-packages/tensorforce/environments/environment.py", line 89, in create
    environment = tensorforce.environments.environments[environment](**kwargs)
  File "/home/oandrieu/env/tensorforce/lib64/python3.7/site-packages/tensorforce/environments/openai_gym.py", line 160, in __init__
    reward_threshold=reward_threshold, tags=tags, **kwargs
  File "/home/oandrieu/env/tensorforce/lib64/python3.7/site-packages/tensorforce/environments/openai_gym.py", line 106, in create_level
    tags = dict(gym.envs.registry.env_specs[level].tags)
AttributeError: 'EnvSpec' object has no attribute 'tags'
```

I had to downgrade gym to 0.15.4.

**Comment by AlexKuhnle** [comment]
You're right, they have removed the `tags` argument in a very recent version. My unittests were complaining for the same reason yesterday. The latest commit should fix this.
