### ISSUE TITLE
Error about parallels

### ISSUE THREAD

**Issue by fanbbbb** [tensorforce/tensorforce#659]
Hello~
  I'm using Tensorforce in a new environment without GYM style. The game environment is individual, and I deploy a tensorforce agent in a flask server, which receives obs as flask request from the individual game env. I set the `parallel_interactions=5`, I run the game in 5 computers as 5 env threads. 5 envs send their obs to the server simultaneously, and the agent do `agent.observe()` and `agent.act()` with the parameter `parallel=env_id`. But I got some error in a few episodes.
 
Here is my code about tensorforce agent in a flask server:
```
agent = Agent.create(
  agent='ppo',
  states=dict(type='float', shape=(args.num_state,)),
  actions=dict(type='int', num_values=args.num_action),
  max_episode_timesteps=5000,
  memory=280000,
  network = [
    {
      "type": "dense",
      "size": 64,
      "activation": "relu"
    },
    {
      "type": "dense",
      "size": 64,
      "activation": "relu"
    }
  ],
  batch_size=10, update_frequency=10, learning_rate=1e-3,
  subsampling_fraction=0.33, optimization_steps=10,
  likelihood_ratio_clipping=0.2, discount=0.99, estimate_terminal=False,
  critic_network = [
      {
        "type": "dense",
        "size": 64,
        "activation": "relu"
      },
      {
        "type": "dense",
        "size": 64,
        "activation": "relu"
      }
    ],
  critic_optimizer=dict(optimizer='adam', multi_step=10, learning_rate=1e-3),
  preprocessing=None,
  exploration=0.1, variable_noise=0.0,
  l2_regularization=0.01, entropy_regularization=0.0,
  name="CUSTOMENV", device=None,
  parallel_interactions=args.num_parallels,
  seed=None,
  execution=None,
  saver=dict(
    directory="./models",
    filename="0312.ckpt",
    frequency=1800,

  ),
  summarizer=dict(
    directory="./summaries",
    labels=['graph', 'entropy', 'losses', 'rewards'],
    frequency=100
  ),
  recorder=dict(
    directory="./records",
    frequency=10
  )
)
```
And here is the error:
```
Traceback (most recent call last):
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [] [Condition x == y did not hold element-wise:] [x (CUSTOMENV.observe/strided_slice_2:0) = ] [2756] [y (CUSTOMENV.observe/Identity:0) = ] [2757]
	 [[{{node Assert}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\miniconda\envs\customenv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\miniconda\envs\customenv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\miniconda\envs\customenv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\miniconda\envs\customenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\miniconda\envs\customenv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\miniconda\envs\customenv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "battle_app_0316.py", line 172, in get_state
    loggers[id].info(f"OBS IS {obs}")
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorforce\agents\agent.py", line 534, in observe
    terminal=terminal, reward=reward, parallel=[parallel], **kwargs
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorforce\core\module.py", line 578, in fn
    fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "D:\miniconda\envs\customenv\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [] [Condition x == y did not hold element-wise:] [x (CUSTOMENV.observe/strided_slice_2:0) = ] [2756] [y (CUSTOMENV.observe/Identity:0) = ] [2757]
	 [[{{node Assert}}]]

[2020-03-17 18:56:07,951] ERROR in app: Exception on /state [GET]
Traceback (most recent call last):
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [] [Condition x == y did not hold element-wise:] [x (CUSTOMENV.observe/strided_slice_2:0) = ] [2756] [y (CUSTOMENV.observe/Identity:0) = ] [2757]
	 [[{{node Assert}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\miniconda\envs\customenv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\miniconda\envs\customenv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\miniconda\envs\customenv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\miniconda\envs\customenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\miniconda\envs\customenv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\miniconda\envs\customenv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "battle_app_0316.py", line 172, in get_state
    loggers[id].info(f"OBS IS {obs}")
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorforce\agents\agent.py", line 534, in observe
    terminal=terminal, reward=reward, parallel=[parallel], **kwargs
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorforce\core\module.py", line 578, in fn
    fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "D:\miniconda\envs\customenv\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "D:\miniconda\envs\customenv\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [] [Condition x == y did not hold element-wise:] [x (CUSTOMENV.observe/strided_slice_2:0) = ] [2756] [y (CUSTOMENV.observe/Identity:0) = ] [2757]
	 [[{{node Assert}}]]
```
The error means the obs dim isn't correct. But I check the data from env, they are okay.
The error wasn't always happen. Before the error happened, some episodes could be trained well, and I can see the loss decrease obviously from Tensorboard. That means some episodes have been trained great.

I'm wondering whether some situations may result in this error.
**Situation1**. I have five computers run five envs, and mybe two envs break out when they were running, and the two broken envs haven't got the terminal status. their episodes were not complete. I did some tests, I set` parallels_interaction=5`, but from the beginning, I only run one env for about 3 hours, no error happened, so I think something about parallels result in this error.
**Situation2**. Whether multiple threads in flask results in the error, because the agent is a global variable.

Any advice will be grateful, Thanks a lot.

**Comment by AlexKuhnle** [comment]
Will add some information later, but quick question: Which version of Tensorforce are you using? If it's an older version, or even if it's the most recent pip version, could you try whether changing to the GitHub master version helps?

**Comment by AlexKuhnle** [comment]
When you say that "the obs dim" isn't correct, does that mean that your observations are of size 2756/7? I'm not sure about where this number comes from, given your configuration. I assume that the environments terminate after `max_episode_timesteps=5000` timesteps? That could otherwise cause problems. Another problem could be memory-related, but I wait for you to confirm whether you're on the latest version, since this should have recently improved (although the changes may also have introduced a new bug :-/ ).

In general your setup using Flask sounds fine. Is there a reason for communicating via Flask, though? If you're not aware of the recent parallel execution changes, you may be interested in checking them out. There are two modes, one based on `multiprocessing`, another one on `socket` communication. In particular, they can be run via the normal `Runner` interface, no need for a custom setup. Another thing, since you're saying they "send their obs to the server simultaneously" -- if this is the case, and you're not already doing it, you can process all 5 queries in one batched call via `agent.act/observe(..., parallel=[0, 1, 2, 3, 4])`. Just to inform you about some recent features... :-)

**Comment by fanbbbb** [comment]
> When you say that "the obs dim" isn't correct, does that mean that your observations are of size 2756/7? I'm not sure about where this number comes from, given your configuration. I assume that the environments terminate after `max_episode_timesteps=5000` timesteps? That could otherwise cause problems. Another problem could be memory-related, but I wait for you to confirm whether you're on the latest version, since this should have recently improved (although the changes may also have introduced a new bug :-/ ).
> 
> In general your setup using Flask sounds fine. Is there a reason for communicating via Flask, though? If you're not aware of the recent parallel execution changes, you may be interested in checking them out. There are two modes, one based on `multiprocessing`, another one on `socket` communication. In particular, they can be run via the normal `Runner` interface, no need for a custom setup. Another thing, since you're saying they "send their obs to the server simultaneously" -- if this is the case, and you're not already doing it, you can process all 5 queries in one batched call via `agent.act/observe(..., parallel=[0, 1, 2, 3, 4])`. Just to inform you about some recent features... :-)

 @AlexKuhnle I checked my pip list, I used version 0.5.3 from pip, I'm running the env with the latest version from master, some result I will inform you at the first time.
I guess that in "2756/7", 2756 means there's 2756 timesteps in an episode and 7 means the action_nums in action space (I use 7 discrete actions in action space).  So I think maybe in one timestep, something terrible happened.
For the idea about `max_episode_timesteps=5000`, I have checked the log, there's no episode reached 5000 timesteps, the env always terminated at about 2000~3000 timesteps. And I think memory size is enough.
I used Flask due to the custom environment is just a game made by my friend times ago, and the game haven't realized as a GYM style, that means I can't do `reset()`. I deployed tensorforce agent in Flask as an observation collector,  the agent collects obs data from envs, and return predicted actions, when "game over", env send a terminal signal to the agent, and the agent will use that in `agent.act(terminal=terminal)` and `observe(terminal=terminal)`, this signal helps training. In this way, I can't use Runner because I can't implement a tensorforce-style custom environment interface.  
The 5 env are deployed in different computers, considering communication time delay and different env terminates at different time, so maybe they can't "keep simultaneous", I think `parallel=[0, 1, 2, 3, 4]` may helps little.

**Comment by fanbbbb** [comment]
@AlexKuhnle I tested the Situation1 mentioned above. Firstly I run 5 envs, and terminated 2 of them when they were running, the 2 instances haven't reached terminal status when they were shut down. That means there are two broken episodes which have no terminal=True in memory. But no error occurs.

The test is based on the latest version from master.

**Comment by AlexKuhnle** [comment]
It is definitely possible that the error you encountered was fixed recently, as there was quite some development around the parallelization feature recently. I hope it works for you now, otherwise let me know.

Flask is a bit like socket-based communication, so it most likely follows a similar pattern than Tensorforce's socket environment. As long as your environment can implement `execute: action -> next-state, reward`, it should be possible to implement an `Environment` interface for it. But no worries, as long as you're happy with your setup right now, no need to change something. However, if you continue working on it, maybe worth looking into at some point.

Minor comment: Your memory size is indeed big enough, in fact it's far "too big". This doesn't hurt, but uses more memory than necessary. It should be possible to drop the explicit `memory` argument entirely, since PPO as on-policy doesn't really make use of a larger-than-necessary memory, and by default a suitable minimal memory size is chosen.

**Comment by fanbbbb** [comment]
@AlexKuhnle Thanks a lot. I run new code with the latest version for thousands of episodes, it works well. I will run that for more episodes. I will contact you latter when something new happens. 

Next step, I'll check the Environment interface and resize the memory. Thanks again~

**Comment by fanbbbb** [comment]
After updating the version, it works well now. Thanks.
