### ISSUE TITLE
cannot run example: AttributeError: module 'tensorflow._api.v1.keras.optimizers' has no attribute 'Ftrl'

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#672]
It seems like I have a problem running tensorforce on Ubuntu 18.04.

Procedure:

```> pip3 uninstall tensorforce
Uninstalling Tensorforce-0.5.2:
  /home/jrlab/.local/lib/python3.6/site-packages/Tensorforce-0.5.2.dist-info/INSTALLER
  /home/jrlab/.local/lib/python3.6/site-packages/Tensorforce-0.5.2.dist-info/LICENSE
  /home/jrlab/.local/lib/python3.6/site-packages/Tensorforce-0.5.2.dist-info/METADATA
  /home/jrlab/.local/lib/python3.6/site-packages/Tensorforce-0.5.2.dist-info/RECORD
  /home/jrlab/.local/lib/python3.6/site-packages/Tensorforce-0.5.2.dist-info/WHEEL
  /home/jrlab/.local/lib/python3.6/site-packages/Tensorforce-0.5.2.dist-info/top_level.txt
Proceed (y/n)? y
  Successfully uninstalled Tensorforce-0.5.2
> pwd
/home/jrlab/Desktop/Git/tensorforce
> git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
> pip3 install -e .
[lots out output]
Successfully installed Tensorforce attrs-19.3.0 cloudpickle-1.3.0 cycler-0.10.0 future-0.18.2 gym-0.17.1 h5py-2.10.0 importlib-metadata-1.6.0 kiwisolver-1.2.0 matplotlib-3.2.1 more-itertools-8.2.0 msgpack-1.0.0 msgpack-numpy-0.4.5 numpy-1.18.3 packaging-20.3 pluggy-0.13.1 py-1.8.1 pyglet-1.5.0 pyparsing-2.4.7 pytest-5.4.1 python-dateutil-2.8.1 scipy-1.4.1 six-1.14.0 tqdm-4.45.0 wcwidth-0.1.9 zipp-3.1.0
> python3 run.py benchmarks/configs/ppo1.json gym --level CartPole-v1 -e 300
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "run.py", line 24, in <module>
    from tensorforce import Agent, Environment, Runner
  File "/home/jrlab/Desktop/Git/tensorforce/tensorforce/__init__.py", line 31, in <module>
    from tensorforce.environments import Environment
  File "/home/jrlab/Desktop/Git/tensorforce/tensorforce/environments/__init__.py", line 29, in <module>
    from tensorforce.environments.carla_environment import CARLAEnvironment
  File "/home/jrlab/Desktop/Git/tensorforce/tensorforce/environments/carla_environment.py", line 7, in <module>
    from tensorforce.agents import Agent
  File "/home/jrlab/Desktop/Git/tensorforce/tensorforce/agents/__init__.py", line 18, in <module>
    from tensorforce.agents.constant import ConstantAgent
  File "/home/jrlab/Desktop/Git/tensorforce/tensorforce/agents/constant.py", line 19, in <module>
    from tensorforce.core.models import ConstantModel
  File "/home/jrlab/Desktop/Git/tensorforce/tensorforce/core/__init__.py", line 23, in <module>
    from tensorforce.core.optimizers import optimizer_modules
  File "/home/jrlab/Desktop/Git/tensorforce/tensorforce/core/optimizers/__init__.py", line 32, in <module>
    from tensorforce.core.optimizers.tf_optimizer import TFOptimizer, tensorflow_optimizers
  File "/home/jrlab/Desktop/Git/tensorforce/tensorforce/core/optimizers/tf_optimizer.py", line 30, in <module>
    ftrl=tf.keras.optimizers.Ftrl,
AttributeError: module 'tensorflow._api.v1.keras.optimizers' has no attribute 'Ftrl'
```

**Comment by AlexKuhnle** [comment]
Hi, this looks like a TF version problem. Could you check whether you're on `2.0.1` (or higher can maybe also work).

**Comment by jerabaul29** [comment]
Mmmh, you are right, only at a tensorflow 1.XX. That was surprising, I thought that tensorflow would be installed in the right version with the command, sorry for that :) .

But I still have a problem when I explicitly ask for installing with the right tf version:

```
$ pip3 install tensorforce[tf]
Collecting tensorforce[tf]
  Using cached https://files.pythonhosted.org/packages/e4/bb/9a328bc31b987e28c3f263c87b649613ee0ea7c248232efee4deb188ebbe/Tensorforce-0.5.4-py3-none-any.whl
Collecting tqdm (from tensorforce[tf])
  Using cached https://files.pythonhosted.org/packages/4a/1c/6359be64e8301b84160f6f6f7936bbfaaa5e9a4eab6cbc681db07600b949/tqdm-4.45.0-py2.py3-none-any.whl
Collecting msgpack-numpy (from tensorforce[tf])
  Using cached https://files.pythonhosted.org/packages/4b/32/323eda6da56cdbf768e41858d491c163a6989f27b1733eb3e9fca21291aa/msgpack_numpy-0.4.5-py2.py3-none-any.whl
Collecting pytest (from tensorforce[tf])
  Using cached https://files.pythonhosted.org/packages/c7/e2/c19c667f42f72716a7d03e8dd4d6f63f47d39feadd44cc1ee7ca3089862c/pytest-5.4.1-py3-none-any.whl
Collecting gym (from tensorforce[tf])
Collecting numpy (from tensorforce[tf])
  Using cached https://files.pythonhosted.org/packages/3d/fc/4763e5f17ac6e7e7d55f377cde859ca1c5d5ac624441ab45315bc578aa9e/numpy-1.18.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting msgpack (from tensorforce[tf])
  Using cached https://files.pythonhosted.org/packages/c9/35/33aa1af0700d21beabdf74373f31c52c048be8ee082f98edbc37ba3ae956/msgpack-1.0.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting matplotlib (from tensorforce[tf])
  Using cached https://files.pythonhosted.org/packages/93/4b/52da6b1523d5139d04e02d9e26ceda6146b48f2a4e5d2abfdf1c7bac8c40/matplotlib-3.2.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting h5py (from tensorforce[tf])
  Using cached https://files.pythonhosted.org/packages/60/06/cafdd44889200e5438b897388f3075b52a8ef01f28a17366d91de0fa2d05/h5py-2.10.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting tensorflow==2.0.1; extra == "tf" (from tensorforce[tf])
  Could not find a version that satisfies the requirement tensorflow==2.0.1; extra == "tf" (from tensorforce[tf]) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow==2.0.1; extra == "tf" (from tensorforce[tf])
```

**Comment by jerabaul29** [comment]
(or should I first un-install tf, then try the command again maybe ^^ ).

**Comment by jerabaul29** [comment]
(note: there is a problem also when I first un install tf [which is actually the reason why I was trying to install from source]). But I guess this may be specific to my machine, sorry for the disturbance.

**Comment by jerabaul29** [comment]
Sorry I just thing my installs were very broken because of some successive updates. Closing now.

**Comment by AlexKuhnle** [comment]
The reason why TensorFlow is not automatically installed is because you have to choose between `tf` and `tf_gpu`, and a default would probably be confusing. If you install via `pip install -e .[tf / tf_gpu]`, it should be installed.

**Comment by jerabaul29** [comment]
Ok, I fixed my broken installation (sorry for the noise), but still have some problems:

```
$ pip3 install tensorforce[cpu]
...
$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> tensorflow.__version__
'2.1.0'
>>> import tensorforce
>>> tensorforce.__version__
'0.5.4'
>>> exit()
$ ls
benchmarks       data  examples  PROJECTS.md  requirements.txt  run.py    tensorforce           Tensorforce.egg-info  tune.py
CONTRIBUTING.md  docs  LICENSE   README.md    ROADMAP.md        setup.py  tensorforce.egg-info  test                  UPDATE_NOTES.md
$ python3 run.py benchmarks/configs/ppo1.json gym --level CartPole-v1 -e 300
usage: run.py [-h] [-a AGENT] [-n NETWORK] [-e ENVIRONMENT] [-l LEVEL]
              [-m MAX_EPISODE_TIMESTEPS] [--visualize]
              [--visualize-directory VISUALIZE_DIRECTORY]
              [--import-modules IMPORT_MODULES] [--num-parallel NUM_PARALLEL]
              [--batch-agent-calls] [--sync-timesteps] [--sync-episodes]
              [--remote {multiprocessing,socket-client,socket-server}]
              [--blocking] [--host HOST] [--port PORT] [-v] [-p EPISODES]
              [-t TIMESTEPS] [-u UPDATES] [--mean-horizon MEAN_HORIZON]
              [--save-best-agent SAVE_BEST_AGENT] [-r REPEAT] [--path PATH]
              [--seaborn]
run.py: error: unrecognized arguments: benchmarks/configs/ppo1.json gym
```

**Comment by AlexKuhnle** [comment]
Yes, the interface of `run.py` changed slightly recently. All arguments are not "explicit", so `-a benchmarks/configs/ppo1.json` and `-e gym`.

**Comment by jerabaul29** [comment]
Ok :) This is taken directly from the Readme, so may be good to update it :)

**Comment by AlexKuhnle** [comment]
Reason is that it makes its usage more flexible, particularly when using the parallelized/remote args.

**Comment by AlexKuhnle** [comment]
Oh, that's bad, thanks for letting me know, that should ofc be updated. :-)

**Comment by jerabaul29** [comment]
(and there was already a -e option, guess it has changed name is -e is now used for something else? :) )

**Comment by AlexKuhnle** [comment]
Yes, it's `-p` now, or just `--episodes`. Not ideal... :-)

**Comment by jerabaul29** [comment]
No worries. Yes, just found it from the help, sorry for the verbosity :) . I think it is good name choices, no worries, will be perfect when the readme is updated :) .

**Comment by jerabaul29** [comment]
Working fine now on my machine, feel free to close when the readme is updated :) .

**Comment by AlexKuhnle** [comment]
Updated, thanks. :+1:
