### ISSUE TITLE
Unexpected error when using DPG agent

### ISSUE THREAD

**Issue by CristianMonea** [tensorforce/tensorforce#679]
Hello! I get an unexpected error when using the DPG agent. This is my code:

```
from tensorforce.agents import Agent
from tensorforce.environments import Environment
from tensorforce.execution import Runner

environment = Environment.create(environment='gym', level='MountainCarContinuous-v0')
agent = Agent.create(agent='dpg', environment=environment, max_episode_timesteps = 1000, batch_size=5, memory=10000)

# Train
for ep in range(2): # Number of episodes
    
    print('********Episode ' + str(ep) + '********')
    
    # Initialize episode
    states = environment.reset()
    done = False
    step = 0
    
    while not done: # Episode timestep
        actions = agent.act(states=states)
        states, done, reward = environment.execute(actions=actions)
        agent.observe(terminal=done, reward=reward)

environment.close()
agent.close()

```
And this is the error:

```
Traceback (most recent call last):

  File "c:\users\user\untitled0.py", line 6, in <module>
    agent = Agent.create(agent='dpg', environment=environment, max_episode_timesteps = 1000, batch_size=5, memory=10000)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\agents\agent.py", line 116, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\agents\agent.py", line 87, in create
    agent = agent(**kwargs)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\agents\dpg.py", line 280, in __init__
    raise TensorforceError.unexpected()

TensorforceError: Unexpected error!
```

What is causing this and how can it be resolved?

**Comment by AlexKuhnle** [comment]
DPG requires only a single continuous action. I had recently added an exception to check for that, but only allowed an action shape of `()`, while MountainCarContinuous uses `(1,)` (which is of course also fine. I've relaxed that constraint now, so it should hopefully work.

**Comment by CristianMonea** [comment]
Now I get this error:

```
Traceback (most recent call last):

  File "c:\users\user\anaconda3\lib\site-packages\tensorforce\execution\untitled0.py", line 6, in <module>
    agent = Agent.create(agent='dpg', environment=environment, max_episode_timesteps = 1000, batch_size=5, memory=10000)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\agents\agent.py", line 116, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\agents\agent.py", line 89, in create
    return Agent.create(agent=agent, environment=environment)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\agents\agent.py", line 66, in create
    agent.initialize()

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\agents\agent.py", line 357, in initialize
    self.model.initialize()

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\models\model.py", line 287, in initialize
    super().initialize()

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\module.py", line 547, in initialize
    name='{}.{}'.format(self.name, function_name), api_function=api_function

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\module.py", line 597, in create_api_function
    results = api_function()

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\models\model.py", line 1406, in api_observe
    terminal=terminal, reward=reward

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\module.py", line 571, in fn
    results = tf_function(*args, **kwargs)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\models\tensorforce.py", line 587, in tf_core_observe
    pred=is_frequency, true_fn=perform_update, false_fn=util.no_operation

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\module.py", line 687, in cond
    x = tf.cond(pred=pred, true_fn=true_fn_wrapper, false_fn=false_fn_wrapper)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow_core\python\ops\control_flow_ops.py", line 1389, in cond_for_tf_v2
    return cond(pred, true_fn=true_fn, false_fn=false_fn, strict=True, name=name)

  File "C:\Users\MiraTechnologies\Anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)

  File "C:\Users\MiraTechnologies\Anaconda3\lib\site-packages\tensorflow_core\python\ops\control_flow_ops.py", line 1174, in cond
    return cond_v2.cond_v2(pred, true_fn, false_fn, name)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow_core\python\ops\cond_v2.py", line 84, in cond_v2
    op_return_value=pred)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\module.py", line 673, in true_fn_wrapper
    result = true_fn()

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\models\tensorforce.py", line 584, in perform_update
    return self.core_update()

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\module.py", line 571, in fn
    results = tf_function(*args, **kwargs)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\models\tensorforce.py", line 664, in tf_core_update
    optimized = self.optimize(indices=indices)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\module.py", line 571, in fn
    results = tf_function(*args, **kwargs)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\models\tensorforce.py", line 685, in tf_optimize
    baseline=self.baseline_policy, memory=self.memory, indices=indices, reward=reward

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\module.py", line 571, in fn
    results = tf_function(*args, **kwargs)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\estimators\estimator.py", line 559, in tf_complete
    states=states, internals=internals, auxiliaries=auxiliaries, actions=actions

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\module.py", line 571, in fn
    results = tf_function(*args, **kwargs)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\policies\action_value.py", line 89, in tf_actions_value
    states=states, internals=internals, auxiliaries=auxiliaries, actions=actions

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\module.py", line 571, in fn
    results = tf_function(*args, **kwargs)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\policies\parametrized_distributions.py", line 304, in tf_actions_values
    actions_values[name] = distribution.action_value(parameters=parameters, action=action)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\module.py", line 571, in fn
    results = tf_function(*args, **kwargs)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\core\distributions\distribution.py", line 56, in tf_action_value
    raise NotImplementedError

NotImplementedError
```

**Comment by AlexKuhnle** [comment]
Ah, again something which hadn't been considered when introducing the singleton-action requirement: that bound continuous action spaces are sometimes handled differently inside Tensorforce (hence the exception here). Fixed this now.

**Comment by CristianMonea** [comment]
It works. Thank you! But it takes around 10 minutes to start (similar for AC, A2C, TRPO). Is my PC too slow or is this slow startup time specific to Tensorforce?

**Comment by AlexKuhnle** [comment]
Hmm... what is your network and memory/batch size? Tensorforce can take some time, as it has to create the graph and initialize everything (it's not (yet) using eager or so). However, I would have said more something like 1min than 10min, so the number surprises me. Can you post the config, just to check whether anything may be wrong there?

**Comment by CristianMonea** [comment]
I've used the code shown in the first message. What config are you referring to (Anaconda environment/PC/other)? If it's of any help:

PC: CPU Intel i7 4770S 3.1GHz, GPU Nvidia GT GeForce 750M, RAM 16 GB
Software: Conda 4.8.2, Tensorflow 2.0.0, Spyder 4.0.1, Python 3.6.8

After a few runs I've noticed that the DPG agent starts after around 3 minutes. However, isn't 3 minutes a bit too slow?

**Comment by AlexKuhnle** [comment]
I meant the "agent config" (arguments to `Agent.create`), but I can see that in your first post, you're right.

I still agree, 3min sounds a bit too much. Three things: First, does it also feel slow after the 3min initialization? How long does 1/100 episode(s) take? Second, if you reduce the memory_relevant sizes, particularly `memory` and maybe `max_episode_timesteps`, does that lead to substantial a speedup? Third, not immediately helpful, but the next version coming soon will move Tensorforce fully to TF2 and also enable eager mode, which should be much faster. (And I assume that 3min init are no problem for "deployment" as long as speed afterwards is good.)

**Comment by CristianMonea** [comment]
I've used these lines:

```
runner = Runner(agent=agent, environment=environment) # Initialize the runner
runner.run(num_episodes=100) # Start the runner
```

1. After 100 episodes, it takes 4.29 s/episode:

`Episodes: 100%|██████████| 100/100 [07:28, reward=-0.20, ts/ep=999, sec/ep=4.29, ms/ts=4.3, agent=97.8%]`

Another example for the A2C model (also a slow starting model):

`Episodes: 100%|██████████| 100/100 [08:19, reward=-3.20, ts/ep=999, sec/ep=5.00, ms/ts=5.0, agent=97.7%] `

2. With 100 times less memory and the least `max_episode_timesteps `allowed:

`agent = Agent.create(agent='dpg', environment=environment, max_episode_timesteps = 999, batch_size=5, memory=100)`

I get the same 3 minutes start time and:

`Episodes: 100%|██████████| 100/100 [07:57, reward=-0.23, ts/ep=999, sec/ep=4.67, ms/ts=4.7, agent=98.0%]`

If I use a lower number of timesteps (e.g., 998) it gives:

```
Traceback (most recent call last):

  File "C:\Users\User\Anaconda3\Lib\site-packages\gym\envs\untitled0.py", line 6, in <module>
    agent = Agent.create(agent='dpg', environment=environment, max_episode_timesteps = 998, batch_size=5, memory=1000)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\agents\agent.py", line 116, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)

  File "C:\Users\User\Anaconda3\lib\site-packages\tensorforce\agents\agent.py", line 83, in create
    assert kwargs['max_episode_timesteps'] >= environment.max_episode_timesteps()

AssertionError
```

3. I hope the next version will speed up the initialization. I am performing a study, so the 3 min delay is not necessary a bottleneck, but it would be of great help if it was lower.

**Comment by AlexKuhnle** [comment]
Regarding changing `max_episode_timesteps`, I should have been clearer: this one needs to be changed as part of `Environment.create(...)`, not `Agent.create(...)`. However, I don't expect big changes since reducing `memory` didn't. I have no idea why it takes so long, it doesn't for me. One last thing maybe: if you've cloned the repo, you could run the corresponding unittest via `python -m unittest test.test_agents.TestAgents.test_dpg` -- this one runs relatively quickly for me for sure.

I don't know when the new version will be ready to replace master, but the core functionality is more or less working (branch `tf2`), and I think will be in "beta version" stage later this week. What's then missing are a few new features and making sure the more TensorFlow-related features like saving, summaries, etc are working properly.

**Comment by CristianMonea** [comment]
The unit test returned:

```
Ran 1 test in 151.808 s

OK
```

That is approx. 2 min and 30 s.

**Comment by AlexKuhnle** [comment]
Yeah, something must be wrong, for me it runs in 20sec. Are you using the TF GPU version? If no problem, you could try what happens if you use the non-GPU version, just to check -- I'm not using a GPU. Also, are you using TF version `2.0.1`? Again, I'm using `2.0.1`, and the update was announced as "important", so maybe something performance-critical changed (although I don't really expect it).

**Comment by CristianMonea** [comment]
I think it is CPU. I haven't made any configurations for using the GPU and my graphics card has CUDA compute capability 3.5, which is below the minimum accepted (supported) by TF 2, so it seems that I couldn't use the GPU even if I wanted to.

I've updated to TF 2.0.1 and I got:

```
Ran 1 test in 141.567s

OK
```

I've also tried with TF 2.1.0, but I got multiple exceptions.

**Comment by AlexKuhnle** [comment]
Yes, TF2.1 is incompatible in some aspects right now. New version will be up-to-date with TF2.2.

**Comment by AlexKuhnle** [comment]
Maybe worth switching to CPU then -- in RL a GPU doesn't speed up things as much as in the supervised case anyway, at least unless you run large-scale experiments with lots of workers collecting experience and parameter servers constantly updating. Depends also on the environment state space, of course -- image inputs benefit more from GPU than low-dimensional inputs.

**Comment by CristianMonea** [comment]
Yes, I am testing simple environments (not large-scale, nor with with complex inputs). Like I said, it seems that I am using the CPU. Can you tell me how to make sure I am using the CPU?

**Comment by AlexKuhnle** [comment]
Sorry, misunderstood. I think if you install `tensorflow` not `tensorflow-gpu`, you're using CPU. Apparently this can also be a (maybe more reliable) indicator:  `tf.test.is_gpu_available()` ([docs](https://www.tensorflow.org/api_docs/python/tf/test/is_gpu_available))

**Comment by CristianMonea** [comment]
I've run the command suggested by you and confirm that TF is using the CPU.

**Comment by AlexKuhnle** [comment]
Unfortunately I have no idea then what the reason for the slow speed may be or what to do about it. Maybe the new version will help.

**Comment by AlexKuhnle** [comment]
Have you solved the problem? Since this doesn't obviously seem to be a problem on Tensorforce side, I will close this issue. By the way, if you want, you can have a look at the `tf2` branch now -- it's not yet finished (saving, summaries and some other features don't work yet), but it should be in a state to play around with. If you set `tf.config.experimental_run_functions_eagerly(run_eagerly=True)`, you force eager execution, which behaves very differently in terms of speed.
