### ISSUE TITLE
self.world: carla.World error

### ISSUE THREAD

**Issue by waynezw0618** [tensorforce/tensorforce#687]
Hi everyone,
 I am installing tensorforce from git. I met the following error message while installing. there is the error message. can anybody help?

[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorforce
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/weizhang/software/ML/DRL/parallel/tensorforce/tensorforce/__init__.py", line 31, in <module>
    from tensorforce.environments import Environment
  File "/Users/weizhang/software/ML/DRL/parallel/tensorforce/tensorforce/environments/__init__.py", line 29, in <module>
    from tensorforce.environments.carla_environment import CARLAEnvironment
  File "/Users/weizhang/software/ML/DRL/parallel/tensorforce/tensorforce/environments/carla_environment.py", line 98
    self.world: carla.World = self.client.get_world()
              ^
SyntaxError: invalid syntax

**Comment by jerabaul29** [comment]
Maybe you can try to use the other readme install instructions?

```pip3 install tensorforce[tf]```

**Comment by AlexKuhnle** [comment]
I think you need to install carla first, which doesn't happen automatically (since it's an optional environment). @Luca96 maybe has more instructions.

**Comment by jerabaul29** [comment]
But it is strange that this crashes the tensorforce import command, right? ...

**Comment by AlexKuhnle** [comment]
Hmm, you're right, I mis-interpreted (or, really, ignored) the stacktrace... :-D  In that case, that may be due to these kind of type annotations being a more recent Python3 feature? Note that it complains about a Syntax error, so it's not missing a package or so (which I also first thought). Anyway, that's not great, Python 3.5+ should ideally all be supported.

**Comment by AlexKuhnle** [comment]
I fixed this now, since indeed these kind of variable type annotations are only introduced in Python 3.6.  So if you try it again with the latest master version, I hope it works now.
