### ISSUE TITLE
tf2 branch fails 'assert environment.states() == states' in parallel run

### ISSUE THREAD

**Issue by joconnor22** [tensorforce/tensorforce#711]
I've been trying out the tf2 branch but having issues getting it to work with parallel environments. The following works fine on the master branch:

```python
from tensorforce import Agent, Environment, Runner

# Number of environments
nEnvs = 2

# Create environments
environments = []
for _ in range(nEnvs):
    environments.append(Environment.create(environment='gym', level='CartPole', max_episode_timesteps=500))

# Create agent
agent = Agent.create(
    agent='ppo',
    environment=environments[0],
    batch_size=32,
    parallel_interactions=nEnvs,
)

# Create and run runner
runner = Runner(agent=agent, environments=environments, num_parallel=nEnvs)
runner.run(num_episodes=64, use_tqdm=True)

# Close
runner.close()
agent.close()
for env in environments:
    env.close()
```

But throws a ValueError on the tf2 branch with the following traceback:
```python
Traceback (most recent call last):
  File "/Users/user/Work/DRL/Examples/Playground/main.py", line 20, in <module>
    runner = Runner(agent=agent, environments=environments, num_parallel=nEnvs)
  File "/Users/user/.local/share/virtualenvs/Playground-0kJfsV1J/src/tensorforce/tensorforce/execution/runner.py", line 163, in __init__
    assert environment.states() == states
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Note that if I switch to `nEnvs = 1` then this works fine on the tf2 branch.

**Comment by AlexKuhnle** [comment]
Hi, thanks for reporting. It looks like a simple bug, so should be possible to fix it very soon.

**Comment by joconnor22** [comment]
Great, thanks a lot.

**Comment by AlexKuhnle** [comment]
I think this should be fixed now. Re-open if not.

**Comment by joconnor22** [comment]
Yes that seems to be working now. Thanks a lot.
