### ISSUE TITLE
TypeError: device() got an unexpected keyword argument 'device_name'

### ISSUE THREAD

**Issue by waynezw0618** [tensorforce/tensorforce#715]
Hello
I am using tensor force on my MacBook Pro. with conda and python3.5

I get following error when I run my application. seems related to some device?

```
TypeError: device() got an unexpected keyword argument 'device_name'

(python3) Weis-MacBook-Pro:boat weizhang$ python test.py 
WARNING:root:No min_value bound specified for state state.
WARNING:root:No min_value specified for action action.
Traceback (most recent call last):
  File "test.py", line 158, in <module>
    objective='policy_gradient', reward_estimation=dict(horizon=1)
  File "/anaconda2/envs/python3/lib/python3.7/site-packages/Tensorforce-0.6.0-py3.7.egg/tensorforce/agents/agent.py", line 122, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/anaconda2/envs/python3/lib/python3.7/site-packages/Tensorforce-0.6.0-py3.7.egg/tensorforce/agents/agent.py", line 93, in create
    agent = agent(**kwargs)
  File "/anaconda2/envs/python3/lib/python3.7/site-packages/Tensorforce-0.6.0-py3.7.egg/tensorforce/agents/tensorforce.py", line 410, in __init__
    config=self.config, saver=saver, summarizer=summarizer
  File "/anaconda2/envs/python3/lib/python3.7/site-packages/Tensorforce-0.6.0-py3.7.egg/tensorforce/core/models/tensorforce.py", line 453, in __init__
    values_spec=values_spec, min_capacity=min_capacity
  File "/anaconda2/envs/python3/lib/python3.7/site-packages/Tensorforce-0.6.0-py3.7.egg/tensorforce/core/module.py", line 447, in submodule
    module = module_cls(*args, **kwargs)
  File "/anaconda2/envs/python3/lib/python3.7/site-packages/Tensorforce-0.6.0-py3.7.egg/tensorforce/core/memories/queue.py", line 43, in __init__
    device=device, name=name, values_spec=values_spec, min_capacity=min_capacity
  File "/anaconda2/envs/python3/lib/python3.7/site-packages/Tensorforce-0.6.0-py3.7.egg/tensorforce/core/memories/memory.py", line 36, in __init__
    super().__init__(device=device, l2_regularization=l2_regularization, name=name)
  File "/anaconda2/envs/python3/lib/python3.7/site-packages/Tensorforce-0.6.0-py3.7.egg/tensorforce/core/module.py", line 160, in __init__
    self.device = tf.device(device_name=device)
TypeError: device() got an unexpected keyword argument 'device_name'
```

**Comment by AlexKuhnle** [comment]
This is probably related to the TensorFlow version you're using. Can you check which one it is?

**Comment by waynezw0618** [comment]
I am using 1.15
```
(python3) Weis-MacBook-Pro:boat weizhang$ python
Python 3.7.7 (default, May  6 2020, 04:59:01) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'1.15.0'
```

**Comment by AlexKuhnle** [comment]
Okay, it requires 2.2, or at least I think 2.0 or 2.1 (but best 2.2).

**Comment by AlexKuhnle** [comment]
Unfortunately the different versions are not compatible enough.

**Comment by waynezw0618** [comment]
good
