### ISSUE TITLE
possible problem with max_episode_timesteps

### ISSUE THREAD

**Issue by jerabaul29** [tensorforce/tensorforce#718]
I wonder if there is a problem on v0.6.0 when the max_episode_timesteps condition is hit.

I have a custom environment. Using:

```
     def max_episode_timesteps(self):
         return(1000)  # dummy value to make sure never stops
```

Gives the following error:

```
WARNING:root:No min_value bound specified for state state.
Episodes:   0%|              | 0/200000 [00:00, reward=0.00, ts/ep=0, sec/ep=0.00, ms/ts=0.0, agent=0.0%]Traceback (most recent call last):
  File "train.py", line 53, in <module>
    runner.run(num_episodes=200000)
  File "/home/jj/Desktop/Git/tensorforce/tensorforce/execution/runner.py", line 549, in run
    self.handle_act(parallel=n)
  File "/home/jj/Desktop/Git/tensorforce/tensorforce/execution/runner.py", line 577, in handle_act
    actions = self.agent.act(states=self.states[parallel], parallel=parallel)
  File "/home/jj/Desktop/Git/tensorforce/tensorforce/agents/agent.py", line 386, in act
    states=states, internals=internals, parallel=parallel, independent=independent
  File "/home/jj/Desktop/Git/tensorforce/tensorforce/agents/recorder.py", line 309, in act
    is_internals_none=is_internals_none, num_parallel=num_parallel
  File "/home/jj/Desktop/Git/tensorforce/tensorforce/agents/agent.py", line 413, in fn_act
    states=states, auxiliaries=auxiliaries, parallel=parallel_tensor
  File "/home/jj/Desktop/Git/tensorforce/tensorforce/core/module.py", line 111, in decorated
    return function_graphs[str(graph_params)](*graph_args)
  File "/home/jj/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/jj/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 618, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/jj/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/jj/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/home/jj/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/jj/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/home/jj/.local/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[0] = [0, 1000] does not index into shape [1,1000,6]
         [[{{node agent/StatefulPartitionedCall/agent/TensorScatterUpdate}}]] [Op:__inference_function_graph_1284]

Function call stack:
function_graph
```

But changing to a much larger max timestep:

```
     def max_episode_timesteps(self):
         return(5000)  # dummy value to make sure never stops
```

The training seems to go fine:

- any idea what the problem is in the first case and how to fix it?
- anything I could do to make it work in the first case?

I do not own the environment code so not sure if I can share it, but if you need more details just let me know.

**Comment by AlexKuhnle** [comment]
My guess would be that the environment doesn't actually terminate after at most 1000 steps (since apparently the agent wants to index the 1000th position). Note that `environment.max_episode_timesteps()` is a "property" of the environment, so the agent won't handle the situation correctly where the environment produces longer episodes, but assumes that the environment behaves according to its "property". Generally, I'd recommend to not define `max_episode_timesteps` unless the environment naturally stops at a given point (like a fixed-step game or so), and instead initialize the environment via `Environment.create(environment=???, max_episode_timesteps=1000)` (which turns the env into a max-1000-step env). Moreover, for efficiency it's probably best to choose a cutoff point which is rarely reached and lower (1000) over a point which is certainly not reached but much higher (5000).

**Comment by jerabaul29** [comment]
Aaah, I thought that reaching the ```environment.max_episode_timesteps()``` value forced termination of the episode, but you say it will not, right? Is this a change in the behavior of tensorforce between the latest v0.5 and the new v0.6?

Thanks, I will change that. I think it should be made very clear in the documentation :) .

**Comment by jerabaul29** [comment]
Mmmh, when I do that I get a new error:

```
Traceback (most recent call last):
  File "train.py", line 57, in <module>
    recorder=None
  File "/home/jj/Desktop/Git/tensorforce/tensorforce/agents/agent.py", line 131, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/home/jj/Desktop/Git/tensorforce/tensorforce/agents/agent.py", line 98, in create
    agent = agent(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'max_episode_timesteps'
```

**Comment by AlexKuhnle** [comment]
No, this was always the case, since from Tensorforce side it's not possible to control how the environment internally handles terminals. It is possible, though, that the problem "doesn't show up", if the agent is not crucially relying on the environment max-timesteps information (can be for some configs or maybe previous implementation versions).

Have you changed environment creation to `Environment.create(..., max_episode_timesteps=N)`? Some algorithms require a `max_episode_timesteps` (others don't, as mentioned above).

**Comment by jerabaul29** [comment]
Ok. Yes, changed everything to be that way, and it works now. Seems like I always get confused at these stages ^^. Thank you for your help!

**Comment by AlexKuhnle** [comment]
Cool, no worries. "Best practice" has changed a bit over the last months, or at least some internals now rely more on "best practice" (like using the right `max_episode_timesteps`). Generally shouldn't cause fundamental problems, but rather make things cleaner, hopefully. :-)
