### ISSUE TITLE
error during initialise the agent

### ISSUE THREAD

**Issue by waynezw0618** [tensorforce/tensorforce#719]
Hello 
I meet a error message says:

```
(python) Weis-MacBook-Pro:training weizhang$ python train.py 
Traceback (most recent call last):
  File "train.py", line 53, in <module>
    recorder=None
  File "/anaconda2/envs/python/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 116, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/anaconda2/envs/python/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 87, in create
    agent = agent(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'multi_step'
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/anaconda2/envs/python/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

```
here is the code:
`    baseline_optimizer=dict(optimizer='adam', learning_rate=1e-3, multi_step=10),
`
the environment is based on anaconda and the packages list is here :

```
(python) Weis-MacBook-Pro:training weizhang$ conda list
# packages in environment at /anaconda2/envs/python:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
absl-py                   0.9.0                    py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
astor                     0.8.0                    py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
attrs                     19.3.0                   pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
c-ares                    1.15.0            h1de35cc_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2020.6.24                     0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2020.6.20                py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cloudpickle               1.3.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.2.2                    py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
google-pasta              0.2.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
grpcio                    1.16.1           py37h044775b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gym                       0.17.2                   pypi_0    pypi
h5py                      2.10.0           py37h0601b69_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
hdf5                      1.10.6               hdbbcd12_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
importlib-metadata        1.7.0                    pypi_0    pypi
intel-openmp              2019.4                      233    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
keras-applications        1.0.8                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
keras-preprocessing       1.1.0                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
kiwisolver                1.2.0                    pypi_0    pypi
libcxx                    10.0.0                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libedit                   3.1.20191231         h1de35cc_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.3                  hb1e8313_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgfortran               3.0.1                h93005f0_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libprotobuf               3.12.3               hab81aa3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
markdown                  3.1.1                    py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
matplotlib                3.2.2                    pypi_0    pypi
mkl                       2019.4                      233    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.3.0            py37hfbe908c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.1.0            py37hc64f4ea_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.1.1            py37h959d312_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
more-itertools            8.4.0                    pypi_0    pypi
msgpack                   1.0.0                    pypi_0    pypi
msgpack-numpy             0.4.6.post0              pypi_0    pypi
ncurses                   6.2                  h0a44026_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy                     1.18.5           py37h1da2735_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.18.5           py37h3304bdc_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
openssl                   1.1.1g               h1de35cc_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
opt_einsum                3.1.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
packaging                 20.4                     pypi_0    pypi
pandas                    1.0.5                    pypi_0    pypi
pip                       20.1.1                   py37_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pluggy                    0.13.1                   pypi_0    pypi
protobuf                  3.12.3           py37hb1e8313_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
py                        1.9.0                    pypi_0    pypi
pyglet                    1.5.0                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pytest                    5.4.3                    pypi_0    pypi
python                    3.7.7                hf48f09d_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2020.1                   pypi_0    pypi
readline                  8.0                  h1de35cc_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
scipy                     1.5.0            py37h912ce22_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
setuptools                49.2.0                   py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
six                       1.15.0                     py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sqlite                    3.32.3               hffcf06c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorboard               2.0.0              pyhb38c66f_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorflow                2.0.0           mkl_py37hda344b4_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorflow-base           2.0.0           mkl_py37h66b1bf0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorflow-estimator      2.0.0              pyh2649769_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorforce               0.5.5                    pypi_0    pypi
termcolor                 1.1.0                    py37_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tk                        8.6.10               hb0a8c7a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tqdm                      4.47.0                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  1.0.1                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wheel                     0.34.2                   py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wrapt                     1.12.1           py37h1de35cc_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.2.5                h1de35cc_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h1de35cc_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
(python) Weis-MacBook-Pro:training weizhang$ conda list python
# packages in environment at /anaconda2/envs/python:
#
# Name                    Version                   Build  Channel
python                    3.7.7                hf48f09d_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.1                    pypi_0    pypi
(python) Weis-MacBook-Pro:training weizhang$ conda list 
# packages in environment at /anaconda2/envs/python:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
absl-py                   0.9.0                    py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
astor                     0.8.0                    py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
attrs                     19.3.0                   pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
c-ares                    1.15.0            h1de35cc_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2020.6.24                     0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2020.6.20                py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cloudpickle               1.3.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.2.2                    py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
google-pasta              0.2.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
grpcio                    1.16.1           py37h044775b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gym                       0.17.2                   pypi_0    pypi
h5py                      2.10.0           py37h0601b69_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
hdf5                      1.10.6               hdbbcd12_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
importlib-metadata        1.7.0                    pypi_0    pypi
intel-openmp              2019.4                      233    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
keras-applications        1.0.8                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
keras-preprocessing       1.1.0                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
kiwisolver                1.2.0                    pypi_0    pypi
libcxx                    10.0.0                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libedit                   3.1.20191231         h1de35cc_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.3                  hb1e8313_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgfortran               3.0.1                h93005f0_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libprotobuf               3.12.3               hab81aa3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
markdown                  3.1.1                    py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
matplotlib                3.2.2                    pypi_0    pypi
mkl                       2019.4                      233    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.3.0            py37hfbe908c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.1.0            py37hc64f4ea_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.1.1            py37h959d312_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
more-itertools            8.4.0                    pypi_0    pypi
msgpack                   1.0.0                    pypi_0    pypi
msgpack-numpy             0.4.6.post0              pypi_0    pypi
ncurses                   6.2                  h0a44026_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy                     1.18.5           py37h1da2735_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.18.5           py37h3304bdc_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
openssl                   1.1.1g               h1de35cc_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
opt_einsum                3.1.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
packaging                 20.4                     pypi_0    pypi
pandas                    1.0.5                    pypi_0    pypi
pip                       20.1.1                   py37_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pluggy                    0.13.1                   pypi_0    pypi
protobuf                  3.12.3           py37hb1e8313_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
py                        1.9.0                    pypi_0    pypi
pyglet                    1.5.0                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pytest                    5.4.3                    pypi_0    pypi
python                    3.7.7                hf48f09d_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2020.1                   pypi_0    pypi
readline                  8.0                  h1de35cc_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
scipy                     1.5.0            py37h912ce22_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
setuptools                49.2.0                   py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
six                       1.15.0                     py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sqlite                    3.32.3               hffcf06c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorboard               2.0.0              pyhb38c66f_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorflow                2.0.0           mkl_py37hda344b4_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorflow-base           2.0.0           mkl_py37h66b1bf0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorflow-estimator      2.0.0              pyh2649769_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorforce               0.5.5                    pypi_0    pypi
termcolor                 1.1.0                    py37_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tk                        8.6.10               hb0a8c7a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tqdm                      4.47.0                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  1.0.1                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wheel                     0.34.2                   py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wrapt                     1.12.1           py37h1de35cc_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.2.5                h1de35cc_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h1de35cc_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
```

what is the problem?

**Comment by AlexKuhnle** [comment]
Considering where the exception is thrown, the problem seems to be another `multi_step` argument passed directly to the agent?

```bash
    agent = agent(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'multi_step'
```

Can you post the full agent initialization/config?

**Comment by waynezw0618** [comment]
```
# Create a PPO agent
agent = Agent.create(
    agent='ppo', environment=boat_env_instance,
    network=network_spec,
    # PPO optimization parameters
    batch_size=10, update_frequency=2, learning_rate=3e-4, multi_step=10,
    subsampling_fraction=0.33,
    # Reward estimation
    likelihood_ratio_clipping=0.2, discount=0.99, predict_terminal_values=False,
    # Baseline network and optimizer
    baseline_network=dict(type='auto', size=32, depth=1),
    baseline_optimizer=dict(optimizer='adam', learning_rate=1e-3, multi_step=10),
    # Preprocessing
....
```

**Comment by AlexKuhnle** [comment]
Ah, I see, you probably used the "latest" readthedocs version (version 0.6 beta), but you're using the pypi Tensorforce version, which is still version 0.5.5. See either the docs [here](https://tensorforce.readthedocs.io/en/0.5.5/), or alternatively install the GitHub master version (see readme).

The problem here is that the main `multi_step` argument was previously called `optimization_steps`.

Hope that helps.
