### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by ArtTemiy** [tensorforce/tensorforce#722]
Trying to run quickstart.py get lots of errors, starting from:

`Traceback (most recent call last):
  File ".../quickstart.py", line 67, in <module>
    main()
  File ".../quickstart.py", line 57, in main
    runner = Runner(agent=agent, environment=environment, max_episode_timesteps=500)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorforce\execution\runner.py", line 177, in __init__
    self.agent = Agent.create(agent=agent, environment=environment)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorforce\agents\agent.py", line 97, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorforce\agents\agent.py", line 116, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorforce\agents\agent.py", line 87, in create
    agent = agent(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'multi_step'`

Using version 0.5.5

**Comment by AlexKuhnle** [comment]
Are you running the latest GitHub `quickstart.py`, by any chance? Since the GitHub master is currently on (not yet pypi-pinned) 0.6 beta version, this version of `quickstart.py` won't be compatible with 0.5.5. In that case, check the 0.5.5 version [here](https://github.com/tensorforce/tensorforce/blob/ce358428965305935b7ee019af1005b49ab1e094/examples/quickstart.py).

**Comment by AlexKuhnle** [comment]
I assume that this means the issue is resolved... :-)
