### ISSUE TITLE
Multiprocessing Issues

### ISSUE THREAD

**Issue by junwoony** [tensorforce/tensorforce#726]
Hello,
I tried to run multi-environment reinforcement learning, but it caused `ConnectionResetError`.

I defined the runner as,
```
num_parallel = 32
runner = Runner(
    agent=agent_spec,
    environments=[setup_env for _ in range(num_parallel)],
    num_parallel=num_parallel,
    remote='multiprocessing',
    max_episode_timesteps=timesteps,
)
```
After about 1000 epochs (varies if I run it again), it keep showing the error. 

```
Episodes:  11%|▋     | 1017/9600 [1:16:35, reward=-3250.95, ts/ep=500, sec/ep=139.06, ms/ts=278.1, agent=2.8%, comm=63.3%]Exception in thread Thread-516070:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorforce/environments/environment.py", line 569, in finish_execute
    self.observation = self.execute(actions=actions)
  File "/opt/conda/lib/python3.7/site-packages/tensorforce/environments/environment.py", line 539, in execute
    states, terminal, reward, seconds = self.receive(function='execute')
  File "/opt/conda/lib/python3.7/site-packages/tensorforce/environments/environment.py", line 490, in receive
    success, result = self.__class__.proxy_receive(connection=self.connection)
  File "/opt/conda/lib/python3.7/site-packages/tensorforce/environments/multiprocessing_environment.py", line 32, in proxy_receive
    return connection[0].recv()
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

... Followed by

Episodes:  11%|▋     | 1051/9600 [1:19:10, reward=-1646.97, ts/ep=500, sec/ep=135.25, ms/ts=270.5, agent=2.9%, comm=61.9%]Exception in thread Thread-533771:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorforce/environments/environment.py", line 569, in finish_execute
    self.observation = self.execute(actions=actions)
  File "/opt/conda/lib/python3.7/site-packages/tensorforce/environments/environment.py", line 539, in execute
    states, terminal, reward, seconds = self.receive(function='execute')
  File "/opt/conda/lib/python3.7/site-packages/tensorforce/environments/environment.py", line 490, in receive
    success, result = self.__class__.proxy_receive(connection=self.connection)
  File "/opt/conda/lib/python3.7/site-packages/tensorforce/environments/multiprocessing_environment.py", line 32, in proxy_receive
    return connection[0].recv()
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
```

Please provide me with any comments/thoughts on this issue.
Thank you.

**Comment by AlexKuhnle** [comment]
Hmm, I have no idea why this happens. Is this using a standard environment, and/or could you try to reproduce the problem with a simple script using CartPole? Otherwise I don't know how to assess this...

**Comment by junwoony** [comment]
@AlexKuhnle It looks like the memory usage is accumulating over time(episode). Does the runner/agent store state observations until the training is terminated? When I tested a very simple (single value) state, the memory usage increased very slowly (or almost constant over time). Is there a way to manage the amount of memory the runner/agent store and reset?

**Comment by AlexKuhnle** [comment]
The runner doesn't store more than a few analytical values, and unless you specify the `recorder` agent argument, the agent should also only store a more or less negligible amount of values (depending on config, it may store reward and terminal values over an episode). So the only effect I can think of is the fact that the effective timestep batch-size varies for TRPO (since it is episode-based), which could mean that the memory per update computation varies and, in case the agent learns to survive for longer and longer, the memory consumption would increase.

Can you observe that this effect increases relative to the size of the state space? And does this definitely happen within one episode, or over the course of multiple episodes? What happens if you change the batch-size?

**Comment by junwoony** [comment]
I solved the memory leak issue. It was the problem in the C code that generated state observation arrays. It did not correctly release the memory after computing the arrays.
