### ISSUE TITLE
Invalid type for MultiInputLayer argument tensors: <class 'str'>.

### ISSUE THREAD

**Issue by wushilan** [tensorforce/tensorforce#739]
Dear developers:
When I set up the following network

> network_spec = [
        [
            dict(type='retrieve', tensors='b'),
            dict(type='dense', size=64, activation='relu'),
            dict(type='register', tensor='b-embedding')
        ],
        [
            dict(type='retrieve', tensors='p'),
            dict(type='dense', size=64, activation='relu'),
            dict(type='flatten'),
            dict(type='register', tensor='p-embedding')
        ],
        [
            dict(type='retrieve',
                 tensors=[
                     'b-embedding',
                     'p-embedding'
                 ],
                 aggregation='concat'),
            dict(type='dense', size=64),
            dict(type='dense', size=64),
            dict(type='dense', size=64)
        ],
    ]
>
And my state is defined in environment as 

>  def states(self):
        states['b'] = dict(type='int',
                            shape=(self.num_r, self.k_2),
                            num_values=self.get_bw_ub() + 1)
        states['p']=dict(type='int',
                            shape=(self.num_r, self.num_v + 1, self.num_n),
                            num_values=2)
        return states
>
I occurred such error in tensorforce=0.6

> Traceback (most recent call last):
  File "/Users/kongyuyang/Desktop/network_slicing_with_drl-master 2/nsdrl/network_slice_train.py", line 120, in <module>
    test_network_slice_env()
  File "/Users/kongyuyang/Desktop/network_slicing_with_drl-master 2/nsdrl/network_slice_train.py", line 83, in test_network_slice_env
    memory=memory)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 131, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 98, in create
    agent = agent(**kwargs)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/agents/dqn.py", line 217, in __init__
    saver=saver, summarizer=summarizer, **kwargs
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/agents/tensorforce.py", line 429, in __init__
    config=self.config, saver=saver, summarizer=summarizer
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/models/tensorforce.py", line 373, in __init__
    actions_spec=self.actions_spec
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/module.py", line 488, in submodule
    module = module_cls(*args, **kwargs)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/policies/parametrized_value_policy.py", line 69, in __init__
    name='network', module=network, modules=network_modules, inputs_spec=self.states_spec
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/module.py", line 488, in submodule
    module = module_cls(*args, **kwargs)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/networks/network.py", line 254, in __init__
    self.layers = list(self._parse_layers_spec(spec=layers, counter=Counter()))
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/networks/network.py", line 259, in _parse_layers_spec
    yield from self._parse_layers_spec(spec=s, counter=counter)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/networks/network.py", line 259, in _parse_layers_spec
    yield from self._parse_layers_spec(spec=s, counter=counter)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/networks/network.py", line 284, in _parse_layers_spec
    yield self.submodule(name=name, module=spec)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/networks/network.py", line 201, in submodule
    is_trainable=is_trainable, is_saved=is_saved, **kwargs
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/module.py", line 488, in submodule
    module = module_cls(*args, **kwargs)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/layers/layer.py", line 208, in __init__
    super().__init__(tensors=tensors, name=name, input_spec=input_spec)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/layers/layer.py", line 109, in __init__
    name='MultiInputLayer', argument='tensors', dtype=type(tensors)
tensorforce.exception.TensorforceError: Invalid type for MultiInputLayer argument tensors: <class 'str'>.
>

**Comment by wushilan** [comment]
When I try to use Tensorforce =0.5.4 instead of 0.6, I occurred this 
Traceback (most recent call last):
  File "/Users/kongyuyang/Desktop/network_slicing_with_drl-master 2/nsdrl/network_slice_train.py", line 120, in <module>
    test_network_slice_env()
  File "/Users/kongyuyang/Desktop/network_slicing_with_drl-master 2/nsdrl/network_slice_train.py", line 83, in test_network_slice_env
    memory=memory)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 114, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 85, in create
    agent = agent(**kwargs)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/agents/dqn.py", line 269, in __init__
    entropy_regularization=entropy_regularization
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/agents/tensorforce.py", line 368, in __init__
    entropy_regularization=entropy_regularization
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/models/tensorforce.py", line 87, in __init__
    actions_spec=self.actions_spec
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/module.py", line 1144, in add_module
    module = module_cls(name, **kwargs)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/policies/parametrized_distributions.py", line 77, in __init__
    inputs_spec=self.states_spec
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/module.py", line 1146, in add_module
    module = module_cls(name, first_arg, **kwargs)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/networks/layered.py", line 58, in __init__
    self.parse_layers_spec(layers_spec=self.layers_spec, layer_counter=Counter())
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/networks/layered.py", line 63, in parse_layers_spec
    self.parse_layers_spec(layers_spec=spec, layer_counter=layer_counter)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/networks/layered.py", line 63, in parse_layers_spec
    self.parse_layers_spec(layers_spec=spec, layer_counter=layer_counter)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/networks/layered.py", line 78, in parse_layers_spec
    self.add_module(name=layer_name, module=layers_spec)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/networks/network.py", line 189, in add_module
    layer = super().add_module(*args, **kwargs)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/module.py", line 1144, in add_module
    module = module_cls(name, **kwargs)
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/layers/dense.py", line 54, in __init__
    l2_regularization=l2_regularization
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/layers/layer.py", line 167, in __init__
    l2_regularization=l2_regularization, **kwargs
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/core/layers/layer.py", line 59, in __init__
    value_spec1=self.input_spec, value_spec2=input_spec
  File "/Users/kongyuyang/anaconda/anaconda3/lib/python3.7/site-packages/tensorforce/util.py", line 637, in unify_value_specs
    name='value-spec', argument='type', value1=dtype1, value2=dtype2
tensorforce.exception.TensorforceError: Value-spec mismatch for argument type: float <-> int.

**Comment by AlexKuhnle** [comment]
Hi @wushilan,

The first problem is just that the retrieve layer always expects a list currently, so e.g. `dict(type='retrieve', tensors=['b'])`. I actually don't know why this has changed, and I think I'll change it back to also accept singleton strings in the future.

The second problem is due to your inputs being discrete integers, but dense layers excepting continuous float inputs. The general advice here is to use an embedding layer to turn the discrete inputs into continuous vectors (at least unless `num_values` is quite big, say, 100+, in which case another solution may be better). An embedding layer can be seen as a sort of dense layer, so you could just replace the initial `'dense'` layers with `'embedding'`. Note that the layers for `b` will also require a `flatten` layer. Generally: embedding layers turn int input of shape `(..., n)` into float tensors of shape `(..., n, m)` where `m` is the size of the layer (so each integer is turned into an `m`-dimensional vector).

Since your network architecture is a standard architecture, you could also just use the [auto network](https://tensorforce.readthedocs.io/en/latest/modules/networks.html#tensorforce.core.networks.AutoNetwork). Your architecture would look as follows:  `network=dict(type='auto', size=64, depth=1, final_depth=3)` (or `depth=2` if you add, not replace, the embedding layers).

**Comment by AlexKuhnle** [comment]
I'm closing this, but feel free to re-open if there are still problems.
