### ISSUE TITLE
I can't install tensorforce's early version

### ISSUE THREAD

**Issue by lushengyang222** [tensorforce/tensorforce#749]
When i download the tensorforce 4.4.0 and use pip install -e .[tf_gpu] it appears
 ERROR: Command errored out with exit status 1:
     command: /home/lu/anaconda3/envs/vn/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lu/\xe4\xb8\x8b\xe8\xbd\xbd/tensorforce-0.4.3/setup.py'"'"'; __file__='"'"'/home/lu/\xe4\xb8\x8b\xe8\xbd\xbd/tensorforce-0.4.3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-uEcLu3
         cwd: /home/lu/下载/tensorforce-0.4.3/
    Complete output (54 lines):
    DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
      ERROR: Command errored out with exit status 1:
       command: /home/lu/anaconda3/envs/vn/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-HXhM4G/future/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-HXhM4G/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-sDYv_8
           cwd: /tmp/pip-wheel-HXhM4G/future/
      Complete output (25 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-wheel-HXhM4G/future/setup.py", line 180, in <module>
          **setup_kwds
        File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
          return distutils.core.setup(**attrs)
        File "/home/lu/anaconda3/envs/vn/lib/python2.7/distutils/core.py", line 137, in setup
          ok = dist.parse_command_line()
        File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/setuptools/dist.py", line 707, in parse_command_line
          result = _Distribution.parse_command_line(self)
        File "/home/lu/anaconda3/envs/vn/lib/python2.7/distutils/dist.py", line 467, in parse_command_line
          args = self._parse_command_opts(parser, args)
        File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/setuptools/dist.py", line 1014, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
        File "/home/lu/anaconda3/envs/vn/lib/python2.7/distutils/dist.py", line 523, in _parse_command_opts
          cmd_class = self.get_command_class(command)
        File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/setuptools/dist.py", line 834, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
          return self.resolve()
        File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
          module = __import__(self.module_name, fromlist=['__name__'], level=0)
        File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 26, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
      ImportError: No module named macosx_libfile
      ----------------------------------------
      ERROR: Failed building wheel for future
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/lu/下载/tensorforce-0.4.3/setup.py", line 65, in <module>
        zip_safe=False)
      File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/setuptools/__init__.py", line 161, in setup
        _install_setup_requires(attrs)
      File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/setuptools/__init__.py", line 156, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/lu/anaconda3/envs/vn/lib/python2.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/home/lu/anaconda3/envs/vn/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmprfvYsG', '--quiet', 'future>=0.14.0']' returned non-zero exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
how can i do it?

**Comment by AlexKuhnle** [comment]
Note that this is not an error coming from Tensorforce, but is thrown during setup inside setuptools. There's not much I can do about that but strongly recommend to move to Python 3 and a newer Tensorforce version, at least if you want to use this framework.
