### ISSUE TITLE
EagerVariableNameReuse when running quickstart.py

### ISSUE THREAD

**Issue by danielbara00** [tensorforce/tensorforce#768]
Hi,
I'm using python 3.8.10.
When I try to run quickstart.py, I get a long stream of errors that I cannot make sense of:

WARNING:root:Infinite min_value bound for state.
Traceback (most recent call last):
  File "C:\Users\alberto\Documents\GitHub\tensorforce\examples\quickstart.py", line 67, in <module>
    main()
  File "C:\Users\alberto\Documents\GitHub\tensorforce\examples\quickstart.py", line 57, in main
    runner = Runner(agent=agent, environment=environment, max_episode_timesteps=500)
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorforce\execution\runner.py", line 178, in __init__
    self.agent = Agent.create(agent=agent, environment=environment)
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorforce\agents\agent.py", line 112, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorforce\agents\agent.py", line 131, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorforce\agents\agent.py", line 104, in create
    return Agent.create(agent=agent, environment=environment)
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorforce\agents\agent.py", line 71, in create
    agent.initialize()
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorforce\agents\agent.py", line 263, in initialize
    self.model.initialize()
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorforce\core\models\tensorforce.py", line 521, in initialize
    super().initialize()
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorforce\core\models\model.py", line 277, in initialize
    super().initialize()
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorforce\core\module.py", line 270, in initialize
    module.initialize()
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorforce\core\module.py", line 270, in initialize
    module.initialize()
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorforce\core\module.py", line 270, in initialize
    module.initialize()
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorforce\core\layers\dense.py", line 76, in initialize
    super().initialize()
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorforce\core\layers\layer.py", line 707, in initialize
    self.bias = self.variable(
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorforce\core\module.py", line 620, in variable
    variable = tf.Variable(
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py", line 262, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py", line 244, in _variable_v2_call
    return previous_getter(
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py", line 237, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2633, in default_variable_creator_v2
    return resource_variable_ops.ResourceVariable(
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1507, in __init__
    self._init_from_args(
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1661, in _init_from_args
    handle = eager_safe_variable_handle(
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 242, in eager_safe_variable_handle
    return _variable_handle_from_shape_and_dtype(
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 174, in _variable_handle_from_shape_and_dtype
    gen_logging_ops._assert(  # pylint: disable=protected-access
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 49, in _assert
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\alberto\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\framework\ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [0] [Op:Assert] name: EagerVariableNameReuse

**Comment by AlexKuhnle** [comment]
Hi, can you check the TensorFlow version you have installed?

**Comment by xix22** [comment]
Yes, I have tensorflow 2.3.1 (and tensorforce 0.6.2).

**Comment by AlexKuhnle** [comment]
Could you test whether updating to the latest TensorFlow version helps? Also, what's your NumPy version? I think 1.20+ cause some problems with TensorFlow, whereas 1.19.5 seems to work well (although it doesn't look like this is the problem here). Otherwise I have no idea -- for me the quickstart example runs fine.

**Comment by xix22** [comment]
It works with the latest tensorflow version. Version 2.3.1 got installed with pip install tensorforce. Can the requirements for tensorforce be updated?

**Comment by AlexKuhnle** [comment]
I assume you've installed via pip. That's a good point, the pip version hasn't been updated for a while. I've updated to a new pip version now. Assume this can be closed then.
