### ISSUE TITLE
How to use enable_int_action_masking?

### ISSUE THREAD

**Issue by bezineb5** [tensorforce/tensorforce#775]
Hello,

I've tried to disable "enable_int_action_masking" and I'm running into issues:

Example code:
```python
from tensorforce import Environment, Agent


environment = Environment.create(environment='cartpole.json')
agent = Agent.create(
    agent='double_dqn',
    environment=environment,
    batch_size=64,
    memory=500,
    config=dict(enable_int_action_masking=False),
)

# Save agent SavedModel
agent.save(directory='saved-model', format='saved-model')
```

And I get the error:
```
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    agent.save(directory='saved-model', format='saved-model')
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 579, in save
    path = self.model.save(directory=directory, filename=filename, format=format, append=append)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorforce/core/models/model.py", line 831, in save
    signatures = independent_act.get_concrete_function(
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1299, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1205, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorforce/core/module.py", line 108, in function_graph
    args = function(self, **kwargs.to_kwargs(), **params_kwargs)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorforce/core/models/model.py", line 556, in independent_act
    actions, internals = self.core_act(
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorforce/core/module.py", line 136, in decorated
    output_args = function_graphs[str(graph_params)](*graph_args)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorforce/core/module.py", line 108, in function_graph
    args = function(self, **kwargs.to_kwargs(), **params_kwargs)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorforce/core/models/tensorforce.py", line 1030, in core_act
    actions, next_internals['policy'] = self.policy.act(
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorforce/core/module.py", line 136, in decorated
    output_args = function_graphs[str(graph_params)](*graph_args)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorforce/core/module.py", line 108, in function_graph
    args = function(self, **kwargs.to_kwargs(), **params_kwargs)
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorforce/core/policies/parametrized_value_policy.py", line 281, in act
    actions = self.actions_spec.fmap(
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorforce/core/utils/nested_dict.py", line 128, in fmap
    setitem(name, function(*args))
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorforce/core/policies/parametrized_value_policy.py", line 275, in function
    mask = auxiliaries[name]['mask']
  File "/Users/benjamin/Documents/Development/Projects/PiBoat/learning/venv/lib/python3.8/site-packages/tensorforce/core/utils/nested_dict.py", line 228, in __getitem__
    assert self.is_singleton()
AssertionError
```

Is there something I'm missing here?

Would the enable_int_action_masking=False remove the "mask" input in the saved model?
<img width="346" alt="image" src="https://user-images.githubusercontent.com/1782448/112716400-9a615d00-8ebc-11eb-965f-4a05dc5c1c5c.png">

I have similar issues on a more complex example, but it's too long to copy.
 
Thanks a lot!
Benjamin

**Comment by AlexKuhnle** [comment]
Hi, you're right, there was a conditional missing in the `parametrized_value_policy`. I think my latest commit should fix this, could you try it out again?

**Comment by bezineb5** [comment]
I confirm it's fixed, thanks a lot!
