### ISSUE TITLE
Agent with Keras Network

### ISSUE THREAD

**Issue by Floriangarcia7** [tensorforce/tensorforce#784]
Hi,

I find Tensorforce really interesting and I would like to use it in my project. However, I have a question.

I need an Agent using PPO (Proximal Policy Optimization), which is possible by doing this : 
`agent = Agent.create(agent='ppo', ....)`

However, I would also need this agent to use my Keras model. I saw that there was a 'network' parameter to specify that we want to use a Keras custum model. Is this the case?

I tried to implement this and got an error.

My code :
```python
# Pre-defined or custom environment 
environment = Environment.create(
    environment='gym', level='CartPole', max_episode_timesteps=500
)

model= [
        dict(type='conv2d_transpose', input_shape=(4, 4, 32), filters=16, kernel_size=(3, 3), strides=2, padding='same'),
        dict(type='conv2d_transpose', filters=8, kernel_size=(3, 3), strides=2, padding='same'),
        dict(type='conv2d_transpose', filters=4, kernel_size=(3, 3), strides=2, padding='same'),
        dict(type='conv2d_transpose', filters=2, kernel_size=(3, 3), strides=2, padding='same'),
        dict(type='conv2d_transpose', filters=1, kernel_size=(3, 3), strides=2, padding='same')
    ]

# Instantiate a Tensorforce agent
agent = Agent.create(
    agent='ppo',
    environment=environment,  # alternatively: states, actions, (max_episode_timesteps) 
    batch_size=10,
    policy=dict(network='keras', model=model)
)

# Train for 300 episodes
for _ in range(300):

    # Initialize episode
    states = environment.reset()
    terminal = False

    while not terminal:
        # Episode timestep
        actions = agent.act(states=states)
        states, terminal, reward = environment.execute(actions=actions)
        agent.observe(terminal=terminal, reward=reward)

agent.close()
environment.close()
```

And I get this error : 
```
Traceback (most recent call last): 
  File "test_tensorforce.py", line 68, in <module>
    policy=dict(network='keras', model = model),
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 131, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 98, in create
    agent = agent(**kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/agents/ppo.py", line 261, in __init__
    saver=saver, summarizer=summarizer, tracking=tracking, **kwargs
TypeError: __init__() got multiple values for keyword argument 'policy'
```
Do you know why I have this error ?
Is there a way to do this ? It would really help me with my project.

Thanks in advance !

**Comment by Floriangarcia7** [comment]
I solved this error with the ticket #736 

But now, I have an other error : 
```
Traceback (most recent call last): 
  File "test_tensorforce.py", line 70, in <module>
    network=model,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 131, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/agents/agent.py", line 98, in create
    agent = agent(**kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/agents/ppo.py", line 261, in __init__
    saver=saver, summarizer=summarizer, tracking=tracking, **kwargs
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/agents/tensorforce.py", line 442, in __init__
    config=self.config, saver=saver, summarizer=summarizer, tracking=tracking
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/core/models/tensorforce.py", line 384, in __init__
    actions_spec=self.actions_spec
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/core/module.py", line 505, in submodule
    module = module_cls(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/core/policies/parametrized_distributions.py", line 68, in __init__
    ParametrizedPolicy.__init__(self=self, network=network, inputs_spec=self.states_spec)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/core/policies/parametrized_policy.py", line 53, in __init__
    name='network', module=network, modules=network_modules, inputs_spec=inputs_spec
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/core/module.py", line 505, in submodule
    module = module_cls(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/core/networks/network.py", line 259, in __init__
    self.layers = list(self._parse_layers_spec(spec=layers, counter=Counter()))
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/core/networks/network.py", line 264, in _parse_layers_spec
    yield from self._parse_layers_spec(spec=s, counter=counter)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/core/networks/network.py", line 289, in _parse_layers_spec
    yield self.submodule(name=name, module=spec)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/core/networks/network.py", line 206, in submodule
    is_trainable=is_trainable, is_saved=is_saved, **kwargs
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/core/module.py", line 505, in submodule
    module = module_cls(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'input_shape'
```

**Comment by Floriangarcia7** [comment]
I tried this (an other implementation) : 
```python
model = Sequential()
model.add(Conv2DTranspose(input_shape=(4, 4, 32), filters=16, kernel_size=(3, 3), strides=2, padding='same'))
model.add(Conv2DTranspose(filters=8, kernel_size=(3, 3), strides=2, padding='same'))
model.add(Conv2DTranspose(filters=4, kernel_size=(3, 3), strides=2, padding='same'))
model.add(Conv2DTranspose(filters=2, kernel_size=(3, 3), strides=2, padding='same'))
model.add(Conv2DTranspose(filters=1, kernel_size=(3, 3), strides=2, padding='same'))

# Pre-defined or custom environment
environment = Environment.create(
    environment='gym', level='CartPole', max_episode_timesteps=500
)

network = KerasNetwork(model=model, name='myKerasModel')

agent_config = TensorforceConfig(
        batch_size=10,
        learning_rate=0.001,
        states=env.states(),
        actions=env.actions(),
        max_episode_timesteps=env.max_episode_timesteps(),
        network=network
)

agent = ProximalPolicyOptimization(config=agent_config)

# Train for 300 episodes
for _ in range(300):
    
    # Initialize episode
    states = environment.reset()
    terminal = False

    while not terminal:
        # Episode timestep
        actions = agent.act(states=states)
        states, terminal, reward = environment.execute(actions=actions)
        agent.observe(terminal=terminal, reward=reward)

agent.close()
environment.close()
```

And I have this error now : 
```
Traceback (most recent call last): 
  File "test_tensorforce.py", line 51, in <module>
    network= KerasNetwork(model=model, name='myKerasModel')
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/core/networks/keras.py", line 43, in __init__
    device=device, l2_regularization=l2_regularization, name=name, inputs_spec=inputs_spec
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/core/networks/network.py", line 42, in __init__
    super().__init__(name=name, device=device, l2_regularization=l2_regularization)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tensorforce/core/module.py", line 175, in __init__
    assert len(Module._MODULE_STACK) >= 1
AttributeError: type object 'Module' has no attribute '_MODULE_STACK'

```

**Comment by AlexKuhnle** [comment]
Hi @Floriangarcia7,

No worries about the spam. You probably realised this by now but:

- In your first attempt, you are using Tensorforce's layer specification (`model = [dict(type='conv2d_transpose', ...`), which is not a Keras Model and hence doesn't require `network='keras'`, you can just do `network=[dict(...`.
- In your second attempt, you use Tensorforce's automatic network `auto`, which is based on the same Tensorforce layer spec functionality. However, there shouldn't be an exception, can you post your full agent config for this one?
- In your third attempt, you're correctly using a Keras Model as argument to a network of type `keras`. However, a few comments here:
    - `TensorforceConfig` is not for agent configs, but for some special settings, see `config` argument [here](https://tensorforce.readthedocs.io/en/latest/agents/tensorforce.html), so replace with `dict` and don't pass as `config=agent_config` but instead as `**agent_config`.
    - It is preferable to create agents via `Agent.create(agent='ppo', **agent_config)` instead of directly as `ProximalPolicyOptimization(**agent_config)`, otherwise you may need to manually initialize via `agent.initialize()`.
    -  You shouldn't instantiate Tensorforce modules but instead pass a config spec, so replace the network spec with `network = dict(type='keras', model=model)` (the underlying TensorFlow modules and variables need to be instantiated in the correct graph name scope etc, technical requirement for TensorFlow / the way Tensorforce uses it).
    - The `name` argument for `network` shouldn't be specified, Tensorforce sets these names internally (note it says `internal use` [here](https://tensorforce.readthedocs.io/en/latest/modules/networks.html)).

I think there is still a problem with the Keras network spec after addressing this, but let me know if you get it to work with these changes.

**Comment by Floriangarcia7** [comment]
Hi @AlexKuhnle ,

Thank you for your very clear and enriching feedback.

- For my second attempt, I can't reproduce the error because in the meantime I modified my code :/

- I tried to modify my third attempt by applying your advice like this : 

```python
# Pre-defined or custom environment
environment = Environment.create(
    environment='gym', level='CartPole', max_episode_timesteps=500
)

model = Sequential()
model.add(Conv2DTranspose(input_shape=(4, 4, 32), filters=16, kernel_size=(3, 3), strides=2, padding='same'))
model.add(Conv2DTranspose(filters=8, kernel_size=(3, 3), strides=2, padding='same'))
model.add(Conv2DTranspose(filters=4, kernel_size=(3, 3), strides=2, padding='same'))
model.add(Conv2DTranspose(filters=2, kernel_size=(3, 3), strides=2, padding='same'))
model.add(Conv2DTranspose(filters=1, kernel_size=(3, 3), strides=2, padding='same'))

network = KerasNetwork(model=model, name='myKerasModel')

agent_config = dict(
        batch_size=10,
        learning_rate=0.001,
        states=env.states(),
        actions=env.actions(),
        max_episode_timesteps=env.max_episode_timesteps(),
        network=network
)

agent = Agent.create(agent='ppo', **agent_config)


# Train for 300 episodes
for _ in range(300):

    # Initialize episode
    states = environment.reset()
    terminal = False

    while not terminal:
        # Episode timestep
        actions = agent.act(states=states)
        states, terminal, reward = environment.execute(actions=actions)
        agent.observe(terminal=terminal, reward=reward)

agent.close()
environment.close()
```

And I got the same error :
```Traceback (most recent call last):
  File "test_tensorforce.py", line 38, in <module>
    network = KerasNetwork(model=model, name='myKerasModel')
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\core\networks\keras.py", line 43, in __init__
    device=device, l2_regularization=l2_regularization, name=name, inputs_spec=inputs_spec
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\core\networks\network.py", line 42, in __init__
    super().__init__(name=name, device=device, l2_regularization=l2_regularization)
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\core\module.py", line 175, in __init__
    assert len(Module._MODULE_STACK) >= 1
AttributeError: type object 'Module' has no attribute '_MODULE_STACK'
```

However, if I don't specify the `name` in the `KerasNetwork ` argument I get this error message : 
```
Traceback (most recent call last):
  File "test_tensorforce.py", line 38, in <module>
    network = KerasNetwork(model=model)
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\core\networks\keras.py", line 43, in __init__
    device=device, l2_regularization=l2_regularization, name=name, inputs_spec=inputs_spec
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\core\networks\network.py", line 42, in __init__
    super().__init__(name=name, device=device, l2_regularization=l2_regularization)
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\core\module.py", line 167, in __init__
    name = name.replace('/', '_')
```

So that's why I specified the name because otherwise I had this error.

**Comment by AlexKuhnle** [comment]
You missed one comment ;-)

> You shouldn't instantiate Tensorforce modules but instead pass a config spec, so replace the network spec with `network = dict(type='keras', model=model)` (the underlying TensorFlow modules and variables need to be instantiated in the correct graph name scope etc, technical requirement for TensorFlow / the way Tensorforce uses it).

So if you replace `network = KerasNetwork(model=model, name='myKerasModel')` by `network = dict(type='keras', model=model)`, it should work better (and then the name will automatically be chosen internally).

**Comment by Floriangarcia7** [comment]
Oops, sorry !

I tried replacing `network = KerasNetwork(model=model, name='myKerasModel')` by `network = dict(type='keras', model=model)` like this : 
```python

environment = Environment.create(
    environment='gym', level='CartPole', max_episode_timesteps=500
)

model = Sequential()
model.add(Conv2DTranspose(input_shape=(4, 4, 32), filters=16, kernel_size=(3, 3), strides=2, padding='same'))
model.add(Conv2DTranspose(filters=8, kernel_size=(3, 3), strides=2, padding='same'))
model.add(Conv2DTranspose(filters=4, kernel_size=(3, 3), strides=2, padding='same'))
model.add(Conv2DTranspose(filters=2, kernel_size=(3, 3), strides=2, padding='same'))
model.add(Conv2DTranspose(filters=1, kernel_size=(3, 3), strides=2, padding='same'))

agent_config = dict(
        batch_size=10,
        learning_rate=0.001,
        states=environment.states(),
        actions=environment.actions(),
        max_episode_timesteps=environment.max_episode_timesteps(),
        network=dict(type='keras', model=model)
)

agent = Agent.create(agent='ppo', **agent_config)

# Train for 300 episodes
for _ in range(300):
    # Initialize episode
    states = environment.reset()
    terminal = False

    while not terminal:
        # Episode timestep
        actions = agent.act(states=states)
        states, terminal, reward = environment.execute(actions=actions)
        agent.observe(terminal=terminal, reward=reward)

agent.close()
environment.close()
```

And now I get a new error :
```
Traceback (most recent call last):
  File "test_tensorforce.py", line 49, in <module>
    agent = Agent.create(agent='ppo', **agent_config)
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\agents\agent.py", line 131, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\agents\agent.py", line 98, in create
    agent = agent(**kwargs)
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\agents\ppo.py", line 261, in __init__
    saver=saver, summarizer=summarizer, tracking=tracking, **kwargs
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\agents\tensorforce.py", line 442, in __init__
    config=self.config, saver=saver, summarizer=summarizer, tracking=tracking
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\core\models\tensorforce.py", line 384, in __init__
    actions_spec=self.actions_spec
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\core\module.py", line 505, in submodule
    module = module_cls(*args, **kwargs)
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\core\policies\parametrized_distributions.py", line 68, in __init__
    ParametrizedPolicy.__init__(self=self, network=network, inputs_spec=self.states_spec)
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\core\policies\parametrized_policy.py", line 55, in __init__
    output_spec = self.network.output_spec()
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorforce\core\networks\keras.py", line 64, in output_spec
    output_shape = self.keras_model.compute_output_shape(input_shape=input_shape)
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorflow\python\keras\engine\sequential.py", line 401, in compute_output_shape
    shape = layer.compute_output_shape(shape)
  File "C:\Users\garciaf\Anaconda3\envs\python_3_7\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 1348, in compute_output_shape
    output_shape[c_axis] = self.filters
IndexError: list assignment index out of range
```

**Comment by Floriangarcia7** [comment]
That's what I thought too.

I am a beginner in tensorflow and actually I think my `input_shape` is `(None, 4, 4, 32)`.
```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv2d_transpose (Conv2DTran (None, 8, 8, 16)          4624
_________________________________________________________________
conv2d_transpose_1 (Conv2DTr (None, 16, 16, 8)         1160
_________________________________________________________________
conv2d_transpose_2 (Conv2DTr (None, 32, 32, 4)         292
_________________________________________________________________
conv2d_transpose_3 (Conv2DTr (None, 64, 64, 2)         74
_________________________________________________________________
conv2d_transpose_4 (Conv2DTr (None, 128, 128, 1)       19
=================================================================
Total params: 6,169
Trainable params: 6,169
Non-trainable params: 0
```

And I don't know how to specify the `batch_size` to my model, because it seems to me that here, my `batch_size` is `None`

**Comment by AlexKuhnle** [comment]
Yes, for Conv2dTranspose you will need a different state shape, so you can try simple Dense layers instead.

**Comment by Floriangarcia7** [comment]
I didn't quite understand.
Instead of what? the `input_shape ` of my first layer?

**Comment by AlexKuhnle** [comment]
CartPole's state space is of shape `(4,)`, so it's not an image and hence you can't apply 2D convolutions. If you replace the `Conv2DTranspose` layers with `Dense` layers, your network should work.

**Comment by AlexKuhnle** [comment]
I assume this is resolved, obvs feel free to re-open or open a new issue if problems remain.
