### ISSUE TITLE
Agent.creat(agent = "ppo", network = network) still initialize netwok = "auto"

### ISSUE THREAD

**Issue by CycloneMAO** [tensorforce/tensorforce#793]
Recently when I used Agent.create() to create an agent like

```
tsfc_agent = Agent.create(
    agent = "ppo",
    environment = my_env,
    max_episode_timesteps = my_env.max_episode_timesteps(),
    states = my_env.states(),
    actions = my_env.actions(),
    policy=dict(distributions=dict(float=dict(type='beta')),
        network = network_spec),
    batch_size = 32,
    memory=10000)
```

it showed me this error, 

> TypeError: __init__() got multiple values for keyword argument 'policy'

Then I debugged into the creator of the PPO agent and found something interesting:

- In line 97-99 of \agents\agent.py :
 ```
if isinstance(agent, type) and issubclass(agent, Agent):
                agent = agent(**kwargs)
                assert isinstance(agent, Agent)
```
It will call the creator for PPO agent and feed **kwargs (which contains all my aruguments I specified above) into PPO's creator. 
- Then in PPO's creator network is specified as "auto" by default and **kwargs is deprecated(and no more appearance in the creator, which means network is always "auto" no matter what you specified in Agent.creat(network =...)
- Most interestingly, in line 204-207 of \agents\ppo.py: 
```
policy = dict(
    type='parametrized_distributions', network=network, temperature=1.0,
    use_beta_distribution=use_beta_distribution
)
```
It will specify the policy mandatorily this way all the time, which means my specification for policy (also in **kwargs) is meaningless.

Please justify my observations above and I am looking forward to the solution(help me and my course project).

**Comment by AlexKuhnle** [comment]
Good observation. Yes, there is a "mismatch" in the arguments between the more general "Tensorforce agent" ([docs](https://tensorforce.readthedocs.io/en/latest/agents/tensorforce.html)) and sub-agents like PPO ([docs](https://tensorforce.readthedocs.io/en/latest/agents/ppo.html)). The reason for this is that PPO is associated with some config choices (for instance, the fact that the policy is of type `parametrized_distributions`) which the user is not required to specify / supposed to change. One might argue whether some choices should be "hard-coded" for PPO or be configurable by the user, and you're right that there are some aspects of the policy (e.g. `temperature`, or Beta distribution) which could indeed be changed (however, it needs to be `parametrized_distributions`). For the Beta distribution this is actually possible: there is an argument `use_beta_distribution` which changes the default from `Gaussian` to `Beta` for continuous actions.

Hope that helps.

**Comment by CycloneMAO** [comment]
In case that **kwargs is deprecated in the creator of PPO agent, it seems impossible to specify any custom network if I simply use `Agent.create(agent = 'ppo', network = whatever...)`. So I turn to use the TensorforceAgent.  My code looks like:
```
network_spec = [
    dict(type = 'flatten'),
    dict(type='dense', size=32, activation='relu'),
    dict(type='dense', size=32, activation='relu'),
]
bs_network_spec = [
    dict(type = 'flatten'),
    dict(type='dense', size=32, activation='relu'),
    dict(type='dense', size=32, activation='relu'),
]

tsfc_agent = Agent.create(
    environment = my_env,
    max_episode_timesteps = 10,
    states = my_env.states(),
    actions = my_env.actions(),
    policy=dict(type='parametrized_distributions',
                use_beta_distribution = True,
                network = network_spec),
    baseline = dict(type='parametrized_state_value', 
                    network=bs_network_spec),
    objective = dict(type = 'policy_gradient', 
                     importance_sampling = True, 
                     clipping_value = 0.25),
    update = dict(unit = "episodes", batch_size = 64), 
    optimizer = dict(
            optimizer='adam', learning_rate=1e-3, multi_step=10,
            subsampling_fraction=.33),
    reward_estimation = dict(
                horizon="episode", discount=.9, 
                predict_horizon_values="early",
                estimate_advantage=True),
    memory=1000)
```

If I create the agent in this way, what's the difference between it and that created via PPO's creator? Will it have the same objective and optimization logic suggested in the original paper?

**Comment by AlexKuhnle** [comment]
Two things missing in your config to replicate the PPO config with the `tensorforce` agent:

- `memory = dict(type='recent', capacity=1000)`, otherwise the default is a replay memory.
- `baseline_objective = dict(type='state_value')`.

Can you try it again with these changes? I need to check why the exception is thrown, though, don't see a reason why that would happen.

However, your initial suggestion, `Agent.create(agent = 'ppo', network = network_spec, ...)` should also work, you just can't specify a full policy (`dict(type='parametrized_distributions', ...)`) for the `network` argument. What exceptions do you get there?

Finally, minor comment: `batch_size` is specified in episodes if `unit='episodes'`, so in your config would consist of 64 episodes, which presumably are *a lot* of timesteps. Something like `batch_size <= 20` should suffice in most cases. Obviously depends on your environment...

**Comment by CycloneMAO** [comment]
The tensorflow problem disappears after I specify the memory and baseline_objective the way you suggested!! I debug into the line with the problem: line 128 in \core\module.py `output_args = function_graphs[str(graph_params)](*graph_args)` When it comes to observe the step which needs update(first time),  `graph_args` just becomes `()`, which may incur the tensorflow error(need to justify? or never mind.. lol)

My point for `Agent.creat(agent = 'ppo', network = ...)` is that it will create the PPO agent via (In line 97-99 of `\agents\agent.py`)
```
if isinstance(agent, type) and issubclass(agent, Agent):
               agent = agent(**kwargs)
               assert isinstance(agent, Agent)
```
Then `netwok `is passed through `**kwargs`, which won't have any effect inside the creator of PPO since `network ` is initialied as `'auto'` by key and passed to the policy via that default part in line 204-207 of `\agents\ppo.py`. And the network I define in `**kwargs` is passed to `super().__init__()` which belongs to TensorforceAgent. Then my network has no effect on anything all the time.

For the `batch_size`, yes in the original paper it will train all the steps in any episodes selected by the batch so my actual batch_size may be big (actual batch_size = `batch_zie ` * `max_episode_timesteps`, for my fixed episode length = `max_episode_timesteps`).  

BTW, I found the `horizon `argument for `reward_estimation `is quite confusing: 

- if it is`"episode"`, does it mean that it will include all the rewards before the end of an episode for computing the Return(and use estimated state value for nonterminal ends, which should be my case since I do not have a terminal state but a fixed episode length for my environment)
- if it is an integer, what's the meaning? fixed number of rewards are involved in the calculation which means the tail part of the episode is ignored for training due to lack of rewards remained?

And one more thing to be confirmed, what happened if `baseline ` is None for my fixed-length-episode environment without a terminal state? How does it compute the Return since we do need an estimate of state-value for the final step of an episode(not terminal because in general terminal should has 0 reward afterwards). My point is when Return has infinite horizon by its definition, isn't `baseline ` necessary?

**Comment by CycloneMAO** [comment]
![image](https://user-images.githubusercontent.com/55273625/119408349-2276ae00-bd18-11eb-9b1e-1f0657404320.png)
Could you explain a bit about this log output?
The first line is generated by the runner and I want to figure out the meanings of `reward = -0.05` and `agent = 0.6%`
The following lines are the action value for each step (my action is float within [0,1] so I specify `use_beta_distribution = True` in order to use the beta parameterization.  It seems to sample values near 0 all the time, is it normal or does the beta parameterization fail in my case?

**Comment by AlexKuhnle** [comment]
- Note that if you pass a bunch of arguments as dict in the form `agent(**kwargs)`, this doesn't mean that `**kwargs` is handled by the `**kwargs` argument of the corresponding constructor. So:

```python
def f(x, **kwargs):
    return x + kwargs['y']

kwargs = dict(x=4, y=5)
print(f(**kwargs))  # 9
```

Is that what you are thinking? Because that will work correctly, so if you specify `network`, it will be used by PPO accordingly. Or have you confirmed that it is not used correctly? If so, how?

- You're understanding of `horizon='episode'` is correct, `return ~ sum(rewards[t:]) + state-value` (roughly, ignoring discount). If it is an integer, `horizon=n`, then only the rewards of `n` timesteps are used and for the n-th timestep the state-value is used (unless terminal), `return ~ sum(rewards[t:t+n]) + state-value`. At the end of an episode, when there are no `n` timesteps left, only the remaining `k` rewards are used, but still the state-value for the final state (unless terminal), `return ~ sum(rewards[t:]) + state-value`. Does that explain it?

- Good question: yes, it makes sense to use a baseline in such cases, for sure. If no baseline is specified, no state-value estimate is added, so states closer to the non-terminal end state accumulate less rewards. Depending on whether your rewards are mostly/only positive or zero-centered (in which case the sum of a sequence of rewards can be expected to be roughly zero), this has a more or less negative effect, but it is rarely ideal.

- `reward=-0.05` means that the undiscounted episode return is `-0.05` -- not a great choice of word here ("reward"), actually. `agent=0.6%` means that the agent computation takes roughly 0.6% of the overall time, so your environment computation seems to be very slow. Does that make sense? If so, you might be interested in parallelization at some point... :-)

- You don't need to use the Beta distribution for bounded action spaces (anymore -- it was preferable in older versions of Tensorforce). It might be that the agent just overfits to 0, or it might be the learning doesn't work well. Moreover, to be honest, I'm not so sure how well the Beta distribution works across problems, so I would actually recommend not using it. By default, a tanh-transformed Gaussian distribution is used.

**Comment by CycloneMAO** [comment]
- No my meaning is that the creator has already a keyword argument for network, and then there's two networks(one is `"auto"`, another is what I pass), then at the end of the creator the program passes both policy it created by default(which contains the "auto" network) and the policy I pass. This will incur multiple values for the same argument(`policy`).
- So the integer value for the `horizon `is like the maximum number of rewards it included in the calculation? That will make sense.
- Does it mean that the estimator for return will compute every reward along the path? If that is the case, the tail part will have less return value as you said. But won't that cause bias since if there are two equivalent steps, say t1 and t2 (say t1<t2), at both the agent observes the same state and conducts the same action, the return for t1 is generally larger than that for t2?
- What can I do to boost up the speed? I use fixed data flow to feed the environment and only calculate some internal states using numpy. How is parallelization applied in this case?
- It's a good suggestion. I will do more tests on different distributions.
- Currently, I am working on a project related to RL in trading. In the context of trading, there are multiple tasks for a trader to accomplish. For example, in the beginning, the agent has to decide whether to open a position. Once it opens a position, it has to decide whether to hold it or close it. Then there are two separate action spaces, one is for the opening, the other is for the closing. It's different from the masking mechanism for discrete action space since all the actions are in the same action space. I wonder if there's any functionality to establish a multi-task agents. Here the word "multi-task" refers to different action spaces the agent will encounter in different timesteps.  I suppose that the training process looks like: the network has multiple output nodes, each for a distinct action space; The agent can only look at one node to make decisions and the reward(return) belongs to that node exceptionally; so the network only performs gradient descent on that node while not backpropagating any gradients to the other. It looks like this network is shared by different agents(each of them deals with a distinct task) to a high extent. Would my setting-up make sense? Any functionality for this kind of agent in this brilliant package?

**Comment by AlexKuhnle** [comment]
- Can you post the code which you think shows the wrong behavior? And the exception if any.
- Yes, the maximum number of rewards before "bootstrapping" the return value with the state-value of the horizon state.
- Yes, that's why it's not ideal, and can only partially be mitigated by making the rewards zero-centered (then at least the difference won't scale with the distance `t2 - t1` in the same way).
- Is it the case that your environment is relatively "slow"? Two options:
    - You can run multiple instances of your environment in separate processes or even machines, if you have the resources.
    - If possible, you can write your environment code in a vectorized way, so you can compute multiple simultaneously running episodes within a single `execute()` computation.
- Multi-task setup: How does the agent know what action space to use? Does the environment signal which space is required, or is it the agent who decides what action space to use for the next action? The former sounds like this could be done via multiple action components and component-level masking, but I'm not sure...

**Comment by CycloneMAO** [comment]
- The conflict of multiple values for `policy `is illustrated in my first post:
  
  ```
  tsfc_agent = Agent.create(
      agent = "ppo",
      environment = my_env,
      max_episode_timesteps = my_env.max_episode_timesteps(),
      states = my_env.states(),
      actions = my_env.actions(),
      policy=dict(distributions=dict(float=dict(type='beta')),
          network = network_spec),
      batch_size = 32,
      memory=10000)
  ```
  The above code generates the following error message:
  
  ```
  Traceback (most recent call last):
  
    File "F:\MoneyCodes\TensorTrade\RL_strat_PPO.py", line 180, in <module>
      tsfc_agent = Agent.create(
  
    File "E:\Anaconda\envs\RL_Trading\lib\site-packages\tensorforce\agents\agent.py", line 131, in create
      return Agent.create(agent=agent, environment=environment, **kwargs)
  
    File "E:\Anaconda\envs\RL_Trading\lib\site-packages\tensorforce\agents\agent.py", line 98, in create
      agent = agent(**kwargs)
  
    File "E:\Anaconda\envs\RL_Trading\lib\site-packages\tensorforce\agents\ppo.py", line 249, in __init__
      super().__init__(
  
  TypeError: __init__() got multiple values for keyword argument 'policy'
  ```

- I found some parallelization part of the TensorforceModel, how does it work? Config `remote ` when creating the environment? For the first option you mention, do you mean I can use multiprocessing in python at each step/episode? Then how to deal with the memory? It looks like there may be some synchronous/asynchronous issues for the training. I found the following feature in the documentation:
  ```
  Runner(
      agent='benchmarks/configs/ppo1.json', environment='CartPole-v1',
      num_parallel=4
  )
  runner.run(num_episodes=100, batch_agent_calls=True)
  ```
  Will this enable parallel functionality? My environment has been already registered in gym so that the parallel is possible for it? It actually uses historical data to build the states. Once the environment `step(action)`, the data is changed. So should I make the data constant and let the environment retrieve them without chaning them?

- For the second option you suggested, what did you mean by "write your environment code in a vectorized way"? Is that equivalent to the synchronous case(the first option)?
- Right now my plan is only "the environment signal which space is required" where the agent doesn't need to choose tasks.
In the doc, how does the following action masking feature work? It seems that it enables action masking by changing the states, so should I change the state every step? Is masking for `multiple action components` available with this feature?

**Comment by AlexKuhnle** [comment]
- Right, but there the problem was that for PPO the `policy` argument is not available. You can only specify the `network` argument, so instead of `policy=dict(...)` simply specify `network=network_spec`. I see now where the confusion is coming from though... the docs are misleading when they say "others – See the Tensorforce agent documentation.". I'll improve that.
- Check out [this example script](https://github.com/tensorforce/tensorforce/blob/master/examples/parallelization.py). For this, you don't need to change anything in the environment implementation, it will just manage multiple env replicas in parallel. Whether it improves performance depends on the environment and hardware available, of course...
- "Vectorized environment" is a bit more difficult and requires env implementation changes (and may not be possible). Might be difficult to do that.
- Action masking right now is not possible for action components, just for individual actions in a discrete `int` action space (component). And yes, you pass the mask at every timestep, which can change at every time. I need to check whether it would be possible easily to integrate action component masking -- it's definitely an interesting feature.

**Comment by CycloneMAO** [comment]
- Yeah passing `network `to the creator is OK since the `network `won't be passed to `super().__init__()` twice as the `policy `will, if specify one.
- The multiprocessing part is very impressing. The only thing I need to confirm is whether it uses completely independent memories for each process. The environment I use will be built upon some variables I create in the main process. Every time the environments update, they will be updated. Therefore, I may need all the processes have the same replica of those variables which are independent during the parallelizaion. If it's not the case, may I save all the variables (actually static for each environment instance) and read them into the memory of each sub-process during initialization of each environment? Will this work with the parallelization functionality?
- I found that many paper use action masking by replace the values for logits(which correspond to the invalid actions) with -inf, then the probability of those actions become zero as well as their gradient(both gradient for probits and log(probits), considering vanilla PG and PPO, respectively). Is that the way TensorforceAgents handle it? But right now considering to "mask" action spaces, the whole process is different. I suppose that doing this is more like masking agents: at each step, some of the agents receive advantage/return and update themselvs while the other remain unchanged. I think it can be done in a multi-agent scheme. Is it similar to the training process in Double DQN?

**Comment by AlexKuhnle** [comment]
- The `multiprocessing` parallelization works naively "as you would expect", so indeed an independent instance of the environment is created in each process. For the problem you describe, I would suggest putting as much as possible into the constructor and/or make it arguments to the environment. So you could for instance specify the environment as follows:
```
arg1 = object()
arg2 = 'abc'
runner = Runner(environment=dict(environment=MyCustomEnv, arg1=arg1, arg2=arg2), ...)
```

- Yes, action masking is done as you describe in Tensorforce. And yes, action space masking may need to be implemented differently, I need to look into it. What's the relation to DoubleDQN? I don't see multi-agent / action masking there?

**Comment by CycloneMAO** [comment]
- In your example, will `arg1=object()` be independent across different paralleled environments? 
- I found the original paper says the Double Q-learning will update the two networks via switching their roles while Double DQN uses a target instead(updates periodically as a delayed copy of the main network). The former will switch the gradient descent process of the two networks every step(or every 2, 3, 4 steps), like the action space masking I described; the latter is just the commonly used DQN now(commonly, is that right?).

**Comment by AlexKuhnle** [comment]
- `arg1` is passed as argument, so will be the same across all environments. Straightforward if this is a primitive datatype like a string, I'm not sure how it works for general "stateful" objects. Best to just try it out?
- Double Q-learning = Double DQN, for all I know. And there is no gradient descent switching and masking happening here, DDQN and DQN both update the Q-network via gradient descent, and maintain a separate "delayed" copy of the Q-network, the target network. You may have mis-interpreted what they do in the paper, or there is a variant of DQN that I don't know. :-)

**Comment by CycloneMAO** [comment]
- As you said, it needs to be justified
- In the paper for DDQN(van Hasselt, Guez and Silver, 2015), they mentioned Double Q-learning(van Hasselt, 2010),  where the switching between two networks for gradient descent is proposed as following:
![image](https://user-images.githubusercontent.com/55273625/120091074-25b7d280-c13a-11eb-9984-84ff3c17ffae.png)
But they replace the switching with a delayed network while remaining the core for "Double". I think a delay version works better than the switching operation in applications so that they modified the original algorithm in Double Q-learning.

**Comment by AlexKuhnle** [comment]
Sorry for not responding. I see what you mean now, it is indeed a bit like "masking", in some way. I haven't looked at the old double QL paper. And sorry, still no updates for action component masking, but I hope to soon get to it.
