### ISSUE TITLE
max_episode_timesteps

### ISSUE THREAD

**Issue by LarsHadidi** [tensorforce/tensorforce#796]
Is it necessary to set the `max_episode_timesteps` parameter ? 

Think a gridworld of size 100x100. One of the cells is terminal. If the agent performs a random walk, it's difficult to estimate the amount of actions it may need to find the terminal cell.

Another agent might possibly live in an environment which never terminates, no finite horizon will be defined for the agent's sequence of actions.

We are currently running a simulation which asks a set of DQN-Agents in each iteration for their decisions and tells them their respective rewards.

What'd be the easiest configuration for a deep reinforcement learner without a terminal state ?

**Comment by LarsHadidi** [comment]
A simple setup, one agent, three actions and a 3x1 state space over the domain of floats, results in a TensorFlow-Error:

```



STATE_SPACE:      {'type': 'float', 'shape': (3, 1), 'min_value': 0, 'max_value': 1}
ACTION_SPACE:     TensorSpec(type=int, shape=(), num_values=3)

ACT:      Agent-0
REWARD:   Agent-0

ACT:      Agent-0
REWARD:   Agent-0
Failed to reward agent

AGENT: DeepQNetwork {'spec': OrderedDict([('agent', 'dqn'), ('states', {'type': 'float', 'shape': (3, 1), 'min_value': 0, 'max_value': 1}), ('actions', {'type': 'int', 'num_values': 3}), ('memory', 1000000), ('batch_size', 1), ('max_episode_timesteps', None), ('network', 'auto'), ('update_frequency', 'batch_size'), ('start_updating', None), ('learning_rate', 0.001), ('huber_loss', None), ('horizon', 1), ('discount', 0.99), ('predict_terminal_values', False), ('target_update_weight', 1.0), ('target_sync_frequency', 1), ('state_preprocessing', 'linear_normalization'), ('reward_preprocessing', None), ('exploration', 0.0), ('variable_noise', 0.0), ('l2_regularization', 0.0), ('entropy_regularization', 0.0), ('parallel_interactions', 1), ('config', None), ('saver', None), ('summarizer', None), ('recorder', None)]), 'create': <function overwrite_staticmethod.<locals>.overwritten at 0x000002E9DB7957B8>, 'load': <function overwrite_staticmethod.<locals>.overwritten at 0x000002E9DB795840>, 'config': <tensorforce.core.config.TensorforceConfig object at 0x000002E9DB794630>, 'is_initialized': True, '_is_agent': True, 'states_spec': TensorsSpec(SINGLETON=TensorSpec(type=float, shape=(3, 1), min_value=0.0, max_value=1.0)), 'actions_spec': TensorsSpec(SINGLETON=TensorSpec(type=int, shape=(), num_values=3)), 'max_episode_timesteps': None, 'parallel_interactions': 1, 'internals_spec': TensorsSpec(policy=TensorsSpec(), baseline=TensorsSpec()), 'terminal_spec': TensorSpec(type=int, shape=(), num_values=3), 'reward_spec': TensorSpec(type=float, shape=()), 'parallel_spec': TensorSpec(type=int, shape=(), num_values=1), 'recorder': None, 'model': <tensorforce.core.models.tensorforce.TensorforceModel object at 0x000002E9DB7947F0>, 'timestep_counter': array([2], dtype=int64), 'timestep_completed': array([ True]), 'auxiliaries_spec': TensorsSpec(SINGLETON=TensorsSpec(mask=TensorSpec(type=bool, shape=(3,)))), 'deterministic_spec': TensorSpec(type=bool, shape=()), 'terminal_buffer': [[]], 'reward_buffer': [[]], 'timesteps': 2, 'episodes': 0, 'updates': 0}
STATE: [[1.], [1.], [1.]]
REWARD: 0.666667

assertion failed: [Condition x >= y did not hold element-wise:] [x (memory/Maximum:0) = ] [0] [y (memory/Const:0) = ] [1]
	 [[{{node agent/StatefulPartitionedCall/agent/cond_1/then/_296/agent/cond_1/StatefulPartitionedCall/agent/StatefulPartitionedCall/memory/assert_greater_equal/Assert/AssertGuard/else/_991/memory/assert_greater_equal/Assert/AssertGuard/Assert}}]] [Op:__inference_observe_4769]
Function call stack:
observe



```


The agent's *initialization* reads:
```python
agents[id] = Agent.create(agent='dqn', states=self.stateSpace, actions=dict(type='int', num_values=request.stationCount),
                          batch_size=1, memory=1000000)
```

**Comment by AlexKuhnle** [comment]
Thanks, I will look into that over the next days.

**Comment by AlexKuhnle** [comment]
Hi @LarsHadidi,

I've just tried to run a DQN agent with no `max_episode_timesteps`, and it seems to work fine:

```python
runner = Runner(
    agent=dict(agent='dqn', memory=100, batch_size=1),
    environment='CartPole'
)

# Check max_episode_timesteps is indeed None
print(runner.environments[0].max_episode_timesteps())
print(runner.agent.max_episode_timesteps)

runner.run(num_episodes=1000)
runner.close()
```

So the problem is not actually the missing `max_episode_timesteps` value. Next I thought it might be due to a situation where an episode has more timesteps than the memory capacity:

```python
class MyEnv(Environment):

    def __init__(self):
        super().__init__()

    def states(self):
        return dict(type=int, shape=(), num_values=3)

    def actions(self):
        return dict(type=int, shape=(), num_values=3)

    def reset(self):
        self.timestep = 0
        return np.random.randint(3)

    def execute(self, actions):
        self.timestep += 1
        # Terminal after 100 timesteps
        if self.timestep > 100:
            return np.random.randint(3), True, 0.0
        else:
            return np.random.randint(3), False, 0.0

# Memory capacity of 10 timesteps
runner = Runner(
    agent=dict(agent='dqn', memory=10, batch_size=1),
    environment=MyEnv
)

# Check max_episode_timesteps is indeed None
print(runner.environments[0].max_episode_timesteps())
print(runner.agent.max_episode_timesteps)

runner.run(num_episodes=100)
runner.close()
```

However, this script runs fine as well. Are you using the `Runner` utility, or could it be that there is something wrong in your custom agent-env loop? Could you try your script, but replace the environment with e.g. `CartPole` or the `MyEnv` I posted above. Otherwise I'm not sure what the difference might be.

**Comment by LarsHadidi** [comment]
Hello @AlexKuhnle 

sure I can post the simplified code of the loop we use:

```python
 for idx in range(10):
        print("Episode", idx)
        action = agent.act(states=np.random.random_sample(stateSpace['shape']))
        print("Selected action", action)
        agent.observe(reward=np.random.random_sample())
```

I have just tested the code from above, and interestingly enough, it raises exaclty that previously mentioned TensorFlow-Error:

```
Python 3.7.0 [MSC v.1912 64 bit (AMD64)] on win32
>>>
None
None
Episodes:   0%|                               | 0/100 [00:00, reward=0.00, ts/ep=0, sec/ep=0.00, ms/ts=0.0, agent=0.0%]C:\Users\user\.conda\envs\swarm\lib\site-packages\tensorflow\python\framework\indexed_slices.py:437: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("policy_optimizer/StatefulPartitionedCall_1:2", shape=(None,), dtype=int32), values=Tensor("policy_optimizer/StatefulPartitionedCall_1:1", shape=(None, 64), dtype=float32), dense_shape=Tensor("policy_optimizer/StatefulPartitionedCall_1:3", shape=(2,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "shape. This may consume a large amount of memory." % value)
Traceback (most recent call last):
  File "tester.py", line 38, in <module>
    runner.run(num_episodes=100)
  File "C:\Users\user\.conda\envs\swarm\lib\site-packages\tensorforce\execution\runner.py", line 634, in run
    self.handle_observe(parallel=n)
  File "C:\Users\user\.conda\envs\swarm\lib\site-packages\tensorforce\execution\runner.py", line 757, in handle_observe
    terminal=self.terminals[parallel], reward=self.rewards[parallel], parallel=parallel
  File "C:\Users\user\.conda\envs\swarm\lib\site-packages\tensorforce\agents\agent.py", line 540, in observe
    terminal=terminal_tensor, reward=reward_tensor, parallel=parallel_tensor
  File "C:\Users\user\.conda\envs\swarm\lib\site-packages\tensorforce\core\module.py", line 136, in decorated
    output_args = function_graphs[str(graph_params)](*graph_args)
  File "C:\Users\user\.conda\envs\swarm\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\user\.conda\envs\swarm\lib\site-packages\tensorflow\python\eager\def_function.py", line 862, in _call
    results = self._stateful_fn(*args, **kwds)
  File "C:\Users\user\.conda\envs\swarm\lib\site-packages\tensorflow\python\eager\function.py", line 2943, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "C:\Users\user\.conda\envs\swarm\lib\site-packages\tensorflow\python\eager\function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\Users\user\.conda\envs\swarm\lib\site-packages\tensorflow\python\eager\function.py", line 560, in call
    ctx=ctx)
  File "C:\Users\user\.conda\envs\swarm\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  assertion failed: [Condition x >= y did not hold element-wise:] [x (memory/Maximum:0) = ] [0] [y (memory/Const:0) = ] [1]
         [[{{node agent/StatefulPartitionedCall/agent/cond_1/then/_296/agent/cond_1/StatefulPartitionedCall/agent/StatefulPartitionedCall/memory/assert_greater_equal/Assert/AssertGuard/else/_988/memory/assert_greater_equal/Assert/AssertGuard/Assert}}]] [Op:__inference_observe_4626]

Function call stack:
observe
```

The dev environment is configured via conda
```yml
name: swarm
dependencies:
  - python == 3.7
  - pip
  - pip:
      - protobuf
      - grpcio
      - grpcio-tools
      - numpy
      - tensorforce
```

and contains effectively the following packages after all dependencies are resolved:
```
absl-py                   0.12.0                   pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
cachetools                4.2.2                    pypi_0    pypi
certifi                   2020.12.5        py37haa95532_0
chardet                   4.0.0                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
google-auth               1.30.0                   pypi_0    pypi
google-auth-oauthlib      0.4.4                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.37.1                   pypi_0    pypi
grpcio-tools              1.37.1                   pypi_0    pypi
gym                       0.18.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      2.10                     pypi_0    pypi
importlib-metadata        4.0.1                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
matplotlib                3.4.2                    pypi_0    pypi
msgpack                   1.0.2                    pypi_0    pypi
msgpack-numpy             0.4.7.1                  pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
opt-einsum                3.3.0                    pypi_0    pypi
pillow                    7.2.0                    pypi_0    pypi
pip                       21.0.1           py37haa95532_0
protobuf                  3.16.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pyglet                    1.5.0                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.7.0                hea74fb7_0
python-dateutil           2.8.1                    pypi_0    pypi
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
scipy                     1.6.3                    pypi_0    pypi
setuptools                52.0.0           py37haa95532_0
six                       1.15.0                   pypi_0    pypi
tensorboard               2.5.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.4.1                    pypi_0    pypi
tensorflow-estimator      2.4.0                    pypi_0    pypi
tensorforce               0.6.3                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tqdm                      4.60.0                   pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.4                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2                      py37_0
wrapt                     1.12.1                   pypi_0    pypi
zipp                      3.4.1                    pypi_0    pypi
```

**Comment by AlexKuhnle** [comment]
That is very weird... which of the above code, out of interest? And could you try updating to the Github master version of Tensorforce and re-try it? Just to make sure there hasn't be a fix related to this more recently -- I can't think of anything, but better to double-check.

**Comment by LarsHadidi** [comment]
All right, @AlexKuhnle
I have just created a fresh conda env for Python 3.7 and installed tensorforce via pip, latest stable version.
Copied the code from your [comment-850822315](https://github.com/tensorforce/tensorforce/issues/796#issuecomment-850822315), preceeded by a 
```python
from tensorforce import *
import numpy as np
```
and ran it. 

And there it comes
`tensorflow.python.framework.errors_impl.InvalidArgumentError:  assertion failed: [Condition x >= y did not hold element-wise:] [x (memory/Maximum:0) = ] [0] [y (memory/Const:0) = ] [1]`

Our new friend, the TensorFlow-Error.

So I created another conda env, Python 3.8

Here is the command history:
```sh
conda create -n sandbox python=3.7
conda activate sandbox
pip install tensorforce
python file.py
```

I will it with another Python version.

**Comment by LarsHadidi** [comment]
Same with Python 3.6

**Comment by LarsHadidi** [comment]
Hello @AlexKuhnle 

I have switched to Python 3.9 and installed from source `pip install git+https://github.com/tensorforce/tensorforce.git`

¯\_(ツ)_/¯  now IT works

**Comment by AlexKuhnle** [comment]
Hmm, okay, then I guess something must have changed recently -- I should fix a new version soon. I very much assume it's not because of the Python version... :-)

Assume this is solved then?

**Comment by LarsHadidi** [comment]
Maybe the pip inside conda env took a dated version of TensorForce, or some other changes happened.
I thank you for your patience and support @AlexKuhnle and for the great work you do with this library !
Also thanks to @thauptmann trying different ways to run TensorForce and providing me with the feedback.
Looking forward on building with the TensorForce communiy.

Issue solved.

**Comment by AlexKuhnle** [comment]
Great, thanks. Will fix another pip version over the next days.

**Comment by madpower2000** [comment]
What about PPO?
When I run:
`agent = Agent.create( 
    agent = 'ppo', 
    environment = environment, 
    batch_size = 10, 
    learning_rate = 1e-3, 
)`

got error `TypeError: __init__() missing 1 required positional argument: 'max_episode_timesteps'`
if not explicitly specify max_episode_timesteps in the environment...

**Comment by AlexKuhnle** [comment]
PPO as policy gradient algorithm is episode-based, meaning it requires an entire episode to compute the episode return. Consequently, PPO expects `max_episode_timesteps` to be specified.

It is not too difficult to minimally modify the [Tensorforce-agent-based PPO config](https://github.com/tensorforce/tensorforce/blob/master/benchmarks/configs/ppo_tensorforce.json) to make it more like the [DQN config](https://github.com/tensorforce/tensorforce/blob/master/benchmarks/configs/dqn_tensorforce.json) with respect to its in-/dependence on full episodes, if you want to look into that. The main points are: `update['unit'] = 'episodes'` and `reward_estimation['horizon'] = 'episode'`. The former can be changed without problems (but `batch_size` and `frequency` need to be adapted accordingly), for the latter I would experiment with numbers between 10 and 100 (at some point the contribution of the remainder in the discounted sum becomes very small, so can be "cut off").

**Comment by madpower2000** [comment]
When I used json configuration files provided by you above, 
```
agent = Agent.create(
    agent = 'configs/ppo.json',  
    environment = environment, 
)
```
both for dqn and ppo I’ve got next error:
`TypeError: __init__() got an unexpected keyword argument 'single_output'`
(my tensorforce version is 0.6.3)

**Comment by AlexKuhnle** [comment]
Yes, you're mixing the most recent Github config with the latest pip version, which are not perfectly compatible since there have been changes in the meantime. I will fix a new pip version now.

**Comment by madpower2000** [comment]
After updating **tensorforce** to the latest github version, I’ve got next error, when trying to use provided _dqn_tensorforce.json_ config file:
`python run.py --agent benchmarks/configs/dqn_tensorforce.json --environment gym --level CartPole-v1 --episodes 100 --repeat 10 --path benchmarks/gym-cartpole/dqn`

`TypeError: __init__() got an unexpected keyword argument 'learning_rate'`

P.S. _ppo_tensorforce.json_ works fine...

**Comment by AlexKuhnle** [comment]
Oh, didn't realise that, I fixed that now.
