### ISSUE TITLE
Error when using DDQN and horizon = 5

### ISSUE THREAD

**Issue by Zebin-Li** [tensorforce/tensorforce#806]
To whom it may concern,

I am exploring Double DQN and the parameters used are:
   "batch_size": [10],
    "memory": [500],
    "learning_rate": [0.001],
    "horizon":[5],
    "discount": [0.98],
    "decay":[0.85]}
"decay" is for reward preprocessing.
However, I met an error:

> Traceback (most recent call last):
  File "C:/Users/zebinli/Box/Zebin Li LAB PC/research projects/active learning with RL/PPO parameters 0604 - Copy - Copy.py", line 427, in <module>
    agent.observe(terminal=terminal, reward=reward)
  File "C:\Users\zebinli\Box\Zebin Li LAB PC\research projects\active learning with RL\venv\lib\site-packages\tensorforce\agents\agent.py", line 557, in observe
    terminal=terminal_tensor, reward=reward_tensor, parallel=parallel_tensor
  File "C:\Users\zebinli\Box\Zebin Li LAB PC\research projects\active learning with RL\venv\lib\site-packages\tensorforce\core\module.py", line 136, in decorated
    output_args = function_graphs[str(graph_params)](*graph_args)
  File "C:\Users\zebinli\Box\Zebin Li LAB PC\research projects\active learning with RL\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\zebinli\Box\Zebin Li LAB PC\research projects\active learning with RL\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 924, in _call
    results = self._stateful_fn(*args, **kwds)
  File "C:\Users\zebinli\Box\Zebin Li LAB PC\research projects\active learning with RL\venv\lib\site-packages\tensorflow\python\eager\function.py", line 3024, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "C:\Users\zebinli\Box\Zebin Li LAB PC\research projects\active learning with RL\venv\lib\site-packages\tensorflow\python\eager\function.py", line 1961, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\Users\zebinli\Box\Zebin Li LAB PC\research projects\active learning with RL\venv\lib\site-packages\tensorflow\python\eager\function.py", line 596, in call
    ctx=ctx)
  File "C:\Users\zebinli\Box\Zebin Li LAB PC\research projects\active learning with RL\venv\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  assertion failed: [Condition x >= y did not hold element-wise:] [x (memory/Maximum:0) = ] [0] [y (memory/Const:0) = ] [1]
	 [[{{node agent/StatefulPartitionedCall/agent/cond_1/then/_307/agent/StatefulPartitionedCall/memory/StatefulPartitionedCall/memory/assert_greater_equal/Assert/AssertGuard/else/_1052/memory/assert_greater_equal/Assert/AssertGuard/Assert}}]] [Op:__inference_observe_4726]
Function call stack:
observe

But if I changed "horizon" to 1 and 2, then the error disappeared. But if use 3 and 4, the error happened again. So I am not sure why it does not work if use larger values for "horizon". Thank you!

Best,
Zebin Li

**Comment by AlexKuhnle** [comment]
Hi @Zebin-Li,

This was due to a bug, but should be fixed with the latest commit. Could you try again?

**Comment by AlexKuhnle** [comment]
Any updates here?

**Comment by Zebin-Li** [comment]
Sorry for the late reply. I haven't tried it yet and may try it in a few days!

**Comment by AlexKuhnle** [comment]
Any updates on this?

**Comment by Zebin-Li** [comment]
Hi @AlexKuhnle,

I am so sorry about the late reply. Currently, I am not working on the project regarding this issue, and I will give you the feedback by this week.

Best,
Zebin Li

**Comment by Zebin-Li** [comment]
Hi @AlexKuhnle,

I think the issue is solved. I tried Horizon = 5 and 10, and the code can run. Thank you very much!

Best,
Zebin

**Comment by AlexKuhnle** [comment]
Cool, thanks for checking, closing this then.
