### ISSUE TITLE
action masking in gym environment

### ISSUE THREAD

**Issue by zirenxiao** [tensorforce/tensorforce#810]
Hi,

I'm using gym environment and want to mask some invalid actions, but it goes error like this
```
Traceback (most recent call last):
  File "C:/Users/***/OneDrive - alumni.unimelb.edu.au/PyCharmProject/mssd-gym/tensorforce_example.py", line 35, in <module>
    states = environment.reset()
  File "C:\Users\***\PycharmProjects\venv\lib\site-packages\tensorforce\environments\environment.py", line 508, in reset
    states = self._environment.reset()
  File "C:\Users\***\PycharmProjects\venv\lib\site-packages\tensorforce\environments\openai_gym.py", line 232, in reset
    states = OpenAIGym.flatten_state(state=states, states_spec=self.states_spec)
  File "C:\Users\***\PycharmProjects\venv\lib\site-packages\tensorforce\environments\openai_gym.py", line 417, in flatten_state
    assert spec is not None
AssertionError
```
The input state is
```
{'state': array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'action_mask': [True, False, True, True]}
```
where the action and observation space are
```
self.action_space = gym.spaces.Discrete(4)  # up, down, left, right
self.observation_space = gym.spaces.Box(low=0, high=4, shape=(10, 22), dtype=np.int)
```
Has this feature implemented?

**Comment by AlexKuhnle** [comment]
Action masking certainly works, but I think it might not be compatible with the Gym interface, i.e., adding state components like `action_mask` which are not part of the `observation_space` doesn't work. This is not a problem on your side (`action_mask` should not be specified in the `observation_space`), I need to check whether this can be fixed in the interface. It should certainly work if you add the `action_mask` component "outside" the Gym environment, before the env state is passed to the agent.

**Comment by AlexKuhnle** [comment]
Could you try again whether your implementation works now with the latest Github version of Tensorforce? I tried to improve it.

**Comment by AlexKuhnle** [comment]
Any updates on this?
