### ISSUE TITLE
Error when using (manual) parallel training 

### ISSUE THREAD

**Issue by berse2212** [tensorforce/tensorforce#811]
I am currently trying around to use the parallel execution to use with selfplay. Sadly the Runner Utility does not provide a setup I could use, so I tried implementing the parallel execution on my own. After a few (around 1-5) episodes of training I am always run into an error when I call the last observe for that episode (terminal = true):

```
Exception ignored in thread started by: <bound method AgentRunner.run of <__main__.AgentRunner object at 0x7f27ae921e80>>
Traceback (most recent call last):
  File ".../parallelLearning.py", line 88, in run
    self.runLearning()
  File ".../parallelLearning", line 119, in runLearning
    self.agent.observe(terminal=terminal, reward=reward, parallel=self.parallelIndex)
  File ".../git/tensorforce/tensorforce/agents/agent.py", line 556, in observe
Exception ignored in thread started by: <bound method AgentRunner.run of <__main__.AgentRunner object at 0x7f27aeb1ff70>>
Traceback (most recent call last):
  File ".../parallelLearning.py", line 88, in run
    updated, episodes, updates = self.model.observe(
    self.runLearning()  File ".../git/tensorforce/tensorforce/core/module.py", line 136, in decorated

  File ".../parallelLearning.py", line 119, in runLearning
    self.agent.observe(terminal=terminal, reward=reward, parallel=self.parallelIndex)
  File ".../git/tensorforce/tensorforce/agents/agent.py", line 556, in observe
    updated, episodes, updates = self.model.observe(
  File ".../git/tensorforce/tensorforce/core/module.py", line 136, in decorated
    output_args = function_graphs[str(graph_params)](*graph_args)
  File ".../.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    output_args = function_graphs[str(graph_params)](*graph_args)
  File ".../.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)    result = self._call(*args, **kwds)
  File ".../.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 924, in _call

  File "....local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 924, in _call
    results = self._stateful_fn(*args, **kwds)
  File ".../.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3023, in __call__
    results = self._stateful_fn(*args, **kwds)
  File "....local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3023, in __call__
    return graph_function._call_flat(
  File ".../.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1960, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
      File ".../.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
return graph_function._call_flat(
  File ".../.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1960, in _call_flat
    outputs = execute.execute(
  File ".../.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Outer dimensions of indices and update must match. Indices shape: [40,1], updates shape:[39,45]
	 [[{{node agent/StatefulPartitionedCall/agent/cond/then/_607/agent/StatefulPartitionedCall/memory/StatefulPartitionedCall/memory/TensorScatterUpdate_1}}]] [Op:__inference_observe_27602]

Function call stack:
observe

    return self._build_call_outputs(self._inference_function.call(
  File ".../.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File ".../.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  assertion failed: [Memory consistency check.] [Condition x == y did not hold element-wise:] [x (memory/count_nonzero_1/Sum:0) = ] [6] [y (memory/add_1:0) = ] [5]
	 [[{{node agent/StatefulPartitionedCall/agent/cond/then/_607/agent/StatefulPartitionedCall/memory/StatefulPartitionedCall/memory/assert_equal_5/Assert/AssertGuard/else/_3649/memory/assert_equal_5/Assert/AssertGuard/Assert}}]] [Op:__inference_observe_27602]

Function call stack:
observe

```

I am unsure what causes it, I even tried to simplify my setup. Currently I am just using a simple ddq agent with an auto network, but also the tensorflow agent with a complex network had this problem. What am I doing wrong here?

**Comment by AlexKuhnle** [comment]
Hi @berse2212, sorry I've overlooked this issue over the last days (best to always post a reminder if no response within 2-3 days).

This looks worrying -- can you post your custom "runner" code? Also, could you run with `config=dict(eager_mode=True)` to better locate where exactly the exception is thrown?

**Comment by berse2212** [comment]
No worries. I thought you might just be busy and did not want to be impolite ;)

Anyways that's my runner:

[PyWebSocketServer.zip](https://github.com/tensorforce/tensorforce/files/6917120/PyWebSocketServer.zip)

**Comment by berse2212** [comment]
The eager_mode gives me following exception:

```
Traceback (most recent call last):
  File "/.../git/masterarbeit/PyQL/de/pyql/PyWebSocketServer.py", line 89, in run
    actions = self.agent.act(states=states, parallel=self.parallelIndex)
  File "/.../git/tensorforce/tensorforce/agents/agent.py", line 413, in act
    self.runLearning()
  File "/.../git/masterarbeit/PyQL/de/pyql/PyWebSocketServer.py", line 126, in runLearning
    return super().act(    raise error
  File "/.../git/tensorforce/tensorforce/agents/recorder.py", line 262, in act

  File "/.../git/masterarbeit/PyQL/de/pyql/PyWebSocketServer.py", line 112, in runLearning
    actions = self.agent.act(states=states, parallel=self.parallelIndex)
  File "/.../git/tensorforce/tensorforce/agents/agent.py", line 413, in act
    actions, internals = self.fn_act(
  File "/.../git/tensorforce/tensorforce/agents/agent.py", line 460, in fn_act
    return super().act(
  File "/.../git/tensorforce/tensorforce/agents/recorder.py", line 262, in act
    actions, internals = self.fn_act(
  File "/.../git/tensorforce/tensorforce/agents/agent.py", line 460, in fn_act
    actions, timesteps = self.model.act(
  File "/.../git/tensorforce/tensorforce/core/module.py", line 136, in decorated
    actions, timesteps = self.model.act(
  File "/.../git/tensorforce/tensorforce/core/module.py", line 136, in decorated
    output_args = function_graphs[str(graph_params)](*graph_args)
    output_args = function_graphs[str(graph_params)](*graph_args)
  File "/.../git/tensorforce/tensorforce/core/models/model.py", line 236, in __exit__
  File "/.../git/tensorforce/tensorforce/core/models/model.py", line 238, in __exit__
    assert popped is self
    self.device.__exit__(etype, exception, traceback)AssertionError: 
  File "/.../.local/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 1808, in __exit__
```

**Comment by AlexKuhnle** [comment]
Could you also post your agent config? I can't see anything obvious in your core loop. Out of interest, in what sense does your setup differ from what the runner provides -- could you give some detail?

**Comment by berse2212** [comment]
I started to simplify the config since I also suspected this to be the problem. This is the least complex version I still got the error for (read: I got the error for every version but this is the simplest):

```    
    exploration = dict(
        type='decaying',
        decay='linear',
        unit='timesteps',
        num_steps=1000,
        initial_value=1.0,
        final_value=0.1
    )

    agent = dict(
        agent='ddqn',
        # environment=environment1,
        batch_size=128,
        network='auto',
        exploration=exploration,
        memory=150000,
        predict_terminal_values=False,
        start_updating=128,
        learning_rate=0.001,
        update_frequency=0.1,
        target_sync_frequency=5,
        state_preprocessing=None,
        parallel_interactions=parallel_interactions
    )
```

I started to write the runner because the one provided seems to behave weird when reaching the last episode. E.g. max episode is 100. The two parallel Agents execute episode 99 and 100. Sometimes there was startet an episode 101. Since those to agents play themselves episode 101 had no opponent to go against and training was stuck. 

Furthermore now my runner is externally controlled. Meaning Websocket calls are made when to start an episode, not the other way round.

One additional note: I am not reusing the environments and reset them for each episode. I thought since there is no strict link between the environment and the agent I could just be lazy and create a new environment for every episode. If that might cause the problem I could probably change it thought.

**Comment by berse2212** [comment]
One more info: the runner works perfectly fine, when used with just one agent.

**Comment by AlexKuhnle** [comment]
Config is definitely fine. I'm wondering now whether it could be the use of `async` in your code -- why do you need that? Couldn't that cause a situation where the agent is called twice at the same time (and hence internal buffering gets messed up)? How in general are the inputs coming from the "two" agents coordinated in the environment / the `Environment` objects? Presumably there are two `Environment` objects which represent the same underlying environment, but specific to each agent's perspective?

**Comment by berse2212** [comment]
I use async because the environment is controlled externally. Therefore I need to wait for each step / the reset. What exactly do you mean by "the agent is called twice at the same time"? Yes there are two environments for each agent's perspective. The external environment waits for each agent to make his action choice and then makes a step. As mentioned above, the agents wait for that to happen and then observe the result and choose a new step.

**Comment by AlexKuhnle** [comment]
Okay. What I meant was whether it's possible that an agent is queried for another action before the previous action has been returned and performed, but it sounds like, by design, this doesn't happen. Is it possible that agent parallel=0 is queried simultaneously to agent parallel=1? Oh, and are you using the latest Github or pip version?

**Comment by berse2212** [comment]
Yes it is possible that agent parallel=0 is queried  simultaneously to agent parallel=1. In fact this is usually the case since both agents are supposed to choose their actions simultaneously before each step (aside from a few edgecases). Is this a problem? 

I should be using the latest git version if there was no update since I started this topic.

**Comment by AlexKuhnle** [comment]
I think it might -- could you try it out by somehow making sure the queries happen in sequence?

**Comment by berse2212** [comment]
That worked! Thanks! I always just had the observe in sequence since the error happend there - that was an easy fix
