### ISSUE TITLE
Having "Tensor had NaN values"

### ISSUE THREAD

**Issue by mikael-thiago** [tensorforce/tensorforce#839]
Hi, this is one of my first times writing doubts in github, if i made some mistake, let me know it, please. And, congrats from all the work on this bib.

I'm trying to train an dqn agent and i'm getting a "Tensor had NaN values" after some episodes, and i'm understanding why. I made something wrong or that is something internal?
I'm using a gym environment, taking images from input. The network consists of 3 conv layers and 1 fc layer.

My code:
```
from tensorforce.agents import DQNAgent
from tensorforce.execution import Runner
from tensorforce.environments import Environment

envName = 'Pong'
envVersion = 'v5'

env = Environment.create(
    environment='gym',
    level='ALE/'+envName+'-' + envVersion,
    visualize=True,
    visualize_directory='./visualize/'+envName)

states_shape = env.states().get('shape')

print(states_shape)

dqn_agent = DQNAgent(
    states=env.states(),
    actions=env.actions(),
    batch_size=4,
    memory=300,
    network=[
        dict(type='conv2d', size=32, window=8, stride=4, activation='relu'),
        dict(type='conv2d', size=64, window=4, stride=2, activation='relu'),
        dict(type='conv2d', size=64, window=3, stride=1, activation='relu'),
        dict(type='flatten'),
        dict(type='dense', size=512, activation='relu'),
        dict(type='linear', size=env.actions().get('num_values')),
    ],
    state_preprocessing=[
        dict(type='image', height=84, width=84, grayscale=True)
    ],
    learning_rate=1e-2,
)

runner = Runner(
    agent=dqn_agent,
    environment=env
)

runner.run(num_episodes=1, evaluation=True)

for i in range(10000000):
    runner.run(num_episodes=10)
    dqn_agent.save(directory='tensorforce/'+envName, format='hdf5')
    runner.run(num_episodes=1, evaluation=True)
    runner.close()

```

Stack trace:
```
Episodes:  10%|▍   | 1/10 [00:34, return=-21.00, ts/ep=613, sec/ep=34.97, ms/ts=57.0, agent=96.0%]Traceback (most recent call last):
  File "c:\Users\mikae\Desktop\gym\tf-agent.py", line 49, in <module>
    runner.run(num_episodes=10)
  File "C:\Users\mikae\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorforce\execution\runner.py", line 652, in run
    self.handle_observe(parallel=n)
  File "C:\Users\mikae\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorforce\execution\runner.py", line 779, in handle_observe
    updated = self.agent.observe(
  File "C:\Users\mikae\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorforce\agents\agent.py", line 558, in observe
    updated, episodes, updates = self.model.observe(
  File "C:\Users\mikae\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorforce\core\module.py", line 136, in decorated
    output_args = function_graphs[str(graph_params)](*graph_args)
  File "C:\Users\mikae\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\eager\def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\mikae\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\eager\def_function.py", line 924, in _call
    results = self._stateful_fn(*args, **kwds)
  File "C:\Users\mikae\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\eager\function.py", line 3039, in __call__
    return graph_function._call_flat(
  File "C:\Users\mikae\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\eager\function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\mikae\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\eager\function.py", line 591, in call
    outputs = execute.execute(
  File "C:\Users\mikae\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Invalid gradient: contains inf or nan. : Tensor had NaN values
         [[{{node agent/StatefulPartitionedCall/agent/cond_1/then/_321/agent/StatefulPartitionedCall/policy_optimizer/StatefulPartitionedCall/policy_optimizer/StatefulPartitionedCall/policy_optimizer/VerifyFinite/CheckNumerics}}]] [Op:__inference_observe_8544]
```

**Comment by AlexKuhnle** [comment]
Hi @mikael-thiago,

I don't know why that would happen. Could you check whether running with a lower learning rate avoids the exception? Also, after how many episodes does this happen?

Finally, a comment: You don't need this layer in your config, `dict(type='linear', size=env.actions().get('num_values')), as it will be added implicitly (so in your case there are two linear layers).

**Comment by mikael-thiago** [comment]
> Hi @mikael-thiago,
> 
> I don't know why that would happen. Could you check whether running with a lower learning rate avoids the exception? Also, after how many episodes does this happen?
> 
> Finally, a comment: You don't need this layer in your config, `dict(type='linear', size=env.actions().get('num_values')), as it will be added implicitly (so in your case there are two linear layers).

Hi, thanks, using a lower learning rate solved the problem. The issue was happening after a different number of episodes for each game (for ms pacman used to happen after 10 episodes, for pong was after 4 or 5).
Finally, thanks for the advice, i wasn't aware of the implicit linear layer.
Sorry for any english mistake and, again, congrats for the great work.

**Comment by AlexKuhnle** [comment]
No worries. Assuming this can be closed then.
