### ISSUE TITLE
Quickstart example does not run

### ISSUE THREAD

**Issue by abhaychitnis** [tensorforce/tensorforce#843]
Hi,
I am a beginner in tensorforce. I have installed tensorforce using pip. I have Windows 10 environment. I have installed Python 3.8 and Tensorflow 2.6. I did a copy and paste of the code in quickstart.py from this repository, into another file 'tensorforceExample.py' and tried to run it. I get following error.

Request your help in taking this first step !

```
C:\Deep Reinforcement Learning Hand On Code\Chapter06>python tensorforceExample.py
Traceback (most recent call last):
  File "tensorforceExample.py", line 1, in <module>
    from tensorforce import Runner
  File "C:\Python38\lib\site-packages\tensorforce\__init__.py", line 23, in <module>
    from tensorforce.environments import Environment
  File "C:\Python38\lib\site-packages\tensorforce\environments\__init__.py", line 16, in <module>
    from tensorforce.environments.environment import Environment, RemoteEnvironment
  File "C:\Python38\lib\site-packages\tensorforce\environments\environment.py", line 28, in <module>
    from tensorforce.core import TensorSpec, TensorsSpec
  File "C:\Python38\lib\site-packages\tensorforce\core\__init__.py", line 29, in <module>
    from tensorforce.core.optimizers import optimizer_modules
  File "C:\Python38\lib\site-packages\tensorforce\core\optimizers\__init__.py", line 32, in <module>
    from tensorforce.core.optimizers.tf_optimizer import TFOptimizer, tensorflow_optimizers
  File "C:\Python38\lib\site-packages\tensorforce\core\optimizers\tf_optimizer.py", line 25, in <module>
    adadelta=tf.keras.optimizers.Adadelta,
  File "C:\Python38\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "C:\Python38\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Python38\lib\site-packages\keras\__init__.py", line 25, in <module>
    from keras import models
  File "C:\Python38\lib\site-packages\keras\models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "C:\Python38\lib\site-packages\keras\metrics.py", line 26, in <module>
    from keras import activations
  File "C:\Python38\lib\site-packages\keras\activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "C:\Python38\lib\site-packages\keras\layers\__init__.py", line 23, in <module>
    from keras.engine.input_layer import Input
  File "C:\Python38\lib\site-packages\keras\engine\input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "C:\Python38\lib\site-packages\keras\engine\base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "C:\Python38\lib\site-packages\keras\mixed_precision\loss_scale_optimizer.py", line 18, in <module>
    from keras import optimizers
  File "C:\Python38\lib\site-packages\keras\optimizers.py", line 26, in <module>
    from keras.optimizer_v2 import adadelta as adadelta_v2
  File "C:\Python38\lib\site-packages\keras\optimizer_v2\adadelta.py", line 22, in <module>
    from keras.optimizer_v2 import optimizer_v2
  File "C:\Python38\lib\site-packages\keras\optimizer_v2\optimizer_v2.py", line 36, in <module>
    keras_optimizers_gauge = tf.__internal__.monitoring.BoolGauge(
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\monitoring.py", line 360, in __init__
    super(BoolGauge, self).__init__('BoolGauge', _bool_gauge_methods,
  File "C:\Python38\lib\site-packages\tensorflow\python\eager\monitoring.py", line 135, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
```

**Comment by jdnklau** [comment]
Hi abhaychitnis,
I just ran into the same error. The problem is, that you have two different keras versions installed (see [this issue as well](https://stackoverflow.com/questions/58012741/error-importing-tensorflow-alreadyexistserror-another-metric-with-the-same-nam)).

Running
```bash
pip uninstall keras
pip install keras==2.6.*
```
to ensure my keras version matches my tensorflow version (2.6.0) resolved the problem for me.

I hope this helps!

**Comment by abhaychitnis** [comment]
Thanks Jannik ! It solved the issue.
