### ISSUE TITLE
TensorforceAgent.load

### ISSUE THREAD

**Issue by ValentinGlaser** [tensorforce/tensorforce#858]
1.  **TRAINING**: I'm trying to _train an agent on multiple environments_ which slightly differ from one another. What's the way to go here?
         - use **TensorforceAgent.load** to use the same agent for all those environments
         - train the agent seperately on all those environments and ...?

2. **APPLICATION**: How can I _use my trained agent_? Do I use **TensorforceAgent.load**?
         - the application is only runned for **1 episode** because there is no training?
         - the application is runned multiple episodes and the results of the last episode are the results of the application?

**Comment by AlexKuhnle** [comment]
Hi @ValentinGlaser,

1. If all the environments share the same state and action space specification, it can make sense to train the same agent on all environments. In that case you can just run one episode with the first environment, one with the second, etc -- no need for saving and loading the agent in between. However, if the state and action space are different, then there is no way of sharing the agent, so you have to train one agent each separately.
2. Yes, you can save and then load your agent if you want to use it later / somewhere else for inference. I don't understand the sub-questions?

**Comment by ValentinGlaser** [comment]
Thanks! 

2. I want to train my agent on different configurations of the environment and test/use the agent on another. So I just use the agent for 1 episode on my test environment, right?

**Comment by AlexKuhnle** [comment]
I see, yes, although it probably makes sense to run it for a few independent episodes to see "average" performance.

**Comment by ValentinGlaser** [comment]
I want to load and save an agent. I'm using:
```
agent = Agent.load(
            directory='{cwd}/agent_original'.format(cwd=cwd),
            format='checkpoint', 
            environment=env_RL,
            saver=dict(directory='agent_new', frequency=5)
            )
```
does this work?
I want to load the trained agent from the folder `agent_original` and save the adapted new agent in the folder `agent_new`.
Or do I have to overrite the files in the folder `agent_original`?

**Comment by ValentinGlaser** [comment]
I get the following error while loading without `saver`. Why can't the agent be loaded?

```
Traceback (most recent call last):
  File "Bmy_file.py", line 55, in <module>
    agent = Agent.load(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 208, in load
    agent = Agent.create(agent=agent, environment=environment, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 112, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 124, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 98, in create
    agent = agent(**kwargs)
TypeError: __init__() missing 4 required positional arguments: 'update', 'optimizer', 'objective', and 'reward_estimation'
```

I load the agent as following:
```
agent = Agent.load(
            directory='{cwd}/agent_original'.format(cwd=cwd),
            filename='checkpoint',
            format='checkpoint', 
            environment=env_RL,
            )
```

**Comment by AlexKuhnle** [comment]
If I understand correctly, the problem is that with `saver` specified when using `Agent.load()`, that "overwrites" the `directory` argument?

The way you describe certainly works, yes. If checkpoints have the timestep/episode/update iteration attached, then simply continuing with the `saver` specified implicitly by the loaded agent is fine. Nonetheless, may check the first alternative you tried, because it would be nice if that works too (and current behavior is not intuitive).
