### ISSUE TITLE
Keras model as policy

### ISSUE THREAD

**Issue by JoForky** [tensorforce/tensorforce#868]
Hi @AlexKuhnle ,

we defined a keras model as policy in our agent as followed:

`
from re import X
import numpy as np
import tensorflow as tf
from tensorflow.keras.optimizers import SGD, Adam
import tensorforce as tfc
from tensorforce import Agent, Environment
 
class NN_Model(tf.keras.Model):
    def __init__(self):
        super().__init__()
 
        self.conv_1D_11 = tf.keras.layers.Conv1D(filters=128, kernel_size=1, activation='relu', name='Conv_1_1', input_shape=(None, 4, 4))
        self.conv_1D_12 = tf.keras.layers.Conv1D(filters=256, kernel_size=1, activation=None, name='Conv_1_2')
 
        # Pointnet Layer 2
        self.conv_1D_21 = tf.keras.layers.Conv1D(filters=512, kernel_size=1, activation='relu', name='Conv_2_1')
        self.conv_1D_22 = tf.keras.layers.Conv1D(filters=512, kernel_size=1, activation=None, name='Conv_2_2')
 
        # Dense Layers
        self.dense_1 = tf.keras.layers.Dense(units=128, activation='relu', name='MLP_1')
        self.dense_2 = tf.keras.layers.Dense(units=128, activation='relu', name='MLP_2')
        self.dense_3 = tf.keras.layers.Dense(units=3, activation=None, name='MLP_3')
 
    def call(self, inputs):
        #inputs = tf.keras.Input(shape=(128, 3), name='Encoder_Input')
        x = self.conv_1D_11(inputs)
        features = self.conv_1D_12(x)
        features_global = tf.reduce_max(features, axis=1, keepdims=True, name='MaxPool_1')
        # features_global = tf.keras.layers.MaxPool1D(pool_size=n_points, name='MaxPool_1')(features)
 
        # Assembling features
        features = tf.concat([features, tf.tile(features_global, [1, tf.shape(inputs)[1], 1])], axis=2)
        # features = tf.keras.layers.concatenate([features, tf.tile(features_global, [1, tf.shape(inputs)[1], 1])], axis=2,name='concat')
 
        # Pointnet Layer 2
        x = self.conv_1D_21(features)
        x = self.conv_1D_22(x)
        # latent = tf.keras.layers.MaxPool1D(pool_size=n_points, name='MaxPool_2')(x)  # Latent Dim
        x = tf.reduce_max(x, axis=1, name='MaxPool_2')
        decoder_inputs = tf.keras.layers.Flatten()(x)
 
        # Decoder
        #decoder_inputs = tf.keras.Input(shape=(512,), name='Decoder_Input')
        x = self.dense_1(decoder_inputs)
        x = self.dense_2(x)
        x = self.dense_3(x)
 
        #x = tf.keras.layers.Reshape([1, 3])(x)
        return x
 
if __name__ == '__main__':
    model = NN_Model()
    opt = Adam(learning_rate=0.0001)
    model.compile(loss="mse", optimizer=opt,metrics=["accuracy"])
   
    #x_train = np.random.random(size=(4,3))
    #y_train = x_train[:,0]
    x_train = tf.random.uniform(shape=(4, 4))
    #y_train = tf.reshape(tf.reduce_sum(x_train, axis=1), shape=((200000, 1, 3)))
 
    environment = Environment.create(
    environment='gym', level='CartPole', max_episode_timesteps=500
    )
 
    agent = Agent.create(
    agent='tensorforce',
    states = dict(type='int', shape=(4,4)),
    actions = dict(type='int', num_values=4),
    memory=10000,
    update=dict(unit='timesteps', batch_size=64),
    optimizer=dict(type='adam', learning_rate=3e-4),
    policy=NN_Model,
    objective='policy_gradient',
    reward_estimation=dict(horizon=20)
    )
   
    print(agent.act(x_train))
 
    #print(x_train)
    #print(y_train)
    #model.fit(x_train, x_train, epochs=1, batch_size=4)
    #print(model.output_shape)
    #print(model.summary())
    #x_test = tf.random.uniform(shape=(2, 3, 3))
    #print(x_test)
    #print(model.predict(x_test))`

We get the error as follows:

`Traceback (most recent call last):
  File "jpk_net.py", line 80, in <module>
    print(agent.act(x_train))
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 417, in act
    deterministic=deterministic
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/agents/recorder.py", line 265, in act
    num_parallel=num_parallel
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 463, in fn_act
    states=states, auxiliaries=auxiliaries, parallel=parallel
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/core/module.py", line 136, in decorated
    output_args = function_graphs[str(graph_params)](*graph_args)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 760, in _initialize
    *args, **kwds))
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3308, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/core/module.py", line 107, in function_graph
    args = function(self, **kwargs.to_kwargs(), **params_kwargs)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/core/models/model.py", line 611, in act
    deterministic=deterministic, independent=False
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/core/module.py", line 136, in decorated
    output_args = function_graphs[str(graph_params)](*graph_args)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 760, in _initialize
    *args, **kwds))
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3308, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/core/module.py", line 107, in function_graph
    args = function(self, **kwargs.to_kwargs(), **params_kwargs)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/core/models/tensorforce.py", line 1122, in core_act
    auxiliaries=auxiliaries, deterministic=deterministic, independent=independent
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/core/module.py", line 136, in decorated
    output_args = function_graphs[str(graph_params)](*graph_args)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 760, in _initialize
    *args, **kwds))
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3308, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/core/module.py", line 107, in function_graph
    args = function(self, **kwargs.to_kwargs(), **params_kwargs)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/core/policies/parametrized_distributions.py", line 182, in act
    independent=independent
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/core/module.py", line 77, in decorated
    output_signature = self.output_signature(function=name)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/core/networks/network.py", line 92, in output_signature
    x=self.output_spec().signature(batched=True),
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/tensorforce/core/networks/keras.py", line 78, in output_spec
    output_shape = self.keras_model.compute_output_shape(input_shape=input_shape)
  File "/root/anaconda3/envs/RL_fork/lib/python3.6/site-packages/keras/engine/base_layer.py", line 793, in compute_output_shape
    'method on your layer (%s).' % self.__class__.__name__)
**NotImplementedError: Please run in eager mode or implement the `compute_output_shape` method on your layer (NN_Model).**`

As far as I recognized, keras models do not implement the compute_output_shape method, while the layers do. But as seen in the output, tensorforce seems to need this method.

How can we solve this problem?

Thanks in advance!

**Comment by Jonas-Gaebele** [comment]
Hi @AlexKuhnle,

sorry for the message again, but I thought some additional information could be useful for you.

In the meantime, I also tried soling the tests with the custom net and it went well.

So it seems like the net is not the core problem.

Hope this helps. I am convinced other people would enjoy the possibility to use a keras custom net in Tensorforce, too.

Thanks in advance!
