### ISSUE TITLE
Error running a loaded agent in multienviroment

### ISSUE THREAD

**Issue by franalcantara** [tensorforce/tensorforce#883]
@jerabaul29 @b-fg

I am running a simulation with several enviroments

`environment_base = CylinderEnvironment(simu_name = '2DCyl', do_baseline=True, continue_training=False, ENV_ID = -1, host = '')

network = [dict(type='dense', size=512), dict(type='dense', size=512)]

agent = Agent.create(
    # Agent + Environment
    agent='ppo', environment=environment_base, max_episode_timesteps=nb_actuations,
    # Network
    network=network,
    # Optimization
    batch_size=20, learning_rate=1e-3, subsampling_fraction=0.2, multi_step=25,
    # Reward estimation
    likelihood_ratio_clipping=0.2, predict_terminal_values=True,
    # Critic
    baseline=network,
    baseline_optimizer=dict(
        type='multi_step', num_steps=5,
        optimizer=dict(type='adam', learning_rate=1e-3)
    ),
    # Regularization
    entropy_regularization=0.01,
    parallel_interactions=num_servers,
    # TensorFlow
    saver=dict(directory=os.path.join(os.getcwd(), 'saver_data'), frequency=1, max_checkpoints=1),
)

#here the array of environments is defined
environments = [CylinderEnvironment(simu_name = '2DCyl', do_baseline=True, continue_training=False, ENV_ID = i, host=h) for i,h in enumerate(hostlist)] 

runner = Runner(agent=agent, environments=environments, remote='multiprocessing')

#start the episodes
runner.run(num_episodes=num_episodes, sync_episodes=False)
runner.close()

#saving all the model data in model-numpy format 
agent.save(directory=os.path.join(os.getcwd(),'model-numpy'), format='numpy', append='episodes')
agent.close()`

After saving the agent, I want to resume the simulation loading the agent:

`environment_base = CylinderEnvironment(simu_name = '2DCyl', do_baseline=False, continue_training=True, ENV_ID = -1, host = '')

# Load agent
agent = Agent.load(directory=os.path.join(os.getcwd(), 'saver_data'), format='checkpoint', environment=environment_base)

#here the array of environments is defined
environments = [CylinderEnvironment(simu_name = '2DCyl', do_baseline=False, continue_training=True, ENV_ID = i, host=h) for i,h in enumerate(hostlist)]

runner = Runner(agent=agent, environments=environments, remote='multiprocessing')

#start the episodes
runner.run(num_episodes=num_episodes, sync_episodes=False)`

But I am getting the following error inside the runner.run line:

Exception in thread Thread-{ID}:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/francisco/tensorforce/tensorforce/environments/environment.py", line 883, in finish_reset
    self._observation = (self.reset(), -1, None)
  File "/home/francisco/tensorforce/tensorforce/environments/environment.py", line 860, in reset
    states, seconds = self.receive(function='reset')
  File "/home/francisco/tensorforce/tensorforce/environments/environment.py", line 787, in receive
    raise TensorforceError(message='\n{}\n{}: {}`'.format(''.join(traceback), etype, value))
tensorforce.exception.TensorforceError: 
  File "/home/francisco/tensorforce/tensorforce/environments/environment.py", line 710, in remote
    raise TensorforceError(message="Invalid remote attribute/function access.")

<class 'tensorforce.exception.TensorforceError'>: Invalid remote attribute/function access.`

Is this error related with the settings of the agent, enviroment and runner?

**Comment by jerabaul29** [comment]
Thanks, will be exciting to hear what @AlexKuhnle will think :) . @franalcantara , one small thing: can you code highlight the code blocks, that will make it easier to read maybe? :) See: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by franalcantara** [comment]
The problem has been solved. The problem was that in the definition of the environment some attributes were being defined in the first simulation inside the self. variable. After resuming the simulation, some of this variables did not need to be defined again, and Tensorforce did not like that. To conclude, you need to define the same attributes and variables in the environment as those defined for the first run of the simulation
