### ISSUE TITLE
tensorforce.exception.TensorforceError: Invalid value for variable argument spec: TensorSpec

### ISSUE THREAD

**Issue by waynezw0618** [tensorforce/tensorforce#902]
Hello 
I am using tensorforce 0.6.0 in DRLinFluids package. I can run tutorial case in [DRLinFluild](https://github.com/venturi123/DRLinFluids) on the cluster. I slightly change the openfoam case part in [DRLinfluid](https://github.com/venturi123/DRLinFluids) from a cylinder of two jet variable to one.  then  the initialization error arise. as :

`
WARNING:root:No min_value bound specified for state.
OpenFOAM_init running time： 45.16 s
OpenFOAM_init running time： 39.83 s
OpenFOAM_init running time： 40.02 s
OpenFOAM_init running time： 40.01 s
OpenFOAM_init running time： 39.02 s
Traceback (most recent call last):
  File "DRLinFluids_cavity/launch_multiprocessing_traning_cavity.py", line 115, in <module>
    agent = Agent.create(
  File "/work/home/acsm7tkef4/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 131, in create
    return Agent.create(agent=agent, environment=environment, **kwargs)
  File "/work/home/acsm7tkef4/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 104, in create
    return Agent.create(agent=agent, environment=environment)
  File "/work/home/acsm7tkef4/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 71, in create
    agent.initialize()
  File "/work/home/acsm7tkef4/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 263, in initialize
    self.model.initialize()
  File "/work/home/acsm7tkef4/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/core/models/tensorforce.py", line 503, in
 initialize
    super().initialize()
  File "/work/home/acsm7tkef4/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/core/models/model.py", line 264, in initi
alize
    super().initialize()
  File "/work/home/acsm7tkef4/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/core/module.py", line 270, in initialize
    module.initialize()
  File "/work/home/acsm7tkef4/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/core/module.py", line 270, in initialize
    module.initialize()
  File "/work/home/acsm7tkef4/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/core/module.py", line 270, in initialize
    module.initialize()
  File "/work/home/acsm7tkef4/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/core/layers/dense.py", line 84, in initia
lize
    self.weights = self.variable(
  File "/work/home/acsm7tkef4/miniconda3/envs/py38/lib/python3.8/site-packages/tensorforce/core/module.py", line 510, in variable
    raise TensorforceError.value(
tensorforce.exception.TensorforceError: Invalid value for variable argument spec: TensorSpec(type=float, shape=(0, 1024)) underspeci
fied.`

I also made comparison for the original setup and the one I modified.

base) [acsm7tkef4@login06 acousticCavity]$  diff DRLinFluids_cavity/launch_multiprocessing_traning_cavity.py ../square2D_2112/DRLinFluids_square/launch_multiprocessing_traning_square.py 
5c5
< import envobject_cavity
---
> import envobject_square
26c26
<     'num_processor': 16,
---
>     'num_processor': 4,
28c28
<     'cfd_init_time': 0.05,
---
>     'cfd_init_time': 0.005,
35c35
<         'actuator': {
---
>         'JET4': {
46c46
<         'actuator': {
---
>         'JET4': {
57c57
<         'actuator': {
---
>         'JET4': {
72c72
<     'interaction_period': 0.3,
---
>     'interaction_period': 0.025,
74c74
<     'writeInterval': 0.3,
---
>     'writeInterval': 0.025,
91c91
<     env = envobject_cavity.cavityNoise2D(
---
>     env = envobject_square.FlowAroundSquare2D(

can you please let me know what I can do ? 

Thanks 
Wei

**Comment by moi567** [comment]
Have you solved this problem?
